### ISSUE TITLE
ReflectorRunnable retries at a very high frequency while trying to reconnect informer

### ISSUE THREAD

**Issue by avmohan** [kubernetes-client/java#1030]
When a shared informer is created on a cluster, `ReflectorRunnable` keeps retrying list-watch at a very high frequency and filling up the logs with stack traces. Any clues on how to go about fixing this? Is it ok to just suppress this logger?

Check the timestamps - it seems to be retrying too fast.
```I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
I 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching... 
E 2020-07-02T05:10:12.053364412Z class io.kubernetes.client.openapi.models.V1DaemonSet#Failed to list-watch: {} 
```

Exception stack trace for the error lines:
```
io.kubernetes.client.openapi.ApiException: 
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:979)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:141)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yue9944882** [comment]
this is weird.. by default, the reflector retries list-watching w/ a constant 1 second backoff.. but from your pasted logs, it looks like looping w/o any backing-off.. what version are you using?

https://github.com/kubernetes-client/java/blob/8f5aabe0f6e8a9e8190d8f8225033c3d736c0d3b/util/src/main/java/io/kubernetes/client/informer/cache/Controller.java#L107-L108

additionally customized exception handling for lister-watcher is supported by https://github.com/kubernetes-client/java/pull/1026. you're free to develop your own backoff policy in the handler. thanks.

**Comment by avmohan** [comment]
I'm on version 8.0.2

**Comment by avmohan** [comment]
Based on the linked code, it does seems like it should retry at 1 second interval only. And I'm on the latest version too. Weird.
The mentioned pr seems to be not released. Will use the back off once it gets out.
