### ISSUE TITLE
How To Create New Pod

### ISSUE THREAD

**Issue by ryan-levell-twc** [kubernetes-client/java#109]
I have a pod.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-name
spec:
...
```
Using `kubectl` I can create this pod with:
```
kubectl apply -f pod.yaml
```

How can I do this with this java API?

My first attempt was to use `createNamespacedPod`:
```
V1Pod pod = api.createNamespacedPod("default", podBody, "false");
```
My pod body I want to create:
```
		V1ObjectMeta meta = new V1ObjectMeta();
		meta.name("my-name");

		V1EnvVar addr = new V1EnvVar();
		addr.name("var1");
		addr.value("value1");

		V1EnvVar port = new V1EnvVar();
		addr.name("var2");
		addr.value("value2");

		V1ResourceRequirements res = new V1ResourceRequirements();
		Map<String, String> limits = new HashMap<>();
		limits.put("cpu", "300m");
		limits.put("memory", "500Mi");
		res.limits(limits);

		V1Container container = new V1Container();
		container.name("my-name");
		container.image("my-image");
		container.env(Arrays.asList(addr, port));
		container.resources(res);

		V1PodSpec spec = new V1PodSpec();
		spec.containers(Arrays.asList(container));

		V1Pod podBody = new V1Pod();
		podBody.apiVersion("v1");
		podBody.kind("Pod");
		podBody.metadata(meta);
		podBody.spec(spec);
```

I am getting:
```
Exception in thread "main" io.kubernetes.client.ApiException: Unprocessable Entity
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPodWithHttpInfo(CoreV1Api.java:8223)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPod(CoreV1Api.java:8207)
```

EDIT: Sorry, I did not include the code that is actually causing the problem, added in the env vars and resource limits part. It works correctly when that code is not included:
Pod created when I delete:
```
		V1EnvVar addr = new V1EnvVar();
		addr.name("var1");
		addr.value("value1");

		V1EnvVar port = new V1EnvVar();
		addr.name("var2");
		addr.value("value2");

		V1ResourceRequirements res = new V1ResourceRequirements();
		Map<String, String> limits = new HashMap<>();
		limits.put("cpu", "300m");
		limits.put("memory", "500Mi");
		res.limits(limits);
```

**Comment by ryan-levell-twc** [comment]
Yikes, it was just a copy/paste error amplified by my first time using the API so I thought it was something more serious :)

```
		V1EnvVar addr = new V1EnvVar();
		addr.name("var1");
		addr.value("value1");

		V1EnvVar port = new ();
		addr.name("var2");
		addr.value("value2");
```
I used `addr` instead of `port` for the second `V1EnvVar`.
