### ISSUE TITLE
NetworkPolicyPort fails at numerical ports

### ISSUE THREAD

**Issue by kadwanev** [kubernetes-client/java#115]
Any attempt at saving a V1NetworkPolicyPort fails with:
```Invalid value: \"80\": must contain at least one letter or number (a-z, 0-9)```

It looks like this value should be an IntOrString type rather than a string so that the rendered json would be of int type when required and string type otherwise.

**Comment by brendandburns** [comment]
I think we need to regenerate code, now that https://github.com/kubernetes-client/gen/pull/30 has merged.

**Comment by kadwanev** [comment]
Is that something I can do locally to verify the fix in my case?

**Comment by brendandburns** [comment]
The (rather terse) instructions are here:

https://github.com/kubernetes-client/java#update-client

If that isn't clear, let me know and I will improve the docs. the `gen` repo is:

https://github.com/kubernetes-client/gen

**Comment by Rafaesp** [comment]
I get
`Exception in thread "main" io.kubernetes.client.ApiException: Unprocessable Entity
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.NetworkingV1Api.createNamespacedNetworkPolicyWithHttpInfo(NetworkingV1Api.java:164)
	at io.kubernetes.client.apis.NetworkingV1Api.createNamespacedNetworkPolicy(NetworkingV1Api.java:148)
	at es.rafa.kubetest.App.main(App.java:70)
`

This the same issue, right? How can I see that detailed description of the error?
