### ISSUE TITLE
LeaderElectionTest is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#1218]
```
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.808 s <<< FAILURE! - in io.kubernetes.client.extended.leaderelection.LeaderElectionTest
[ERROR] testLeaderElectionReportLeaderOnStart(io.kubernetes.client.extended.leaderelection.LeaderElectionTest)  Time elapsed: 2.846 s  <<< ERROR!
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 

 cannot be returned by identity()
identity() should return String
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
   Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.

	at io.kubernetes.client.extended.leaderelection.LeaderElectionTest.testLeaderElectionReportLeaderOnStart(LeaderElectionTest.java:328)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
```

**Comment by brendandburns** [comment]
Reopening this with a new failure:

Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.087 s <<< FAILURE! - in io.kubernetes.client.extended.leaderelection.LeaderElectionTest
Error:  testLeaderElectionWithRenewDeadline(io.kubernetes.client.extended.leaderelection.LeaderElectionTest)  Time elapsed: 1.402 s  <<< FAILURE!
java.lang.AssertionError: expected:<9> but was:<8>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.kubernetes.client.extended.leaderelection.LeaderElectionTest.assertHistory(LeaderElectionTest.java:265)
	at io.kubernetes.client.extended.leaderelection.LeaderElectionTest.testLeaderElectionWithRenewDeadline(LeaderElectionTest.java:248)
