### ISSUE TITLE
NoClassDefFoundError using .kube/config

### ISSUE THREAD

**Issue by tmella** [kubernetes-client/java#1273]
I am trying to list all Namespaces in my cluster from outside, however whenever try to do so I am encountered with the following error:

`ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: com/microsoft/aad/adal4j/AuthenticationContext
java.lang.NoClassDefFoundError: com/microsoft/aad/adal4j/AuthenticationContext
        at io.kubernetes.client.util.authenticators.AzureActiveDirectoryAuthenticator.refresh(AzureActiveDirectoryAuthenticator.java:67)
        at io.kubernetes.client.util.KubeConfig.getAccessToken(KubeConfig.java:215)
        at io.kubernetes.client.util.credentials.KubeconfigAuthentication.<init>(KubeconfigAuthentication.java:46)
        at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:276)
        at io.kubernetes.client.util.ClientBuilder.getClientBuilder(ClientBuilder.java:108)
        at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:87)
        at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:79)
        at io.kubernetes.client.util.Config.defaultClient(Config.java:113)`

I have been working on this project for a long time and it has only started happening to me this week. I have not tampered with any of the dependencies of the project or changed the implementation. 

I am currently using the following version of the project "io.kubernetes:client-java:9.0.0".

The steps to reproduce are to simply call:

`ApiClient client = Config.defaultClient();`

The issue occurs on the line of code shown above (first line in the project).

**Comment by brendandburns** [comment]
The `adal` libraries are marked as `optional` for this library because they are Azure specific (and large)

You need to add the following dependency to the `pom.xml` for your project:

```
      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>adal4j</artifactId>
        <version>1.6.5</version>
      </dependency>
```

Then the adal library will be pulled in as a dependency.

My guess is either a) you were previously getting this dependency from some other source or b) you never had to refresh tokens before recently.

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/blob/338411901836fbb8001e04c6cc420cc2010843e4/pom.xml#L130

i agree it's the optionality issue..

**Comment by mlauke** [comment]
mhm... i think if the adal library is optional, then the _ io.kubernetes.client.util.KubeConfig.getAccessToken()_ should be aware of this. in terms of "adal4j" acts as a k8s driver and it's not available then this should result in a warning, but not in a runtime error here. i've mixed kube configs for aws, azure at the same time and no idea how to tackle this.
