### ISSUE TITLE
Bad error message returned when trying to hit an endpoint that doesn't exist

### ISSUE THREAD

**Issue by mvaal** [kubernetes-client/java#1328]
When hitting a cluster for a type that isn't installed yet, it is returning a 404 error with the message `404 page not found`.

Unfortunately this attempts to deserialize to a V1Status object here:
https://github.com/kubernetes-client/java/blob/b0ea48e144083706f1bac9942e4d209d4282d5ff/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L737

And throws the following error:
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) ~[gson-2.8.6.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:na]
	at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:137) ~[client-java-api-10.0.0.jar:na]
	at io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:737) ~[client-java-10.0.0.jar:na]
	at io.kubernetes.client.util.generic.GenericKubernetesApi.get(GenericKubernetesApi.java:319) ~[client-java-10.0.0.jar:na]
	at io.kubernetes.client.util.generic.GenericKubernetesApi.get(GenericKubernetesApi.java:170) ~[client-java-10.0.0.jar:na]
```

Which is extremely misleading. Should catch this before attempted deserialization.

**Comment by yue9944882** [comment]
@mvaal thanks for reporting this, i filed a fix at #1331
