### ISSUE TITLE
Reflector doesn't shutdown gracefully on thread interruption

### ISSUE THREAD

**Issue by iyashu** [kubernetes-client/java#1329]
I'm trying to build an informer using `DefaultSharedIndexInformer` watching for ConfigMap resources and noticed that on stopping the informer (using `DefaultSharedIndexInformer::stop`) `main` function doesn't exits. After taking thread dump using jstack, I've found that reflector thread is not terminated. Below is the complete example to reproduce with java version 1.8.0_191 and client version 9.0.2.
<details>
<summary> Example Code </summary>

```java
package io.kubernetes.client.util.example;

import com.google.gson.reflect.TypeToken;
import io.kubernetes.client.informer.ListerWatcher;
import io.kubernetes.client.informer.ResourceEventHandler;
import io.kubernetes.client.informer.SharedInformer;
import io.kubernetes.client.informer.impl.DefaultSharedIndexInformer;
import io.kubernetes.client.openapi.ApiClient;
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.apis.CoreV1Api;
import io.kubernetes.client.openapi.models.V1ConfigMap;
import io.kubernetes.client.openapi.models.V1ConfigMapList;
import io.kubernetes.client.util.CallGeneratorParams;
import io.kubernetes.client.util.Config;
import io.kubernetes.client.util.Watch;
import io.kubernetes.client.util.Watchable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

public class SimpleUsageExample {
    private static final Logger logger = LoggerFactory.getLogger(SimpleUsageExample.class);

    private static final ExecutorService DEFAULT_EXECUTOR = Executors.newFixedThreadPool(20, r -> {
        Thread thread = new Thread(r, "ConfigMapThread");
        thread.setDaemon(true);
        return thread;
    });


    public static void main(String[] args) throws Exception {
        logger.info("starting up the main");
        ExecutorService executorService = DEFAULT_EXECUTOR;

        V1ConfigMap configMap;

        ApiClient apiClient = Config.fromConfig("emma.kubeconfig");
        apiClient.setReadTimeout(0);
        String fieldSelector = "metadata.name=test";
        String namespace = "configmap-test";

        CoreV1Api coreV1Api = new CoreV1Api(apiClient);

        SharedInformer<V1ConfigMap> informer = new DefaultSharedIndexInformer<>(V1ConfigMap.class, new ListerWatcher<V1ConfigMap, V1ConfigMapList>() {
            @Override
            public V1ConfigMapList list(CallGeneratorParams params) throws ApiException {
                return coreV1Api.listNamespacedConfigMap(namespace, null, true, null,
                        fieldSelector, null, null,
                        params.resourceVersion, params.timeoutSeconds, params.watch);
            }

            @Override
            public Watchable<V1ConfigMap> watch(CallGeneratorParams params) throws ApiException {
                return Watch.createWatch(apiClient,
                        coreV1Api.listNamespacedConfigMapCall(namespace, null, true, null,
                                fieldSelector, null, null,
                                params.resourceVersion, params.timeoutSeconds, params.watch, null),
                        new TypeToken<Watch.Response<V1ConfigMap>>() {
                        }.getType());
            }
        }, 0);

        informer.addEventHandler(new ResourceEventHandler<V1ConfigMap>() {
            @Override
            public void onAdd(V1ConfigMap cm) {
                System.out.printf("%s config map added!\n", cm.getMetadata().getName());
            }

            @Override
            public void onUpdate(V1ConfigMap oldCm, V1ConfigMap newCm) {
                System.out.printf(
                        "%s => %s config map updated!\n",
                        oldCm.getMetadata().getName(), newCm.getMetadata().getName());
            }

            @Override
            public void onDelete(V1ConfigMap cm, boolean deletedFinalStateUnknown) {
                System.out.printf("%s config map deleted!\n", cm.getMetadata().getName());
            }
        });
        informer.run();

        long timeoutInMillis = TimeUnit.SECONDS.toMillis(20);
        try {
            long start = System.currentTimeMillis();
            while (!informer.hasSynced()) {
                if (System.currentTimeMillis() - start > timeoutInMillis) {
                    throw new TimeoutException(String.format("informer store cache has not been synced within %d ms",
                            timeoutInMillis));
                }
                Thread.sleep(TimeUnit.SECONDS.toMillis(1));
            }
        } catch (Exception ex) {
            informer.stop();
            throw ex;
        }
        informer.stop();
        System.out.println("exiting main...");
    }
}
```

</details>

**Relevant Thread Dump** 
```
"controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-0" #16 prio=5 os_prio=31 tid=0x00007fda9d94c000 nid=0xa303 runnable [0x00007000036e4000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	- locked <0x000000076d4d5fc0> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	- locked <0x000000076d4f2b58> (a sun.security.ssl.AppInputStream)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:72)
	at okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:307)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:492)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
	at io.kubernetes.client.util.Watch.hasNext(Watch.java:182)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.watchHandler(ReflectorRunnable.java:169)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:110)
	at io.kubernetes.client.informer.cache.Controller$$Lambda$16/1983988693.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

On inspecting the source code, it seems that watch.hasNext under watchHandler doesn't gets interrupted on thread interrupt.
https://github.com/kubernetes-client/java/blob/45d246d03c0d49c125c0c64d2de5d235ab1a972f/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L160

One fix that working as of now is to force watch close under [ReflectorRunnable::stop](https://github.com/kubernetes-client/java/blob/45d246d03c0d49c125c0c64d2de5d235ab1a972f/util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java#L146) method like - 
```java
  public void stop() {
    isActive.set(false);
    if (watch != null) {
      try {
        watch.close();
      } catch (IOException ex) {
        throw new RuntimeException(ex);
      }
    }
  }
```
One obvious catch is we need to synchronize that watch variable using some locking mechanism. If you like I can create a pull request if looks good. Thoughts?

**Comment by yue9944882** [comment]
> One fix that working as of now is to force watch close under ReflectorRunnable::stop method like -

this approach sounds good to me. can you send a PR so that we can merge?
