### ISSUE TITLE
Run KubeConfigFileClientExample.java，get Exception

### ISSUE THREAD

**Issue by mxtsuper** [kubernetes-client/java#1342]
Hello
I run the KubeConfigFileClientExample.java on my PC outsides a  K8s cluster.
I copied the config file on the PC. I did not copy the certificates and keys on the PC.

I got the exception as followings.  
Please give me some hints on deal with them. 
Do I need to load the certificates and keys on the PC ? But they will be in different path.
Thanks a lot
Exception in thread "main" io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:886)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:35051)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:34949)
	at pretrochina.TestClient.main(TestClient.java:31)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:327)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:270)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:265)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1344)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1219)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1162)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:451)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:428)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:184)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1196)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1105)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:399)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:371)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:882)
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1328)
	... 35 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 41 more

**Comment by yue9944882** [comment]
@mxtsuper can you double check whether the file path is correct or do you have the permission to the file?

**Comment by mxtsuper** [comment]
Hello yue9944882 . 
I checked the config file, and debug the codes.
It read the config file, get the config data, such as basefile etc. 
It has the same errors.

![image](https://user-images.githubusercontent.com/24969526/97142934-a5dd1a80-179c-11eb-814d-cc4413f82a1f.png)

**Comment by brendandburns** [comment]
My guess is that your kubeconfig file is malformed somehow and the CA cert is invalid. Does `kubectl` work with the same `kubeconfig` file?

**Comment by mxtsuper** [comment]
kubectl works

**Comment by brendandburns** [comment]
Just to be clear `kubectl --kubeconfig <path-to-kubeconfig> get nodes` works correctly?

Do any of the other examples work correctly?

Can you attach your kubeconfig file? (please remove all secret info first)

It very much looks like the code is unable to load the CA root certificate, so we need to understand more about that certificate and how it is being passed into the client code.

**Comment by kalyan123i** [comment]
HI, +1 
I face similar issue when connecting it AKS

**Comment by kalyan123i** [comment]
Fixed it by disabling the ssl over the proxy, this is not preferred for prod and pre-prod clusters. Only for testing and debugging lower environments :)
ref : https://stackoverflow.com/questions/42288868/okhttp3-accept-all-certificates-and-use-a-certificatepinner/43120474

@mxtsuper

**Comment by brendandburns** [comment]
Can you send the Java version (and OS) that you are using?

And when you say "over a proxy" what do you mean? is there an HTTP proxy between you and AKS?

**Comment by kalyan123i** [comment]
@brendanburns 
I am using java version 8 and Os is via windows. I am using the AKS cluster at microsoft. We have proxy in organization to talk to internet. So, we have to offload the proxy there , to make the current client version (10.1) work.

I am no issue till version 6.X from 7.X and above i see this issue...
For any k8's version i see same issue


Sample code what i have done. 

`SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
    sslContext.init(null, new TrustManager[]{
      new X509TrustManager() {
        @Override
        public void checkClientTrusted(java.security.cert.X509Certificate[] chain,
                                       String authType) throws CertificateException {
        }

        @Override
        public void checkServerTrusted(java.security.cert.X509Certificate[] chain,
                                       String authType) throws CertificateException {
        }

        @Override
        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
          return new X509Certificate[0];
        }
      }
    }, new java.security.SecureRandom());



    OkHttpClient proxyClient = new OkHttpClient
      .Builder()
      .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("XXXX.proxy.XXXXXXX.XXXX", 8080)))
      .sslSocketFactory(sslContext.getSocketFactory(),
        new X509TrustManager() {
          @Override
          public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
          }

          @Override
          public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
          }

          @Override
          public java.security.cert.X509Certificate[] getAcceptedIssuers() {
            return new java.security.cert.X509Certificate[]{};
          }
        })
      .build();

    apiClient.setHttpClient(proxyClient);

    CoreV1Api coreV1Api = new CoreV1Api(apiClient);`
