### ISSUE TITLE
Incorrect exit code in current Exec implementation

### ISSUE THREAD

**Issue by panashka** [kubernetes-client/java#1346]
Hi,
I stumbled upon https://github.com/kubernetes-client/java/issues/861. I'm experiencing the same issue.
But it's already closed so I decided to raise new one. 
In the previous bug it was mentioned that exceptions like "java.net.SocketException: Connection closed by remote host" are expected on connection termination. The thing is:
If actual command complete with status 0, eventually its code will be overwritten with -1975219. 
```    @Override
            public void failure(Throwable ex) {
              super.failure(ex);
              // TODO, it's possible we should suppress this error message, but
              // currently there's
              // no good place to surface the message, and without it, this will be
              // really hard to
              // debug.
              ex.printStackTrace();
              synchronized (ExecProcess.this) {
                // Try for a pretty unique error code, so if someone searches
                // they'll find this
                // code.
                statusCode = -1975219;
                isAlive = false;
                ExecProcess.this.latch.countDown();
              }
            }
```
So if I am lucky to grab status code before mentioned exception, I get 0 or whatever correct status is. If not, I get  -1975219. 
Maybe you can do like below so that actual exit code didn't get overwritten.
```
@Override
                        public void failure(final Throwable exception) {
                            super.failure(exception);
                            synchronized (ExecProcess.this) {
                                if (latch.getCount() != 0) {
                                    statusCode = -1_975_219;
                                    isAlive = false;
                                    ExecProcess.this.latch.countDown();
                                }
                            }
                        }
```
Thank you!

**Comment by dzhi-lyft** [comment]
Related to the issue, I am interested in how to avoid the exception or suppress it in console output.

```
java.net.SocketException: Connection closed by remote host
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1547)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
        ......
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
