### ISSUE TITLE
java.io.IOException: Invalid DER: object is not integer

### ISSUE THREAD

**Issue by jevin36** [kubernetes-client/java#135]
Hi,

I am trying to get the client api (0.2) up and running but unfortunately I am getting the following error:
```
2017-12-05 16:21:10 ERROR {main} io.kubernetes.client.util.Config - Failed to invoke build key managers
java.io.IOException: Invalid DER: object is not integer
	at io.kubernetes.client.util.SSLUtils$Asn1Object.getInteger(SSLUtils.java:229)
	at io.kubernetes.client.util.SSLUtils.next(SSLUtils.java:160)
	at io.kubernetes.client.util.SSLUtils.decodePKCS1(SSLUtils.java:155)
	at io.kubernetes.client.util.SSLUtils.createKeyStore(SSLUtils.java:100)
	at io.kubernetes.client.util.SSLUtils.createKeyStore(SSLUtils.java:78)
	at io.kubernetes.client.util.SSLUtils.keyManagers(SSLUtils.java:63)
	at io.kubernetes.client.util.Config.fromConfig(Config.java:110)
```
I tried it with the following code (via config yaml as string and via ~/.kube/config file)

```
ApiClient apiClient = Config
                    .fromConfig(configAsString)
                    //.fromConfig(new FileReader("/Users/me/.kube/config"))
                    .setVerifyingSsl(false);
Configuration.setDefaultApiClient(apiClient);
```

kubectl on command line works fine with my config

Do you have any suggestions?

**Comment by lwander** [comment]
The authenticators here aren't fully fleshed-out. Have you tried with the 1.0.0-beta1 release?

**Comment by brendandburns** [comment]
This looks like your SSL key isn't in the expected format...

Can you share the key format (obviously, please obfuscate the key itselft)

**Comment by jevin36** [comment]
Hi,
sorry I don't have it at hand right now. I think it was in a pem format so I converted the pem to der and tried it again. Unfortunately that didn't work either.

**Comment by brendandburns** [comment]
I'm going to close this, since I think that it was a badly formatted key.  If this re-occurs and you have the key, please re-open this issue and send the key along and we can try to debug.

**Comment by jevin36** [comment]
Hi @brendanburns , I finally got a go from the customer I am working at to share the kubeconfig, but I am not supposed to post it online. Is it possible to pm it to you?
