### ISSUE TITLE
GenericKubernetesApi return errors ` Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $`

### ISSUE THREAD

**Issue by Bryce-huang** [kubernetes-client/java#1350]
I use the latest code generator to generate crd code and use GenericKubernetesApi to call k8s api, but it returns an error，like：
```java
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:138)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:713)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.get(GenericKubernetesApi.java:294)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.get(GenericKubernetesApi.java:158)
	at models.Main.main(Main.java:24)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 8 more
```

the java code :

```java
var client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(config)))
                                  .build();
        Configuration.setDefaultApiClient(client);
        GenericKubernetesApi<V1beta1ProcessService, V1beta1ProcessServiceList> api = new GenericKubernetesApi<>(V1beta1ProcessService.class, V1beta1ProcessServiceList.class, group, version, plural);
        System.out.println(Yaml.dump(api.get("processservice-sample")));
```
the k8s info 
```
I1029 11:39:06.251496    9159 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json" -H "User-Agent: kubectl/v1.18.8 (linux/amd64) kubernetes/9f2892a" 'https://kubernetes.docker.internal:6443/apis/oide.szsandstone.com/v1beta1/namespaces/default/processservices?limit=500'
I1029 11:39:06.260031    9159 round_trippers.go:443] GET https://kubernetes.docker.internal:6443/apis/oide.szsandstone.com/v1beta1/namespaces/default/processservices?limit=500 200 OK in 8 milliseconds
I1029 11:39:06.260088    9159 round_trippers.go:449] Response Headers:
I1029 11:39:06.260139    9159 round_trippers.go:452]     Content-Type: application/json
I1029 11:39:06.260168    9159 round_trippers.go:452]     Content-Length: 2798
I1029 11:39:06.260199    9159 round_trippers.go:452]     Date: Thu, 29 Oct 2020 03:39:06 GMT
I1029 11:39:06.260227    9159 round_trippers.go:452]     Cache-Control: no-cache, private


NAME                    AGE
processservice-sample   26m
```

client version : 9.0.2

**Comment by Bryce-huang** [comment]
After I configured all the information correctly and set the namespace parameter for the get method, I found that the crd object can be successfully obtained, but the crd object still cannot be created. I will continue to troubleshoot errors
`api.get("default","processservice-sample"); `

**Comment by yue9944882** [comment]
is this a duplicate of https://github.com/kubernetes-client/java/issues/1328? if so, the fix has landed on master.

**Comment by Bryce-huang** [comment]
Thanks, it may be that the crd object I constructed is incorrect.
