### ISSUE TITLE
When I use ‘（(KubectlDrain) Kubectl.drain().apiClient(apiClient).name(name).execute()，  as follow exception

### ISSUE THREAD

**Issue by ssvvnn** [kubernetes-client/java#1362]
When I use ‘（(KubectlDrain) Kubectl.drain().apiClient(apiClient).name(name).execute()，  as follow exception
java.lang.NullPointerException: null
	at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:259)
	at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:293)
	at io.kubernetes.client.extended.kubectl.KubectlCordon.performCordon(KubectlCordon.java:43)
	at io.kubernetes.client.extended.kubectl.KubectlDrain.doDrain(KubectlDrain.java:62)
	at io.kubernetes.client.extended.kubectl.KubectlDrain.execute(KubectlDrain.java:54)
	at com.deepexi.kubebox.repo.NodeRepository.drain(NodeRepository.java:54)
	at com.deepexi.kubebox.repo.NodeRepository$$FastClassBySpringCGLIB$$dc20e267.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.deepexi.kubebox.repo.NodeRepository$$EnhancerBySpringCGLIB$$39e340a3.drain(<generated>)
	at com.deepexi.kubebox.domain.entity.Node.drain(Node.java:99)
	at com.deepexi.kubebox.service.NodeService.drain(NodeService.java:71)
	at com.deepexi.kubebox.service.NodeService$$FastClassBySpringCGLIB$$2289a9d9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

**Comment by brendandburns** [comment]
The ModelMap isn't loading correctly (it appears)

Do you see any other errors before this?

Can you try adding `ModelMap.refresh(...)` before your `Kubectl.drain().(...)` call?

**Comment by ssvvnn** [comment]
> The ModelMap isn't loading correctly (it appears)
> 
> Do you see any other errors before this?
> 
> Can you try adding `ModelMap.refresh(...)` before your `Kubectl.drain().(...)` call?
I  have resolved this problem by adding ‘ModelMapper.refresh(new Discovery(apiClient))’，is it a bug ?

**Comment by ssvvnn** [comment]
And I have a another problem, this method  KubectlDrain.gracePeriod(...)  is seems like that a timeout seconds, not as offical shows:
grace-period |   | -1 | Period of time in seconds given to each pod to terminate gracefully. If negative, the default value specified in the pod will be used.

**Comment by brendandburns** [comment]
I'm glad the first issue is resolved.

Two requests:
* Can you give me details of how you were calling the code? The model map should be created by a static initializer when the class is loaded, so I want to understand what is going wrong in case there is a deeper issue.

* Can you open a separate issue for the second problem (the grace period one) so that we can track it separately? Also, please add some more details to that issue, I don't quite understand the problem you are facing.

Thanks!

**Comment by ssvvnn** [comment]
> I'm glad the first issue is resolved.
> 
> Two requests:
> 
> * Can you give me details of how you were calling the code? The model map should be created by a static initializer when the class is loaded, so I want to understand what is going wrong in case there is a deeper issue.
> * Can you open a separate issue for the second problem (the grace period one) so that we can track it separately? Also, please add some more details to that issue, I don't quite understand the problem you are facing.
> 
> Thanks!

ok，that was how called to the code:
maven dependency:
  <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-extended</artifactId>
            <version>10.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>10.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.sundr</groupId>
                    <artifactId>sundr-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.sundr</groupId>
                    <artifactId>sundr-codegen</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.sundr</groupId>
                    <artifactId>builder-annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
the  code:
(KubectlDrain) Kubectl.drain().apiClient(apiClient).name(name).execute();
the exception:
java.lang.NullPointerException: null
at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:259)
at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:293)
at io.kubernetes.client.extended.kubectl.KubectlCordon.performCordon(KubectlCordon.java:43)
at io.kubernetes.client.extended.kubectl.KubectlDrain.doDrain(KubectlDrain.java:62)
at io.kubernetes.client.extended.kubectl.KubectlDrain.execute(KubectlDrain.java:54)
at com.deepexi.kubebox.repo.NodeRepository.drain(NodeRepository.java:54)
at com.deepexi.kubebox.repo.NodeRepository$$FastClassBySpringCGLIB$$dc20e267.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
