### ISSUE TITLE
When I use KubectlCordon, appears NullPointerException. After adding ModelMapper.refresh, resolved with local environment, but appears NullPointerException again when I run it in Linux by java -jar

### ISSUE THREAD

**Issue by nusguoqi** [kubernetes-client/java#1394]
Exception as follows
ERROR c.icbc.ydjr.paas.kube.impl.KubeClientApiHelperImpl - kubectlOperate Error 
java.lang.NullPointerException: null 
        at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:259) 
        at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:293) 
        at io.kubernetes.client.extended.kubectl.KubectlCordon.performCordon(KubectlCordon.java:43) 
        at io.kubernetes.client.extended.kubectl.KubectlCordon.execute(KubectlCordon.java:37) 
        at com.icbc.ydjr.paas.kube.KubectlUtil.operate(KubectlUtil.java:128) 
        at com.icbc.ydjr.paas.kube.impl.KubeClientApiHelperImpl.kubectlOperate(KubeClientApiHelperImpl.java:826) 
        at com.icbc.ydjr.paas.controller.NodeController.nodeSchedulePolicy(NodeController.java:206) 
        at com.icbc.ydjr.paas.controller.NodeController$$FastClassBySpringCGLIB$$a962ff9a.invoke(<generated>) 
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) 
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) 
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) 
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52) 
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) 
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) 
        at com.icbc.ydjr.paas.aspect.LogAspect.doAround(LogAspect.java:47) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
        at java.lang.reflect.Method.invoke(Method.java:498) 

My code as follows:
//init client
String root = System.getProperty("user.dir");
String fileName = "kubectl.kubeconfig";
ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(filePath+fileName))).build();
Configuration.setDefaultApiClient(client); 

//...
//perform cordon
case "cordon":
   ModelMapper.refresh(new Discovery(client));
   cordon().apiClient(client).name(kubectlTemplate.getKindName()).execute();
   log.info("Node|"+ kubectlTemplate.getKindName() +"|cordoned");
   return 0;

I met this exception before, and I added (ModelMapper.refresh(new Discovery(client));)
It only works for my local env(jdk 1.8, windows, Idea), when I run it with java -jar on a linux (jdk1.8, SUSE), the exception appears again.
Any ideas for me to try?

**Comment by brendandburns** [comment]
API discovery isn't working properly. My guess is that it is because your linux environment doesn't have the right credentials for your Kubernetes cluster, but I'm not certain.

The basic problem is that the ModelMapper doesn't have an entry for the `V1Node` class.

You could manually add the mapping (eg. `ModelMapper.addModelMap("", "v1", "node", "nodes", V1Node.class)`

which should resolve the issue, but it is very weird that discovery isn't working for you automatically.
