### ISSUE TITLE
snakeyaml cannot convert the string to V1beta1Ingress object

### ISSUE THREAD

**Issue by nijov** [kubernetes-client/java#148]
I am using yaml.dump() method to store the V1beta1Ingress object as a string. But when I load it back to the V1beta1Ingress object it fails. The problem is with IntOrString conversion I think.

Code:
    	Yaml yaml = new Yaml(new Constructor(), repr);
    	File configFile = new File(yamlIngressTemplateWithPath);
    	FileReader input = new FileReader(configFile);
    	V1beta1Ingress body = (V1beta1Ingress ) yaml.loadAs(input, V1beta1Ingress.class);
    	
	String bodystring = yaml.dump(body);
    	V1beta1Ingress bodynew = (V1beta1Ingress ) yaml.loadAs(bodystring, V1beta1Ingress.class);

Error:

java.lang.NoSuchMethodException: io.kubernetes.client.custom.IntOrString.<init>()
 in 'string', line 32, column 24:
              servicePort: {}
                           ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:313)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:298)
	... 53 more
Caused by: org.yaml.snakeyaml.error.YAMLException: java.lang.NoSuchMethodException: io.kubernetes.client.custom.IntOrString.<init>()
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.createEmptyJavaBean(Constructor.java:220)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:184)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:298)
	... 56 more
Caused by: java.lang.NoSuchMethodException: io.kubernetes.client.custom.IntOrString.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.createEmptyJavaBean(Constructor.java:216)
	... 59 more

**Comment by kondapally1989** [comment]
well it worked for me with out any issue

following is the code i used ( your code only)

```
Representer repr = new Representer();
Yaml yaml = new Yaml(new Constructor(), repr );
String yamlIngressTemplateWithPath = "kubernetes/src/test/java/template.yaml";
File configFile = new File(yamlIngressTemplateWithPath);
FileReader input = new FileReader(configFile);
V1beta1Ingress body = (V1beta1Ingress ) yaml.loadAs(input, V1beta1Ingress.class);
String bodystring = yaml.dump(body);
V1beta1Ingress bodynew = (V1beta1Ingress ) yaml.loadAs(bodystring, V1beta1Ingress.class);
System.out.println(bodynew);
```

and following is the yaml: 

```
kind: V1beta1Ingress
metadata:
    clusterName: test
spec:
    rules: [{host: host2}]
```
Did you pull the latest code and build the jar ?
project contains class:  io.kubernetes.client.custom.IntOrString

**Comment by nijov** [comment]
Thank you for the response. This is my yaml file. If I remove the line servicePort: 8080 , it will work. If I add it, it is not working.

kind: Ingress
metadata:
  clusterName: myappcluster
  annotations:
    ingress.kubernetes.io/rewrite-target: /aptappiaas
spec:
  rules:
  - host: itlab5.it.com
    http:
      paths:
      - backend:
          serviceName: afc-iaas
          servicePort: 8080
        path: /aptappiaas

**Comment by brendandburns** [comment]
This is outside of the scope of this client library (for now at least) so I'm going to close this issue, but I think you need to do something like this:

https://bitbucket.org/asomov/snakeyaml/wiki/Howto#markdown-header-how-to-substitute-object-in-yaml-document-with-a-custom-object
