### ISSUE TITLE
Watch example timeouts after few seconds

### ISSUE THREAD

**Issue by scholzj** [kubernetes-client/java#150]
When I try to run `WatchExample.java`, the Watch seems to work only for few seconds. After ~10 seconds after the last update it ttriggers following exception:

```
Exception in thread "main" java.lang.RuntimeException: IO Exception during hasNext method.
	at io.kubernetes.client.util.Watch.hasNext(Watch.java:111)
	at io.kubernetes.client.examples.WatchExample.main(WatchExample.java:41)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:454)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:435)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at io.kubernetes.client.util.Watch.hasNext(Watch.java:109)
	... 1 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 8 more
```

I don't think that is expected. I can see it with both master and 1.0.0-beta1. I'm runnng it against Minikube v0.24.1 (Kubernetes 1.8.0).

**Comment by brendandburns** [comment]
This is in the okhttp library.

You need to:

```
apiClient.getHttpClient().setReadTimeout(<something really long>)
```

https://github.com/square/okhttp/blob/okhttp_25/okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java#L252

We should add this to the example (want to send a PR? :)

**Comment by scholzj** [comment]
Thanks. That does the trick. I opened the PR #155 to add this to the example code.
