### ISSUE TITLE
Server Error and nullpointerException for backgroundFunctionExecutor

### ISSUE THREAD

**Issue by mahichachra** [kubernetes-client/java#1507]
The same code snippet is giving output in my local but when i have deployed the same as a cloud function which is using kubernetes client library which is using listNode method present in the CoreApi class i am getting nullpointerexception in BackgroundFunctionExecutor class and server error as well. In the below snippet i am able to print "Entered fetch" but after that i am getting error;

1. i am using CoreV1Api in io.kubernetes.client.openapi.apis.CoreV1Api
2. OS type and version:Mac
3. Java version:11
4. google-api-client version(s):1.31.1

Code snippet:
```
@Override
    public void accept(PubSubMessage pubSubMessage, Context context) throws Exception {
        test();
    }
private static void test() throws IOException, GeneralSecurityException, ApiException {
        CoreV1Api coreApi =createKubernetesService();
        fetch(coreApi);
    }
    private static CoreV1Api createKubernetesService() throws IOException {
        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);
        CoreV1Api coreApi = new CoreV1Api();
        return coreApi;
    }
    private static void fetch(CoreV1Api coreApi) throws ApiException, IOException, GeneralSecurityException {
        logger.info("Entered fetch");
        V1NodeList list =
                coreApi.listNode("true", false, null, null, null, 250, null, null, 900,false);
        logger.info("After fetching list");
    }
```

Stacktrace Obtained
```
io.kubernetes.client.openapi.ApiException: Server Error
                                                        	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:993)
                                                        	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:905)
                                                        	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:35956)
                                                        	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:35848)
                                                        	at TestCloudFunction.fetchNodePoolLabels(TestCloudFunction.java:44)
                                                        	at TestCloudFunction.test(TestCloudFunction.java:34)
                                                        	at TestCloudFunction.accept(TestCloudFunction.java:28)
                                                        	at TestCloudFunction.accept(TestCloudFunction.java:19)
                                                        	at com.google.cloud.functions.invoker.BackgroundFunctionExecutor$TypedFunctionExecutor.serviceLegacyEvent(BackgroundFunctionExecutor.java:285)
                                                        	at com.google.cloud.functions.invoker.BackgroundFunctionExecutor.lambda$serviceLegacyEvent$8(BackgroundFunctionExecutor.java:375)
                                                        	at com.google.cloud.functions.invoker.BackgroundFunctionExecutor.runWithContextClassLoader(BackgroundFunctionExecutor.java:382)
                                                        	at com.google.cloud.functions.invoker.BackgroundFunctionExecutor.serviceLegacyEvent(BackgroundFunctionExecutor.java:375)
                                                        	at com.google.cloud.functions.invoker.BackgroundFunctionExecutor.service(BackgroundFunctionExecutor.java:330)
                                                        	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
                                                        	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
                                                        	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
                                                        	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
                                                        	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
                                                        	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
                                                        	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
                                                        	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
                                                        	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
                                                        	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
                                                        	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                                                        	at com.google.cloud.functions.invoker.runner.Invoker$NotFoundHandler.handle(Invoker.java:388)
                                                        	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
                                                        	at org.eclipse.jetty.server.Server.handle(Server.java:500)
                                                        	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
                                                        	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
                                                        	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
                                                        	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
                                                        	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
                                                        	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
                                                        	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
                                                        	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
                                                        	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
                                                        	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by brendandburns** [comment]
ServerErrror indicates your server is returning a 500. Not sure why. If you print the response body from the ApiException you may get more details to help you debug.

**Comment by yue9944882** [comment]
@mahichachra 500 is usually connected w/ the bugs inside the kube-apiserver. can you paste detailed messages from the server's response?

**Comment by mahichachra** [comment]
but how can i print the body of Exception, it is getting generated in client library and i am only using it as dependency in pom, adding try catch and printing also wont make a difference i think

**Comment by brendandburns** [comment]
Sorry for the slow response.

You should be able to catch `ApiException` and then you should be able to use `ApiException.getResponseBody()` to print the details.

**Comment by brendandburns** [comment]
Closing this issue due to lack of response. Please use `/reopen` if you need to reopen it.
