### ISSUE TITLE
getRelistResourceVersion() is too old and causes infinite errors

### ISSUE THREAD

**Issue by tony-clarke-amdocs** [kubernetes-client/java#1533]
I tried updating to client 11.0.0. However, the logs get filled with the following errors:

```
2021-02-09 08:37:29.076 ERROR 78258 --- [s.V1ConfigMap-1] i.k.c.informer.cache.ReflectorRunnable   : class io.kubernetes.client.openapi.models.V1ConfigMap#Reflector loop failed unexpectedly

io.kubernetes.client.openapi.ApiException: Gone
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:993) ~[client-java-api-11.0.0.jar:na]
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:905) ~[client-java-api-11.0.0.jar:na]
	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:207) ~[client-java-11.0.0.jar:na]
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:77) ~[client-java-11.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) ~[na:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]

2021-02-09 08:37:30.454  INFO 78258 --- [s.V1ConfigMap-1] i.k.c.informer.cache.ReflectorRunnable   : class io.kubernetes.client.openapi.models.V1ConfigMap#Start listing and watching...

```

This error repeats forever. Looking into the actual exception I can see it is like this:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"The resourceVersion for the provided list is too old.","reason":"Expired","code":410}
```
I think this is a bug introduced with [this](https://github.com/kubernetes-client/java/commit/c8a47c91eacdef1ba4d03513786cb3d46c822464) commit. The last synced resource can become too old and we will always get an error if we retry using that resource version.

**Comment by brendandburns** [comment]
Agreed. We should catch the exception and retry without a resource version.

cc @yue9944882

**Comment by ryanjbaxter** [comment]
When can we expect an updated 11.0.x release?

**Comment by yue9944882** [comment]
@ryanjbaxter i just had https://github.com/kubernetes-client/java/pull/1552 picked to 11.0.x. @brendandburns how do you think about publishing a new release after merging the picked fix?

**Comment by ryanjbaxter** [comment]
@yue9944882 I see that the fix was merged.  @brendanburns can we do another release of 11.0.x?

**Comment by ryanjbaxter** [comment]
bump @brendanburns can we get a release of the 11.0.x branch?
