### ISSUE TITLE
 is the stream not closed when use exec with v8.0.0?

### ISSUE THREAD

**Issue by tingweiwu** [kubernetes-client/java#1547]
when I use 8.0.0 version and v1.15.11 version on the server side, I find that the exec don't  disconnect util timeout.
is this a bug?

```
java.io.IOException: Pipe broken
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:321)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:109)

```

is this solved on 8.0.1 and 8.0.2 by this commit?
https://github.com/kubernetes-client/java/commit/df2dbb40371ebb2a5386975097775f0bfd17546b

**Comment by brendandburns** [comment]
If your program in the container is exiting, but the stream is staying open, then yes, I think it is fixed by that commit.

**Comment by brendandburns** [comment]
Closing this issue because I believe the question is answered. Please use `/reopen` if further assistance is required.
