### ISSUE TITLE
Timeout error when executing listNamespacedJobs inside cluster

### ISSUE THREAD

**Issue by OberstHorst** [kubernetes-client/java#160]
Hey,
i am trying to use the Batch API to list all my jobs in a specific namespace. However when executing the command it returns a timeout error:
` io.kubernetes.client.ApiException: java.net.SocketTimeoutException: connect timed out
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:801)
	at io.kubernetes.client.apis.BatchV1Api.listNamespacedJobWithHttpInfo(BatchV1Api.java:977)
	at io.kubernetes.client.apis.BatchV1Api.listNamespacedJob(BatchV1Api.java:954)
	at de.jlu.bioinfsys.workflowUI.jobcleaner.kube.JobStatusChecker.getJobList(JobStatusChecker.java:49)
	at de.jlu.bioinfsys.workflowUI.jobcleaner.start.Run.main(Run.java:19)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:120)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:797)
	... 4 more `

This is my code:
```ApiClient client = Configuration.getDefaultApiClient();
        client.setBasePath(this.host);
        client.getHttpClient().setReadTimeout(60, TimeUnit.SECONDS);

        String key = readFile("/var/run/secrets/kubernetes.io/serviceaccount/token", Charset.defaultCharset());

        ApiKeyAuth BearerToken = (ApiKeyAuth) client.getAuthentication("BearerToken");
        BearerToken.setApiKey(key);

        Configuration.setDefaultApiClient(client);
        this.batchApiInstance = new BatchV1Api();
        this.batchApiInstance.getApiClient().getHttpClient().setConnectTimeout(10, TimeUnit.SECONDS);```

and the call itself:
```    public V1JobList getJobList() {
        V1JobList v1JobList = new V1JobList();
        try {
            v1JobList = batchApiInstance
                    .listNamespacedJob(namespace, pretty, "_continue_example", null, null, null, null, null, 60, null);
            } catch (ApiException e) {
            e.printStackTrace();
        }

        return v1JobList;
    }```

The namespace is "default" and the hostname is "http://kubernetes.default".
It runs as a single container pod using the Deployment API.
I use minikube v1.8 to execute the code.

Thanks in advance

**Comment by brendandburns** [comment]
This looks like nothing is listening where the client is looking.

Why are you setting `BasePath` in the client. If you are using `defaultClient()` everything should get setup correctly from your kubeconfig file.

**Comment by OberstHorst** [comment]
Okay i made it work. My problem was that i confused `defaultClient()` and `getDefaultApiClient()`. 
I did not see the `util.Conf` and thought is should use `client.Configuration`
Thanks for helping
