### ISSUE TITLE
ExtensionsV1beta1Api deleteNamespacedReplicaSet throw 500 Error

### ISSUE THREAD

**Issue by PGDream** [kubernetes-client/java#161]
at call ExtensionsV1beta1Api.deleteNamespacedReplicaSet throw Internal Server Error , code 500;
curl -X DELETE "http://1xxxx/apis/extensions/v1beta1/namespaces/default/deployments/api-test-nginx" , Deployment can normal deleted.
code: 
       <pre>
        ExtensionsV1beta1Api api = new ExtensionsV1beta1Api();
        V1DeleteOptions options = new V1DeleteOptions();
        options.setApiVersion("extensions/v1beta1");
        options.setKind("Deployment");
        api.deleteNamespacedDeployment("api-test-nginx", "default", options, null, null, null, null);
      </pre>

exception:
      io.kubernetes.client.ApiException: Internal Server Error

	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.ExtensionsV1beta1Api.deleteNamespacedReplicaSetWithHttpInfo(ExtensionsV1beta1Api.java:3129)
	at io.kubernetes.client.apis.ExtensionsV1beta1Api.deleteNamespacedReplicaSet(ExtensionsV1beta1Api.java:3109)
	at TestClient.deleteReplicationSet(TestClient.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)

**Comment by PGDream** [comment]
BUG FIX:
V1DeleteOptions options = new V1DeleteOptions();

delete code:
options.setApiVersion("extensions/v1beta1");
options.setKind("Deployment");

**Comment by brendandburns** [comment]
Still though, that shouldn't throw a 500 in Kubernetes you should get a BadRequest...

I'll try to repro and file a bug on Kubernetes.

**Comment by kondapally1989** [comment]
error is arising because of :
```options.setKind("Deployment");```

correct kind  which works is:
```options.setKind("DeleteOptions");```

**Comment by pycaster** [comment]
I have a similar problem with resource kind: Namespace. I was able to create the Namespace correctly but deleting the same threw me this error,

```
java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 17 column 14 path $.status
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:401)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:389)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at io.kubernetes.client.JSON.deserialize(JSON.java:106)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespaceWithHttpInfo(CoreV1Api.java:11031)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespace(CoreV1Api.java:11012)
```

The namespace is deleted but I still get this exception.

Any idea? My delete options were this,

```
    V1DeleteOptions dp = new V1DeleteOptions()
    dp.setApiVersion(apiVersion)
    dp.setKind("DeleteOptions")
    dp.setGracePeriodSeconds(10)
    dp.orphanDependents(false)
    dp.setPropagationPolicy("true")
    return api.deleteNamespace(name, dp, "true", 10, false, "false")
```

**Comment by pycaster** [comment]
Also why V1DeleteOptions.kind() needs to be "DeleteOptions"? I originally tried this with "Namespace" as that's the resource I created but it gave me same error as the OP. Is there such a kind defined in kubernetes? I can't find it anywhere in the docs.

**Comment by kondapally1989** [comment]
this Error will arise for all delete objects see https://github.com/kubernetes-client/java/issues/86

DeleteOptions
api ref :https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#deleteoptions-v1-meta

**Comment by SataQiu** [comment]
**A method to fix this bug is to modify the code of io.kubernetes.client.models.V1Status**

By default, the type of status field is String,  but it can't parse JSON objects.

If we change it to Object type, it will be able to work properly！


The key code is as follows：

`
package io.kubernetes.client.models;

public class V1Status {
   .......

  @SerializedName("status")
  private Object status = null;

  public Object getStatus() {
    return status;
  }

  public void setStatus(Object status) {
    this.status = status;
  }
   
  ......
}

`
