### ISSUE TITLE
Upgrade request required

### ISSUE THREAD

**Issue by waytoharish** [kubernetes-client/java#1644]
Hi Team i am using the KubernatesClient java client to exec the pod. Using below piece of code as reference  
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-10/src/main/java/io/kubernetes/client/examples/ExecExample.java

but getting below error-

Task :KubernatesClient.main()
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/Users/hshar119/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://e1cloud-v41.aexp.com/api/v1/namespaces/one-data-core-test/pods/backup1-deployment-36-gfkjm/exec?stdin=true&stdout=true&stderr=true&tty=false&container=backup1&command=date
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: authorization: Bearer XGdwPjtkTmfqsbpu2fUdsvXcjvLiQtaqqNH3iCkVJpY=
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: Sec-WebSocket-Protocol: v4.channel.k8s.io
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: User-Agent: Kubernetes Java Client/11.0.1-SNAPSHOT
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: Upgrade: websocket
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: Connection: Upgrade
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: Sec-WebSocket-Key: 4UF1/mRzjxupP3/gFeiZVw==
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: Sec-WebSocket-Version: 13
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: --> END GET
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: <-- 400 Bad Request https://APIHOST/api/v1/namespaces/nameSpaceName/pods/podName/exec?stdin=true&stdout=true&stderr=true&tty=false&container=backup1&command=date (1830ms)
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: Server: nginx/1.9.15
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: Date: Tue, 13 Apr 2021 07:21:18 GMT
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: Content-Length: 139
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: Connection: keep-alive
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: Cache-Control: no-store
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: 
Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}

Apr 13, 2021 12:51:18 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (139-byte body)
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:196)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:167)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

> Task :KubernatesClient.main() FAILED

Execution failed for task ':KubernatesClient.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java'' finished with non-zero exit value 77

**Comment by yue9944882** [comment]
```
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: Upgrade: websocket
Apr 13, 2021 12:51:16 PM okhttp3.internal.platform.Platform log
INFO: Connection: Upgrade
```

@waytoharish are you accessing the kube-apiserver thru a gateway/proxy which drops the header? by the debug log, it clearly sent the upgrade header but oddly it seems that the kube-apiserver is not receiving it..

**Comment by waytoharish** [comment]
@yue9944882 i am calling api server directly . Interestingly i am able to do the same with fabric8io/kubernetes-client

**Comment by brendandburns** [comment]
I think the problem here is this:
```
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
```

Something about your request is malformed. If you print the body of the response you should get more details.

**Comment by waytoharish** [comment]
How to print the body of response ??
