### ISSUE TITLE
Client-java-extended library - java.net.SocketTimeoutException: connect timed out when doing Kubectl.apply

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1652]
**Describe the bug**
I am trying to perform Kubectl.apply from client-java-extended library. I am seeing java.net.SocketTimeoutException: connect timed out error.

I am using kubeconfig token to build Api Client.
```
 public boolean applyManifest(KubeConfigToken kubeConfigToken, String namespace, String kubeManifest) throws K8sHelperException, IOException {
        List<Object> allResources = listResources(kubeManifest);
        ApiClient apiClient = buildApiClient(kubeConfigToken);
        for (Object resource: allResources) {
            try {
                Class clazz = resource.getClass();
                KubectlApply kubectlApply = (KubectlApply) Kubectl.apply(clazz).fieldManager("kubectl")
                        .forceConflict(true).resource((KubernetesObject) resource).namespace(namespace);
                KubectlApply kubectlApplyClient = (KubectlApply) kubectlApply.apiClient(apiClient);
                KubernetesObject appliedObject = kubectlApplyClient.execute();
            } catch (KubectlException e) {
                throw new K8sHelperException("Unable to create apply command for resource", e);
            }
        }
        return true;
    }
              
private ApiClient buildApiClient(KubeConfigToken kubeConfigToken) {
        return new ClientBuilder().setCertificateAuthority(Base64.getDecoder()
                .decode(kubeConfigToken.getKubeConfig().getCertificateAuthorityData()))
                .setVerifyingSsl(true)
                .setBasePath(kubeConfigToken.getKubeConfig().getServer())
                .setAuthentication(new AccessTokenAuthentication(kubeConfigToken.getToken())).build();
    }
public List<Object> listResources(String kubeManifest) throws IOException {
        return Yaml.loadAll(kubeManifest);
    }
```

** Client Version **
client-java-extended 10.0.0

** Kubernetes Version **
v1.18.10

** Java Version **
Java 8

Stack Trace:
Caused by: io.kubernetes.client.openapi.ApiException: java.net.SocketTimeoutException: connect timed out
2021-04-15T22:26:22Z at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:886)
2021-04-15T22:26:22Z at io.kubernetes.client.Discovery.get(Discovery.java:170)
2021-04-15T22:26:22Z at io.kubernetes.client.Discovery.versionDiscovery(Discovery.java:148)
2021-04-15T22:26:22Z at io.kubernetes.client.Discovery.legacyCoreApi(Discovery.java:140)
2021-04-15T22:26:22Z at io.kubernetes.client.Discovery.findAll(Discovery.java:50)
2021-04-15T22:26:22Z at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:236)
2021-04-15T22:26:22Z at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:216)
2021-04-15T22:26:22Z at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.refreshDiscovery(Kubectl.java:221)
2021-04-15T22:26:22Z... 14 common frames omitted 
2021-04-15T22:26:22Z Caused by: java.net.SocketTimeoutException: connect timed out
2021-04-15T22:26:22Z at java.net.PlainSocketImpl.socketConnect(Native Method)
2021-04-15T22:26:22Z at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
2021-04-15T22:26:22Z at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
2021-04-15T22:26:22Z at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
2021-04-15T22:26:22Z at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
2021-04-15T22:26:22Z at java.net.Socket.connect(Socket.java:606)
2021-04-15T22:26:22Z at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
2021-04-15T22:26:22Z at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
2021-04-15T22:26:22Z at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
2021-04-15T22:26:22Z at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
2021-04-15T22:26:22Z at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
2021-04-15T22:26:22Z at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
2021-04-15T22:26:22Z at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
2021-04-15T22:26:22Z at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
2021-04-15T22:26:22Z at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-04-15T22:26:22Z at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2021-04-15T22:26:22Z at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
2021-04-15T22:26:22Z at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-04-15T22:26:22Z at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2021-04-15T22:26:22Z at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2021-04-15T22:26:22Z at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-04-15T22:26:22Z at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
2021-04-15T22:26:22Z at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-04-15T22:26:22Z at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2021-04-15T22:26:22Z at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
2021-04-15T22:26:22Z at okhttp3.RealCall.execute(RealCall.java:81)
2021-04-15T22:26:22Z at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:882)
2021-04-15T22:26:22Z ... 21 common frames omitted

**Comment by yue9944882** [comment]
> java.net.SocketTimeoutException: connect timed out

@saparaj your code looks good overall. but `SocketTimeoutException` usually means the client was not able to access the kubernetes apiserver due to network connectivity issues. is `kubeConfigToken.getKubeConfig().getServer()` a valid connect'able server address?

**Comment by saparaj** [comment]
Oh okay, Let me check that. Will this happen if Kubernetes cluster is private? I am using Oracle Kubernetes Engine.
