### ISSUE TITLE
Kubernetes Java client throwing exception when i try to get replicacount for a deployment

### ISSUE THREAD

**Issue by Gajanana** [kubernetes-client/java#1725]
**Describe the bug**

I am using Java client to get replica count for one of the deployments .This is how i m using . My k8s version is 1.18 and java kubernetes client version is 10.0.0
```

  KubeClient kubeClient = new KubeClient();
      kubeClient.getReplicas();

public class KubeClient {
        public void getReplicas() throws IOException, ApiException {
            ApiClient client = Config.defaultClient();
            Configuration.setDefaultApiClient(client);
            AppsV1Api appsV1Api = new AppsV1Api(client);
            V1Scale v1Scale = appsV1Api.readNamespacedDeploymentScale("mydeployment", "mynamespace", null);
            System.out.println("no of replicas is :  "+v1Scale.getSpec().getReplicas());
        }
    }

```
Getting below exception when I call appsV1Api.readNamespacedDeploymentScale("mydeployment", "mynamespace", null);

```
] |>>   ... 30 more |>>
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 12395
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.2.jar:?]
    at com.google.gson.Gson.fromJson(Gson.java:795) ~[gson-2.2.2.jar:?]
    at com.google.gson.Gson.fromJson(Gson.java:761) ~[gson-2.2.2.jar:?]
    at com.google.gson.Gson.fromJson(Gson.java:710) ~[gson-2.2.2.jar:?]
    at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:137) ~[client-java-api-10.0.0.jar:?]
    at io.kubernetes.client.openapi.ApiClient.deserialize(ApiClient.java:757) ~[client-java-api-10.0.0.jar:?]
    at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:958) ~[client-java-api-10.0.0.jar:?]
    at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883) ~[client-java-api-10.0.0.jar:?]
    at io.kubernetes.client.openapi.apis.AppsV1Api.readNamespacedDeploymentWithHttpInfo(AppsV1Api.java:14456) ~[client-java-api-10.0.0.jar:?]
    at io.kubernetes.client.openapi.apis.AppsV1Api.readNamespacedDeployment(AppsV1Api.java:14426) ~[client-java-api-10.0.0.jar:?]
    at com.airwave.acp.kube.KubeClient.getRelicas(KubeClient.java:19) ~[vrf-engine-4.0.4.jar:?]
    at com.airwave.svg.init.VRFEngine.init(VRFEngine.java:137) [vrf-engine-4.0.4.jar:?]
    at com.airwave.svg.init.VRFEngine.main(VRFEngine.java:92) [vrf-engine-4.0.4.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 12395
    at com.google.gson.stream.JsonReader.expect(JsonReader.java:339) ~[gson-2.2.2.jar:?]
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322) ~[gson-2.2.2.jar:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165) ~[gson-2.2.2.jar:?]
    ... 30 more
```
But getting above exception . not sure what is wrong with my implementation can someone please tell me which version of Kubeclient is compatible with which version oh K8s

** Client Version **
`10.0.0`

** Kubernetes Version **
`1.18.8`

** Java Version **
 Java 8

**To Reproduce**
1. Write simple maven based java project
2. add kubernetes client https://mvnrepository.com/artifact/io.kubernetes/client-java/10.0.0
3. Use above code 

**Expected behavior**
Java client should not crash and should give proper output

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Linux
 - Environment : Docker
 - Cloud: GCP

**Additional context**

**Comment by yue9944882** [comment]
@Gajanana i wasnt able to reproduce this in either (13.x.y client x 1.21 cluster) or (10.x.y client x 1.18 cluster)

can you set ApiClient#setDebugging to true and bring us the concrete response body so that we can find out the crux?

**Comment by brendandburns** [comment]
@Gajanana my guess is that you have some sort of proxy (or your server URL is incorrect) which is returning bad data.

I would print `ApiException.getResponseBody()` which will probably give you additional hints.

**Comment by Gajanana** [comment]
It worked with V 9.0.0 will recheck with 10.0.0 again

**Comment by brendandburns** [comment]
@Gajanana any updates on this issue?

**Comment by Gajanana** [comment]
Its working now Thanks

**Comment by munishchouhan** [comment]
same issue faced in 21.0.0
