### ISSUE TITLE
Exception in thread "main" io.kubernetes.client.openapi.ApiException: 

### ISSUE THREAD

**Issue by kisscyc** [kubernetes-client/java#1753]
**Describe the bug**
I write a test demo to create pod ,the code as follow:

ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new
FileReader(kubeConfigPath))).build();

Configuration.setDefaultApiClient(client);

CoreV1Api api = new CoreV1Api();

 V1Pod body = new V1Pod();

 V1Pod result = api.createNamespacedPod("default", body,null,null,null);

** Kubernetes Version **
 v1.17.2

** Java Version **
openjdk 11.0.2

but it reports as
Exception in thread "main" io.kubernetes.client.openapi.ApiException: 
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:979)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
	at io.kubernetes.client.openapi.apis.CoreV1Api.createNamespacedPodWithHttpInfo(CoreV1Api.java:7900)
	at io.kubernetes.client.openapi.apis.CoreV1Api.createNamespacedPod(CoreV1Api.java:7874)
	at K8sUtil.createPod(K8sUtil.java:96)
	at JavaK8s.main(JavaK8s.java:37)

**Comment by brendandburns** [comment]
You need more details from that exception to debug what is going on.

Try catching the exception and printing `ApiException.getResponseBody()` that should offer more details about the problem.

**Comment by ra-amitkumar** [comment]
@brendandburns I am having similar issues where the exception message is empty but i see messages in the response body. Is there a reason why the exception message attribute is not being set with the relevant message from the response body?

The issue i am facing right now with this is having to update code where **ApiException** is being handled to look into the response body rather than the **message** attribute which is standard for an Exception object.
