### ISSUE TITLE
serializing a V1Pod object to json

### ISSUE THREAD

**Issue by ceeaspb** [kubernetes-client/java#177]
I wanted to take all the data from a V1Pod object (from a watch event) and use it in another system by serializing the data with Jackson.

```
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.cbor.CBORFactory;
import com.fasterxml.jackson.dataformat.cbor.CBORGenerator;
...
ByteArrayOutputStream baos = new ByteArrayOutputStream();
CBORFactory cborFactory = new CBORFactory();
cborFactory.setCodec(new ObjectMapper());
final CBORGenerator generator = cborFactory.createGenerator(baos);
generator.writeObject(response.object);
byte[] bytes = baos.toByteArray();
```

It nearly worked by choked on a ```port``` field.

```
com.fasterxml.jackson.databind.JsonMappingException: Not a string (through reference chain: 
io.kubernetes.client.models.V1Pod["spec"]->
io.kubernetes.client.models.V1PodSpec["containers"]->
java.util.ArrayList[0]->
io.kubernetes.client.models.V1Container["readinessProbe"]->
io.kubernetes.client.models.V1Probe["tcpSocket"]->
io.kubernetes.client.models.V1TCPSocketAction["port"]->
io.kubernetes.client.custom.IntOrString["strValue"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:299)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:342)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:686)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2436)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:355)
	at zzz.K8sClient$4.lambda$0(K8sClient.java:95)
	at java.lang.Iterable.forEach(Iterable.java:75)
...
Caused by: java.lang.IllegalStateException: Not a string
	at io.kubernetes.client.custom.IntOrString.getStrValue(IntOrString.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:633)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	... 26 more

```

The following worked around the issue but would like to have a fix if possible:

```
$ git diff kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
diff --git a/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java b/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
index 6acd23e..3e3c427 100644
--- a/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
+++ b/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java
@@ -32,7 +32,7 @@ public class IntOrString {
 
     public String getStrValue() {
         if (isInt) {
-            throw new IllegalStateException("Not a string");
+               return intValue.toString();
         }
         return strValue;
     }
```

**Comment by lewisheadden** [comment]
I think the fix you proposed will produce an object that isn't compliant (e.g. `{"strValue": "1"}` instead of just `1` or `{"strValue": "90%"}` instead of `"90%"`) with the `V1Pod` schema. This might cause you problems elsewhere.

An option here is to implement the same logic in a Jackson `StdSerializer` and register it with the `ObjectMapper`. Would that work for you? 

I [implemented the custom type adapter](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java#L52-L73) for this in GSON which is used to serialize it in the client and it would just need reproduced in Jackson which can be done by implementing `StdSerializer`.

**Comment by ceeaspb** [comment]
Thanks @lewisheadden I'll use the GSON adapter.

**Comment by ryanpeach** [comment]
Can someone share the code to do this? I would like to print my object as json to the console.
