### ISSUE TITLE
copy.copyFileToPod websocket closed error

### ISSUE THREAD

**Issue by aliyueshuo** [kubernetes-client/java#1785]
**Describe the bug**
**help! when i use the method "copy.copyFileToPod",  the file in guest alway incompleted, and console export as follows。**
java.io.IOException: WebSocket has closed.
	at io.kubernetes.client.util.WebSocketStreamHandler$WebSocketOutputStream.write(WebSocketStreamHandler.java:270)
	at org.apache.commons.codec.binary.BaseNCodecOutputStream.flush(BaseNCodecOutputStream.java:124)
	at org.apache.commons.codec.binary.BaseNCodecOutputStream.write(BaseNCodecOutputStream.java:177)
	at org.apache.commons.compress.utils.CountingOutputStream.write(CountingOutputStream.java:48)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream$BufferAtATimeOutputChannel.write(FixedLengthBlockOutputStream.java:244)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.writeBlock(FixedLengthBlockOutputStream.java:92)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.maybeFlush(FixedLengthBlockOutputStream.java:86)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.write(FixedLengthBlockOutputStream.java:122)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:454)
	at io.kubernetes.client.util.Streams.copy(Streams.java:28)
	at io.kubernetes.client.Copy.copyFileToPodAsync(Copy.java:374)
	at io.kubernetes.client.Copy.copyFileToPod(Copy.java:350)
	at PushFile.pushFileToPod(PushFile.java:34)
	at PushFile.main(PushFile.java:28)
	Suppressed: java.io.IOException: This archive contains unclosed entries.
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:289)
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:307)
		at io.kubernetes.client.Copy.copyFileToPodAsync(Copy.java:378)
		... 3 more

Process finished with exit code 0

**my example code as follows**

    public static void main(String[] args) throws Exception {

        ApiClient client = null;
        File kubeConfigFile = new File(kubeConfig);
        KubeConfig kubeConfig = KubeConfig.loadKubeConfig(new FileReader(kubeConfigFile));
        client = ClientBuilder.kubeconfig(kubeConfig).build();
        client.setWriteTimeout(0);
        client.setReadTimeout(0);
        client.setConnectTimeout(0);
        client.setDebugging(true);
        io.kubernetes.client.openapi.Configuration.setDefaultApiClient(client);

        pushFileToPod("namespace", "podname", "/Gradles.tar.zst", "/home/alibaba/Gradles5.tar.zst");

    }
    public static void pushFileToPod(String namespace, String podName, String filePathInHost, String filePathInGuest) {
        Copy copy = new Copy();
        try {
            copy.copyFileToPod(namespace,
                    podName,
                    "hello-pod",
                    Paths.get(filePathInHost),
                    Paths.get(filePathInGuest));

        } catch (IOException | ApiException e) {
           e.printStackTrace();
        }

    }

** Client Version **
e.g. `11.0.0`

** Kubernetes Version **
e.g. `1.19.3`

** Java Version **
e.g. Java 8

**Comment by brendandburns** [comment]
Is it possible that the `tar` executable isn't present in your Pod? Copy relies on `tar` being present inside the container.

Does `kubectl cp` to that container work correctly?

**Comment by aliyueshuo** [comment]
but kubectl cp is ok

**Comment by brendandburns** [comment]
Do other API calls (e.g. list pods) work correctly when using the Java client library?

Your code looks correct, so I'm not sure what is going wrong.

**Comment by aliyueshuo** [comment]
Except copy api, all api run well. and is it related to my file suffix ".tar.zstd"?

**Comment by brendandburns** [comment]
Ultimately, Copy is just calling `sh -c base64 -d | tar -xmf - -C $parentPath` so you might try running that with `kubectl exec ...` and see if you get a more detailed error.

Code is here:
https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/Copy.java#L420

**Comment by imilos** [comment]
I can confirm that this issue still exists in the newest version 16.0.0 of `client-java`. It breaks each time after 17MB of any file is transmitted to the pod.

**Comment by thecrazzymouse** [comment]
Do you know why is it 17 MB?

**Comment by tg123** [comment]
see #2309
