### ISSUE TITLE
Failing to create namespaceRole: io.kubernetes.client.ApiException: Not Found

### ISSUE THREAD

**Issue by pycaster** [kubernetes-client/java#181]
I was able to successfully use the library to manage namespaces so far but hitting this exception while trying to create role and roleBinding.

Here is a piece of code that's doing this,

```
StringReader reader = new StringReader(this.KubeConfig)
ApiClient apiClient = Config.fromConfig(reader)
Configuration.setDefaultApiClient(apiClient)
```

```
    RbacAuthorizationV1alpha1Api apiInstance = new RbacAuthorizationV1alpha1Api()
    V1alpha1Role body = new V1alpha1Role()

    // set api version
    body.setApiVersion("rbac.authorization.k8s.io/v1beta1")

    // metadata object
    // https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/V1ObjectMeta.md
    V1ObjectMeta metaData = new V1ObjectMeta()
    // set name
    metaData.name("testing-role")

    // set metadata
    body.setMetadata(metaData)

    // prepare rules
    // This rule on role resource is granting all access but only to namespace associated
    // https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/V1alpha1PolicyRule.md
    V1alpha1PolicyRule rule = new V1alpha1PolicyRule()
    rule.addApiGroupsItem("*")
    rule.addResourcesItem("*")
    rule.addVerbsItem("*")
    // Add a rule object
    body.addRulesItem(rule)

    // create
    apiInstance.createNamespacedRole(namespace, body, "true")
```

Here is the exception,

```
io.kubernetes.client.ApiException: Not Found
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.RbacAuthorizationV1alpha1Api.createNamespacedRoleWithHttpInfo(RbacAuthorizationV1alpha1Api.java:434)
	at io.kubernetes.client.apis.RbacAuthorizationV1alpha1Api.createNamespacedRole(RbacAuthorizationV1alpha1Api.java:418)
```

Reference:

https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/RbacAuthorizationV1alpha1Api.md#createNamespacedRole

**Comment by pycaster** [comment]
Never mind. Found the bug in my code. I was using V1alpha1 resource instead V1beta1.
