### ISSUE TITLE
ExecExample hangs after sending 'exit'

### ISSUE THREAD

**Issue by kazakovium** [kubernetes-client/java#1830]
**Describe the bug**
ExecExample application hangs after issuing `exit` command

**Client Version**
`13.0.0`

**Kubernetes Version**
`1.22`

**Java Version**
Java 11.0.12

**To Reproduce**

1. **Comment out line: `System.exit(proc.exitValue());`**
2. Run ExecJava
3. Send `exit` command

**Expected behavior**
Application immediately finished execution with exit code 0

**Actual behavior**
Application hangs for infinite time. If `Ctrl+D` issued after 60+ sec, throws an exception and finishes with status 0
```
echo foo
foo
exit
^D
java.io.IOException: Socket is closed!
	at io.kubernetes.client.util.WebSocketStreamHandler$WebSocketOutputStream.flush(WebSocketStreamHandler.java:221)
	at io.kubernetes.client.util.Streams.copy(Streams.java:30)
	at org.talend.ExecExample$1.run(ExecExample.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)

Process finished with exit code 0
```

**Additional context**
I tried different manipulations with in/out streams, but the best I could get is to have application finished with exit code 0 after exactly 1 minute of waiting.
How can I achieve immediate exit apart from `System.exit()`?

**Comment by brendandburns** [comment]
You need to get the application on the other side of the `exec` to terminate. If it is a shell, sending ctrl-d across is probably the best way to do that. You can send ctrl-d as a ASCII/UTF-8 byte across the stream, and I think it should exit properly w/o waiting one minute.
