### ISSUE TITLE
KubectlApply doesn't work with some Rancher clusters.

### ISSUE THREAD

**Issue by chengaofeng** [kubernetes-client/java#1838]
**Describe the bug**
  I am trying to create an service using Kubectl.apply as per this: https://github.com/kubernetes-client/java/blob/b0c91798c63203f20dc8f2674197e772b2c187ee/docs/kubectl-equivalence-in-java.md#kubectl-apply

  source code:
  ```
  KubectlApply kubectlApply = Kubectl.apply(V1Service.class).fieldManager("kubectl").resource(resource);
  KubectlApply kubectlApplyClient = kubectlApply.apiClient(apiClient);
  kubectlApplyClient.execute();
  ```

  I am getting below error:

  ```
      Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: 404
      at com.google.gson.Gson.fromJson(Gson.java:944)
      at com.google.gson.Gson.fromJson(Gson.java:897)
      at com.google.gson.Gson.fromJson(Gson.java:846)
      at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:169)
      at io.kubernetes.client.util.generic.GenericKubernetesApi.patch(GenericKubernetesApi.java:632)
      at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:89)
      at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:67)
      at chengf.falcon.k8s.learn.ManifestTest.applyManifest(ManifestTest.java:65)
      ... 23 more
      Caused by: java.lang.IllegalStateException: Not a JSON Object: 404
      at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
      at io.kubernetes.client.gson.V1StatusPreProcessor.isLegitKubernetesStatus(V1StatusPreProcessor.java:39)
      at io.kubernetes.client.gson.V1StatusPreProcessor.preDeserialize(V1StatusPreProcessor.java:26)
      at io.gsonfire.gson.HooksTypeAdapter.runPreDeserialize(HooksTypeAdapter.java:79)
      at io.gsonfire.gson.HooksTypeAdapter.read(HooksTypeAdapter.java:53)
      at com.google.gson.Gson.fromJson(Gson.java:932)
      ... 30 more
  ```

**Client Version**
I've tried the following version：

`11.0.0`、`11.0.2`、`13.0.0`

**Kubernetes Version**
`v1.19.0`

**Java Version**
Java 8

**service.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: appstore
  labels:
    app: nginx-test
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-test

```

I tried the same resource with kubectl CLI and I don't see any error:
```
kubectl apply --server-side=true --field-manager=kubectl -f service.yaml
```

**Comment by brendandburns** [comment]
It appears that you are trying to `apply` to an object that doesn't exist.

Though `kubectl` supports this, the current implementation of apply in this library does not.

You should use create for this for now.

We'd be happy to take a PR to add support if you felt like sending one. The code is here:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java

**Comment by dddddai** [comment]
> It appears that you are trying to `apply` to an object that doesn't exist.
> 
> Though `kubectl` supports this, the current implementation of apply in this library does not.
> 
> You should use create for this for now.
> 
> We'd be happy to take a PR to add support if you felt like sending one. The code is here:
> 
> https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java

I'm ok to apply a service that doesn't exist. My kubernetes version is v1.17.2 and here is my code

```java
    V1ServiceSpec spec=new V1ServiceSpec();
    spec.setSelector(Collections.singletonMap("app","foo"));
    V1ServicePort port = new V1ServicePort();
    port.setPort(8440);
    port.setTargetPort(new IntOrString(80));
    port.setName("http");
    port.setProtocol("TCP");
    spec.setPorts(Collections.singletonList(port));

    V1Service service =
        Kubectl.apply(V1Service.class)
            .resource(new V1Service()
                .kind("Service")
                .apiVersion("v1")
                .metadata(new V1ObjectMeta().namespace("dwq").name("foo").labels(Collections.singletonMap("app","foo")))
                .spec(spec))
            .execute();
```


@chengaofeng What does your `resource` object look like ?

**Comment by brendandburns** [comment]
@dddddai thanks for sharing that code works. 

The resource object is in YAML in the original issue. Perhaps the namespace doesn't exist?

**Comment by chengaofeng** [comment]
@dddddai Sorry for the late reply
What client version are you using. As I tried the same code you shared, the error is still there

* Source code
```
{
        ApiClient apiClient = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(Thread.currentThread().getContextClassLoader().getResource("config.yml").getPath()))).build();
        Configuration.setDefaultApiClient(apiClient);
        V1ServiceSpec spec=new V1ServiceSpec();
        spec.setSelector(Collections.singletonMap("app","foo"));
        V1ServicePort port = new V1ServicePort();
        port.setPort(8440);
        port.setTargetPort(new IntOrString(80));
        port.setName("http");
        port.setProtocol("TCP");
        spec.setPorts(Collections.singletonList(port));

        V1Service service =
                Kubectl.apply(V1Service.class)
                        .resource(new V1Service()
                                .kind("Service")
                                .apiVersion("v1")
                                .metadata(new V1ObjectMeta().namespace("dwq").name("foo").labels(Collections.singletonMap("app","foo")))
                                .spec(spec))
                        .execute();
    }
```

* Error message
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: 404

	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:169)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.patch(GenericKubernetesApi.java:632)
	at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:89)
	at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:67)
	at chengf.falcon.k8s.learn.KubectlApplyServiceTest.test2(KubectlApplyServiceTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.IllegalStateException: Not a JSON Object: 404
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at io.kubernetes.client.gson.V1StatusPreProcessor.isLegitKubernetesStatus(V1StatusPreProcessor.java:39)
	at io.kubernetes.client.gson.V1StatusPreProcessor.preDeserialize(V1StatusPreProcessor.java:26)
	at io.gsonfire.gson.HooksTypeAdapter.runPreDeserialize(HooksTypeAdapter.java:79)
	at io.gsonfire.gson.HooksTypeAdapter.read(HooksTypeAdapter.java:53)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 29 more
```

* Client version

```
<dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>13.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-extended</artifactId>
            <version>13.0.0</version>
        </dependency>


        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-api-fluent</artifactId>
            <version>13.0.0</version>
        </dependency>
```

**Comment by chengaofeng** [comment]
@dddddai  ```Kubectl.get``` command works. 

I tried ```Kubectl.apply``` command for ```Deployment```,```DaemonSet```,```ClusterRole```, all works fine. 

```Kubectl.create``` for ```Service``` throws similar error

 ```
io.kubernetes.client.extended.kubectl.exception.KubectlException: io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: null
    code: 404
    details: null
    kind: null
    message: 404 page not found
    
    metadata: null
    reason: null
    status: null
}

	at io.kubernetes.client.extended.kubectl.KubectlCreate.execute(KubectlCreate.java:58)
	at chengf.falcon.k8s.learn.KubectlApplyServiceTest.test2(KubectlApplyServiceTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: null
    code: 404
    details: null
    kind: null
    message: 404 page not found
    
    metadata: null
    reason: null
    status: null
}
	at io.kubernetes.client.util.generic.KubernetesApiResponse.lambda$throwsApiException$0(KubernetesApiResponse.java:64)
	at io.kubernetes.client.util.generic.KubernetesApiResponse.onFailure(KubernetesApiResponse.java:78)
	at io.kubernetes.client.util.generic.KubernetesApiResponse.throwsApiException(KubernetesApiResponse.java:62)
	at io.kubernetes.client.extended.kubectl.KubectlCreate.execute(KubectlCreate.java:55)
	... 23 more

```

**Comment by chengaofeng** [comment]
@dddddai  @brendanburns 
Thanks for the attention.  It's my fault.

My cluster installed by Rancher, This is the key of the problems。

The  Original  k8s API server url is  ```https://k8s_apiserver_ip:6443/api/v1/...```,  while the Rancher k8s API url is```https://rancher_server_ip/k8s/clusters/c-7q988/api/v1/...```.

When I apply a service , After the method```GenericKubernetesApi.tweakCallForCoreV1Group```, the request url change to 
```https://rancher_server_ip/api/c-7q988/apis//v1/namespaces/appstore/services/nginx-test```, which is not a correct service patch url, So the error occurred.

**Comment by brendandburns** [comment]
This feels like a bug in the `tweakCallForCoreV1Group` function. We should make that function do a better job if the path is longer than one `/`
