### ISSUE TITLE
PagerTest.testPaginationForNamespaceListWithSuccessThreadSafely() is flaky

### ISSUE THREAD

**Issue by NeverRaR** [kubernetes-client/java#1843]
```
com.github.tomakehurst.wiremock.client.VerificationException: Expected exactly 20 requests matching the following pattern but received 21:
{
  "urlPath" : "/api/v1/namespaces",
  "method" : "GET",
  "queryParameters" : {
    "limit" : {
      "equalTo" : "1"
    }
  }
}

	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:538)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:521)
	at com.github.tomakehurst.wiremock.client.WireMock.verify(WireMock.java:559)
	at io.kubernetes.client.extended.pager.PagerTest.testPaginationForNamespaceListWithSuccessThreadSafely(PagerTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:79)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:40)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by dddddai** [comment]
I think **this problem might occur when multiple iterators calling `PagerIterator.makeCall()` concurrently**.

In `PagerTest.testPaginationForNamespaceListWithSuccessThreadSafely()`, it creates **multiple iterators on one pager**
https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/extended/src/test/java/io/kubernetes/client/extended/pager/PagerTest.java#L147-L158
Each thread calls `PagerIterator.next()` to get the next object
https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java#L155-L160
Then it calls `PagerIterator.makeCall()` to get more objects
https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java#L133-L147
However, **`listObjectCurrentPage` is shared by multiple iterators**, which modify `listObjectCurrentPage` concurrently. This might break the consistency of `continueToken` in each iterator. 

For example, **iterator1** would make unexpected call because the `continueToken` is returned by `listObjectCurrentPage.getMetadata().getContinue()` where `listObjectCurrentPage` has been modifyed by **iterator2**, which makes **iterator1** get a wrong continueToken.

So I think `listObjectCurrentPage` should not be shared by multiple iterators. Instead, each iterator should have its own `listObjectCurrentPage`.
WDYT @yue9944882 @brendanburns 

BTW, I wonder why `Pager` has to be thread-safe, when do we need to create multiple iterators on one pager?

**Comment by yue9944882** [comment]
@dddddai thank you for digging into this, i just opened https://github.com/kubernetes-client/java/pull/1863 to move the field `listObjectCurrentPage` into the nested class `PagerIterator` to get rid of concurrent modifications.

**Comment by yue9944882** [comment]
> BTW, I wonder why Pager has to be thread-safe, when do we need to create multiple iterators on one pager? (if listObjectCurrentPage is shared)


@dddddai otherwise we will always have to instantiate a new `Pager` in each thread's context. e.g. in a spring application, we may want to define the pager as a singleton in the bean-factory instead of creating on demand.
