### ISSUE TITLE
Flaky: io.kubernetes.client.CopyTest

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#1862]
flakiness found in https://github.com/kubernetes-client/java/pull/1860. based on an initial oberservance, it is possibly caused by improper usage of wiremock servers.

```
Error:  testUrl(io.kubernetes.client.CopyTest)  Time elapsed: 0.088 s  <<< ERROR!
java.lang.IllegalStateException
	at io.kubernetes.client.util.WebSocketStreamHandler.getInputStream(WebSocketStreamHandler.java:158)
	at io.kubernetes.client.Exec$ExecProcess.getInputStream(Exec.java:577)
	at io.kubernetes.client.Exec$ExecProcess.getInputStream(Exec.java:559)
	at io.kubernetes.client.Copy.copyFileFromPod(Copy.java:90)
	at io.kubernetes.client.Copy.copyFileFromPod(Copy.java:76)
	at io.kubernetes.client.CopyTest.testUrl(CopyTest.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:79)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by jayesh-srivastava** [comment]
Hi @yue9944882 . I'm new here and I really want to contribute. Can I take up this issue? Would you please guide me as to how to start working on this issue?

**Comment by brendandburns** [comment]
@jayesh-srivastava basically you need to run that test N times (e.g. 100 times) until it fails and debug why it is failing.

One possible reason is related to using static ports w/ WireMock (https://github.com/kubernetes-client/java/issues/1229) but I haven't looked at this specific test. It's also possible that we're using a static wiremock instead of a local one.
