### ISSUE TITLE
Trying to create a KubernetesClient throws NoSuchFieldError 

### ISSUE THREAD

**Issue by nivsa** [kubernetes-client/java#1883]
**Describe the bug**
Trying to create a KubernetesClient throws NoSuchFieldError.

Dependencies in use according to Gradle classpath:
```
io.kubernetes:client-java-api-fluent:13.0.0=classpath
io.kubernetes:client-java-api:13.0.0=classpath
io.kubernetes:client-java-proto:13.0.0=classpath
io.kubernetes:client-java:13.0.0=classpath
com.squareup.okhttp3:logging-interceptor:4.9.1=classpath
com.squareup.okhttp3:mockwebserver:3.12.6=classpath
com.squareup.okhttp3:okhttp:4.9.1=classpath
com.squareup.okhttp:okhttp:2.7.4=classpath
com.squareup.okio:okio:2.8.0=classpath
```

Stacktrace:
```
Caused by: java.lang.NoSuchFieldError: Companion
        at okhttp3.internal.Util.<clinit>(Util.kt:71)
        at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
        at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
        at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
        at io.kubernetes.client.openapi.ApiClient.initHttpClient(ApiClient.java:91)
        at io.kubernetes.client.openapi.ApiClient.initHttpClient(ApiClient.java:87)
        at io.kubernetes.client.openapi.ApiClient.<init>(ApiClient.java:78)
        at io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:421)
```

** Client Version **
13.0.0

** Kubernetes Version **
1.20

** Java Version **
Java 8

**To Reproduce**
Not sure what created the problem and it doesn't reproduce in all of our projects.

**Server (please complete the following information):**
 - OS: Linux, Mac
 - Cloud: GCP

**Comment by brendandburns** [comment]
This looks like a dependency issue, not an issue with this client.

We use maven for all of our testing, so using gradle with this lib is semi-unsupported.

**Comment by nitinsh99** [comment]
@nivsa Were you able to find out the root cause of the issue? I am seeing the same problem in our project
