### ISSUE TITLE
Java Client throws java.lang.NullPointerException: null at io.kubernetes.client.Discovery.lambda$null$5(Discovery.java:119)

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1886]
Hi @yue9944882 and @brendanburns,

We are seeing this null pointer exception in Model.refresh() call - We are trying to do simple apply manifest 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-test
  labels:
    mytest: sa-test
```

Full Stack Trace
```
java.lang.NullPointerException: null
at io.kubernetes.client.Discovery.lambda$null$5(Discovery.java:119)
at java.util.Optional.ifPresent(Optional.java:159)
at io.kubernetes.client.Discovery.lambda$manageRelationFromResourceToSubResources$6(Discovery.java:117)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
at io.kubernetes.client.Discovery.manageRelationFromResourceToSubResources(Discovery.java:114)
at io.kubernetes.client.Discovery.groupResourcesByName(Discovery.java:97)
at io.kubernetes.client.Discovery.findAll(Discovery.java:72)
at io.kubernetes.client.Discovery.findAll(Discovery.java:65)
at io.kubernetes.client.Discovery.findAll(Discovery.java:55)
at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:239)
at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:219)
```
** Client Version **
12.0.0

** Kubernetes Version **
1.20.8

** Java Version **
Java 8

Please let us know any pointers on how to fix this or what is causing this?

**Comment by brendandburns** [comment]
Something in your discovery APIs (the meta-api that lists the API is unexpected, can you attach the output of curl to `/api` and also to `/apis/<group>` for all of the APIs on your cluster.

We probably should add some defense in depth for a null-pointer in that case too.

**Comment by saparaj** [comment]
@brendanburns Here is the output of curl 
![1- kubectl api-versions](https://user-images.githubusercontent.com/62569721/133737820-ed63a1de-b5a8-41f4-85bb-def5196329f9.png)
![2a-kubectl api-resources](https://user-images.githubusercontent.com/62569721/133737840-dfccc84a-ea78-4674-90cf-7ca8829bb84c.png)
![2b-kubectl api-resources](https://user-images.githubusercontent.com/62569721/133737957-26bd017d-3d12-4fea-ae77-49f5d353cfd3.png)

![3a- APISERVER_api](https://user-images.githubusercontent.com/62569721/133737969-d6a974a8-047a-4949-ad76-275bf43ac812.png)
[3b- APISERVER_apiv1.txt](https://github.com/kubernetes-client/java/files/7183311/3b-.APISERVER_apiv1.txt)

**Comment by saparaj** [comment]
Is it possible to add null pointer defense in discovery class in here: 
https://github.com/kubernetes-client/java/blob/f20788272291c0e79a8c831d8d5a7dd94d96d2de/util/src/main/java/io/kubernetes/client/Discovery.java#L119
something like this:
`((Set)subResources.computeIfAbsent(this.getMajorResourceName(r.getName())), r -> new HashSet<>()).add(subResourceName);`

**Comment by saparaj** [comment]
@brendandburns Now we are seeing API exception in the logs after null pointer defense.
Is there any way to find the root cause of API Exception? I don't see it in stack trace.
Thank you.
```
Caused by: io.kubernetes.client.extended.kubectl.exception.KubectlException: io.kubernetes.client.openapi.ApiException:
at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.refreshDiscovery(Kubectl.java:223)
at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:71)
at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:67)
at com.oracle.pic.dlc.deployment.worker.client.k8s.K8sHelper.applyManifest(K8sHelper.java:85)
... 11 common frames omitted
Caused by: io.kubernetes.client.openapi.ApiException:
at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:974)
at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:886)
at io.kubernetes.client.Discovery.get(Discovery.java:174)
at io.kubernetes.client.Discovery.resourceDiscovery(Discovery.java:156)
at io.kubernetes.client.Discovery.findAll(Discovery.java:71)
at io.kubernetes.client.Discovery.findAll(Discovery.java:65)
at io.kubernetes.client.Discovery.findAll(Discovery.java:55)
at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:259)
at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:239)
at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.refreshDiscovery(Kubectl.java:221)
... 14 common frames omitted

```

**Comment by brendandburns** [comment]
APIException indicates that the server returned a non-200 code. You can print more information from the exception itself.

**Comment by HuboryChen** [comment]
private Map<String, Set<String>> manageRelationFromResourceToSubResources(
      V1APIResourceList resourceList) {
    Map<String, Set<String>> subResources = new HashMap<>();
    resourceList.getResources().stream()
        .forEach(r -> subResources.put(r.getName(), new HashSet<>()));
    resourceList.getResources().stream()
        .forEach(
            r -> {
              getSubResourceNameIfPossible(r.getName())
                  .ifPresent(
                      subResourceName -> {
                        subResources.get(getMajorResourceName(r.getName())).add(subResourceName);
                      });
            });
    return subResources;
  }




subResources.get(getMajorResourceName(r.getName())).add(subResourceName);


This is a bug. When the return value of this line is null, a null pointer exception will be reported
