### ISSUE TITLE
Incorrect exit code in current Exec implementation

### ISSUE THREAD

**Issue by gholliday100** [kubernetes-client/java#1891]
Hi,
I stumbled upon #1346 and I'm experiencing the same issue (issue was closed by bot).

In the previous bug it mentioned that exceptions like "java.net.SocketException: Connection closed by remote host" are expected on connection termination. The thing is, if the actual command completes, eventually its exit code will be overwritten with -1975219.

            public void failure(Throwable ex) {
              super.failure(ex);
              // TODO, it's possible we should suppress this error message, but
              // currently there's
              // no good place to surface the message, and without it, this will be
              // really hard to
              // debug.
              ex.printStackTrace();
              synchronized (ExecProcess.this) {
                // Try for a pretty unique error code, so if someone searches
                // they'll find this
                // code.
                statusCode = -1975219;
                isAlive = false;
                ExecProcess.this.latch.countDown();
              }
            }

If I get this exit code I'm forced to rerun the command, as i'm not sure of the final outcome.

Many thanks,

**Comment by brendandburns** [comment]
I believe this is different than that. If the server closes the connection because the exec finishes, this will terminate correctly. If you are running an exec and the server closes the connection unexpectedly then you will see this exception.

Can you give more specific details about what you are doing and what you are seeing?

**Comment by gholliday100** [comment]
So I am using version of 10.0.1 of the client and performing an Exec as follows:

		Exec exec = new Exec(client);
		boolean tty = System.console() != null;

		final Process proc = exec.exec(namespace, podName, commands.toArray(new String[commands.size()]), true, tty);

		if (in != null) {
			Thread inT =
					new Thread(
						new Runnable() {
						  public void run() {
							try {
							  Streams.copy(in, proc.getOutputStream());
							} catch (Exception ex) {
							  logger.error("Error redirecting InputStream to stdin", ex);
							  ex.printStackTrace();
							}
						  }
						});
				inT.start();
		}
        
        Thread outT =
			new Thread(
			    new Runnable() {
                  public void run() {
                    try {
                      Streams.copy(proc.getInputStream(), out);
                    } catch (Exception ex) {
                      logger.error("Error redirecting stdout", ex);
                      ex.printStackTrace();
                    }
                  }
                });
        outT.start();		
        
        
        Thread errT =
                new Thread(
                    new Runnable() {
                      public void run() {
                        try {
                          Streams.copy(proc.getErrorStream(), err);
                        } catch (Exception ex) {
                          logger.error("Error redirecting stderr", ex);
                          ex.printStackTrace();
                        }
                      }
                    });
        errT.start();   	        

		boolean complete = proc.waitFor(execTimeout, TimeUnit.SECONDS);

		// wait for any last output; no need to wait for input thread
		//inT.join();
		outT.join();
		errT.join();

		proc.destroy();

The majority of the time this works fine, however intermittently i'm seeing an exit
code of -1975219 in the returned Process (used in the client for the failure) 
and the following stacktrace in the logs at the same point:

```
java.net.SocketException: Connection or outbound has been closed
 	at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:267)
 	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1029)
 	at okio.OutputStreamSink.write(JvmOkio.kt:53)
 	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
 	at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
 	at okhttp3.internal.ws.WebSocketWriter.writeControlFrame(WebSocketWriter.kt:142)
 	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.kt:102)
 	at okhttp3.internal.ws.RealWebSocket.writeOneFrame$okhttp(RealWebSocket.kt:533)
 	at okhttp3.internal.ws.RealWebSocket$WriterTask.runOnce(RealWebSocket.kt:620)
 	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 	at java.lang.Thread.run(Thread.java:748)	
```

**Comment by brendandburns** [comment]
Ah, thanks for the details. This is on the close. It looks like the issue is that there is a race between the server closing the connection and us initiating a close on the connection. I think I see how to fix it, I will try to send a PR soon.

We need to differentiate between the "I couldn't write" vs the "I couldn't close" state.

**Comment by gholliday100** [comment]
Super thankyou!

**Comment by IstvanSzilagyi** [comment]
Hello.

Is there any news about this issue ? 
Im facing the same error.
- kubernetes-client: V10.0.0 (tried 11 also)
- java: V8
- Spring-boot: V2.5.2 (probably not relevant in this case)
- Camel: V3.11 (probably not relevant in this case)

The errors im getting is basically:

```
Error on flush
java.io.IOException: Socket is closed!
        at io.kubernetes.client.util.WebSocketStreamHandler$WebSocketOutputStream.flush(WebSocketStreamHandler.java:221)
        at io.kubernetes.client.util.WebSocketStreamHandler.close(WebSocketStreamHandler.java:136)
        at io.kubernetes.client.Exec$ExecProcess$1.close(Exec.java:542)
        at io.kubernetes.client.Exec$ExecProcess$1.handleMessage(Exec.java:508)
        at io.kubernetes.client.util.WebSocketStreamHandler.bytesMessage(WebSocketStreamHandler.java:75)
        at io.kubernetes.client.util.WebSockets$Listener.onMessage(WebSockets.java:142)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:326)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:221)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        
         failed to send warning alert CLOSE_NOTIFY (
"throwable" : {
  java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
        at sun.security.ssl.TransportContext.warning(TransportContext.java:246)
        at sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:637)
        at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:555)
        at okhttp3.internal.Util.closeQuietly(Util.java:154)
        at okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:294)
        at okhttp3.internal.connection.Transmitter.exchangeMessageDone(Transmitter.java:258)
        at okhttp3.internal.connection.Exchange.bodyComplete(Exchange.java:204)
        at okhttp3.internal.connection.RealConnection$1.close(RealConnection.java:558)
        at okhttp3.internal.Util.closeQuietly(Util.java:139)
        at okhttp3.internal.ws.RealWebSocket.onReadClose(RealWebSocket.java:367)
        at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:202)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)}

)
SSLSocket duplex close failed (
"throwable" : {
  java.net.SocketException: Socket is closed
        at java.net.Socket.shutdownInput(Socket.java:1539)
        at sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:218)
        at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:741)
        at sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(SSLSocketImpl.java:691)
        at sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:650)
        at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:555)
        at okhttp3.internal.Util.closeQuietly(Util.java:154)
        at okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.java:294)
        at okhttp3.internal.connection.Transmitter.exchangeMessageDone(Transmitter.java:258)
        at okhttp3.internal.connection.Exchange.bodyComplete(Exchange.java:204)
        at okhttp3.internal.connection.RealConnection$1.close(RealConnection.java:558)
        at okhttp3.internal.Util.closeQuietly(Util.java:139)
        at okhttp3.internal.ws.RealWebSocket.onReadClose(RealWebSocket.java:367)
        at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:202)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)}

)
```
        
The relevant code part im using is:


```
final Process proc =exec.exec(namespace, podName, new String[]{"sh", "-c", "ls -la"}, true, tty);

            Thread in =
                    new Thread(
                            new Runnable() {
                                public void run() {
                                    try {
                                        ByteStreams.copy(System.in, proc.getOutputStream());
                                    } catch (Exception ex) {
                                        ex.printStackTrace();
                                    }
                                }
                            }, "Thread in");
            in.start();

            Thread out =
                    new Thread(
                            new Runnable() {
                                public void run() {
                                    try {
                                        ByteStreams.copy(proc.getInputStream(), System.out);
                                    } catch (Exception ex) {
                                        ex.printStackTrace();
                                    }
                                }
                            }, "Thread out");
            out.start();
            out.join();

            proc.destroy();
            int exitValue = proc.exitValue();
            logger.info("Process exit value was: " + exitValue);
```

**Comment by ltamaster** [comment]
Hi, I got a similar issue, can you reopen this issue?

**Comment by guillaumerose** [comment]
I still face it with 16.0.

/reopen

**Comment by xibz** [comment]
@brendandburns can we get some people to look at this? This is a pretty severe issue, and Im about 2 seconds away from using the Go SDK which handles this properly.

**Comment by yhilmare** [comment]
which version can we upgrade to solve this problem?
