### ISSUE TITLE
Exception when deleting namespaced pod

### ISSUE THREAD

**Issue by pires** [kubernetes-client/java#190]
Running Kubernetes 1.9.1 and a snapshot build of this repo as of https://github.com/kubernetes-client/java/commit/505a812482d0d3a61e47c4188fdab14935ec0f42, I get this when deleting a namespace pod:

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 4559 path $.status
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at io.kubernetes.client.JSON.deserialize(JSON.java:106)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPodWithHttpInfo(CoreV1Api.java:13152)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPod(CoreV1Api.java:13132)
	at pires.kubernetes.scheduler.KubernetesPlanCustomizer.drain(KubernetesPlanCustomizer.java:137)
	at pires.kubernetes.scheduler.KubernetesPlanCustomizer.drainKubeNode(KubernetesPlanCustomizer.java:78)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at pires.kubernetes.scheduler.KubernetesPlanCustomizer.customizeDecommission(KubernetesPlanCustomizer.java:70)
	at pires.kubernetes.scheduler.KubernetesPlanCustomizer.updatePlan(KubernetesPlanCustomizer.java:48)
	at pires.scheduler.AbstractScheduler.start(AbstractScheduler.java:97)
	at pires.scheduler.SchedulerRunner.run(SchedulerRunner.java:118)
	at pires.kubernetes.scheduler.Main.main(Main.java:108)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 4559 path $.status
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:831)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:422)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:410)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	... 17 more
```

**Comment by kondapally1989** [comment]
This is know issue https://github.com/kubernetes-client/java/issues/86#issuecomment-334981383
This  error may arise for all delete K8 objects. 
as said in comment, you may wrap it in try catch.

**Comment by pires** [comment]
Thank you!

**Comment by pires** [comment]
Another option may be:
```java
final Response response = apiClient.deleteNamespacedPodCall(pod.getMetadata().getName(), pod.getMetadata().getNamespace(), new V1DeleteOptions().gracePeriodSeconds(0L).propagationPolicy("Foreground"), null, null, null, null, null, null).execute();

if (!response.isSuccessful()) {
    LOGGER.warn("Couldn't delete pod [{}] with reason: {}", pod.getMetadata().getName(), response.message());
}
```

**Comment by brendandburns** [comment]
Closing as a dup of #86

**Comment by icehehehe** [comment]
> Another option may be:
> 
> ```java
> final Response response = apiClient.deleteNamespacedPodCall(pod.getMetadata().getName(), pod.getMetadata().getNamespace(), new V1DeleteOptions().gracePeriodSeconds(0L).propagationPolicy("Foreground"), null, null, null, null, null, null).execute();
> 
> if (!response.isSuccessful()) {
>     LOGGER.warn("Couldn't delete pod [{}] with reason: {}", pod.getMetadata().getName(), response.message());
> }
> ```

This is very useful.I use the newest java-client with the parameter modified.Thank you! ! !
