### ISSUE TITLE
Empty issuer DN not allowed in X509Certificates

### ISSUE THREAD

**Issue by GithubRyze** [kubernetes-client/java#1926]
**Describe the bug**
Empty issuer DN not allowed in X509Certificates

** Client Version **
 `13.0.0`

** Java Version **
e.g. Java 8

` 
ApiClient client = Config.defaultClient();  
    client.setDebugging(true);  
    client.setVerifyingSsl(false);  
    client.setBasePath("https://techteam-dev-infra-kb.ewell.hk:32222");  
    Configuration.setDefaultApiClient(client);  
    CoreV1Api api = new CoreV1Api(); 
    V1PodList list = api.listPodForAllNamespaces( 
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
    for (V1Pod item : list.getItems()) {    
      System.out.println(item.getMetadata().getName());  
    }`

log:
Exception in thread "main" io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLProtocolException: Empty issuer DN not allowed in X509Certificates
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:889)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:35956)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:35848)
	at com.ewell.hk.K8s.main(K8s.java:30)
Caused by: javax.net.ssl.SSLProtocolException: Empty issuer DN not allowed in X509Certificates
	at sun.security.ssl.HandshakeMessage$CertificateMsg.<init>(HandshakeMessage.java:458)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:221)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
	... 3 more
Caused by: java.security.cert.CertificateParsingException: Empty issuer DN not allowed in X509Certificates
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:651)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at sun.security.ssl.HandshakeMessage$CertificateMsg.<init>(HandshakeMessage.java:455)

**Comment by GithubRyze** [comment]
i am not import any certificate, just  copy example code in my class.  Example  doesn't import certificate.  I think the readme should   tell us how to import the certificate and  what to be prepared before running.

**Comment by brendandburns** [comment]
I don't think the issue is with the kubeconfig

I think the issue is that the certificate coming from your apiserver is formatted in such a way that Java can't load it.

Are you using a self-signed certificate for the kube apiserver?

**Comment by GithubRyze** [comment]
hi @brendandburns, can you tell me how can i get all containers in k8s node?   this url (https://domain/api/v1/node/techteam-dev-1/pod?itemsPerPage=10&page=1&sortBy=d,creationTimestamp)  in k8s  browser dashboard can view all containers in node.
