### ISSUE TITLE
deleteNamespacedPod expects V1Status response, but is actually V1Pod and fails to parse

### ISSUE THREAD

**Issue by electricsam** [kubernetes-client/java#205]
Using:
```
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>1.0.0-beta2</version>
            <scope>compile</scope>
        </dependency>
```

When running deleteNamespacedPod, an exception is thrown when parsing the response.  The API documentation indicates that a Status type should be returned.  However, in reality, the deleted pod JSON is returned.   This appears to be related to https://github.com/kubernetes/kubernetes/issues/59501

Running:
```
try {
            api.deleteNamespacedPod(podName, namespace, new V1DeleteOptions(), null, null, null, null);
} catch (ApiException e) {
      System.out.println(e.getResponseBody());
      throw new RuntimeException("Unable to delete pod", e);
}
```

Results in:
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1526 path $.status
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at io.kubernetes.client.JSON.deserialize(JSON.java:106)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPodWithHttpInfo(CoreV1Api.java:13152)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPod(CoreV1Api.java:13132)
	at com.example.tug.TugAction.delete(TugAction.java:63)
	at com.example.tug.Tug.main(Tug.java:23)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1526 path $.status
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:831)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:422)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:410)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	... 11 more
```

Running:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by electricsam** [comment]
This problem also occurs with BatchV1Api.deleteNamespacedJob.  Status is expected, but a Job is returned in the response.

**Comment by kondapally1989** [comment]
duplicate https://github.com/kubernetes-client/java/issues/86 
 https://github.com/kubernetes-client/java/issues/86#issuecomment-334981383
issue with all delete objects

**Comment by brendandburns** [comment]
Closing as a duplicate. (and yes, this is a general issue with delete and the fact that Swagger/generated code can't handle multi-return...)
