### ISSUE TITLE
Using exec process outputstreams causes stack traces

### ISSUE THREAD

**Issue by Cybermaxke** [kubernetes-client/java#2055]
**Describe the bug**
The following error is thrown after every `Exec` process is closed and if `getOutputStream` is used on the process. The cause of this issue is located at https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java#L114. The state is set here to closed, but afterwards there's a loop over all the output streams to flush and close them. However, in this flush method, there's an if condition that checks that the state is not closed, resulting in the exception.
This is not an issue that breaks the usage of exec, but is spamming the logs with these exceptions.
```
17:13:36,393 [OkHttp https://kubernetes.docker.internal:6443/...] ERROR [io.kubernetes.client.util.WebSocketStreamHandler] [pid=14149] Error on flush
java.io.IOException: Socket is closed!
        at io.kubernetes.client.util.WebSocketStreamHandler$WebSocketOutputStream.flush(WebSocketStreamHandler.java:221) ~[client-java-14.0.0.jar:?]
        at io.kubernetes.client.util.WebSocketStreamHandler.close(WebSocketStreamHandler.java:136) [client-java-14.0.0.jar:?]
        at io.kubernetes.client.Exec$ExecProcess$1.close(Exec.java:542) [client-java-14.0.0.jar:?]
        at io.kubernetes.client.Exec$ExecProcess$1.handleMessage(Exec.java:508) [client-java-14.0.0.jar:?]
        at io.kubernetes.client.util.WebSocketStreamHandler.bytesMessage(WebSocketStreamHandler.java:75) [client-java-14.0.0.jar:?]
        at io.kubernetes.client.util.WebSockets$Listener.onMessage(WebSockets.java:142) [client-java-14.0.0.jar:?]
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:338) [okhttp-4.9.1.jar:?]
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:247) [okhttp-4.9.1.jar:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106) [okhttp-4.9.1.jar:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293) [okhttp-4.9.1.jar:?]
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195) [okhttp-4.9.1.jar:?]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) [okhttp-4.9.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Client Version**
`14.0.0`

**Kubernetes Version**
`1.21.3`

**Java Version**
Java 11

**To Reproduce**
1. Use`Exec` to create a `Process`
2. Write something to the stdin of the process using `getOutputStream`
3. Close/wait for process to finish -> stack trace

**Comment by yue9944882** [comment]
> java.io.IOException: Socket is closed!

thanks for reporting this, i think we can suppress the error logs by filtering these IOExceptions

**Comment by Cybermaxke** [comment]
Occasionally there an additional stack trace that cannot be suppressed through a logger, because it's directly printed:
```
[2022-01-05T11:05:16.602Z] java.net.SocketException: Connection or outbound has been closed
[2022-01-05T11:05:16.602Z] 	at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:267)
[2022-01-05T11:05:16.602Z] 	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1224)
[2022-01-05T11:05:16.602Z] 	at okio.OutputStreamSink.write(JvmOkio.kt:53)
[2022-01-05T11:05:16.602Z] 	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
[2022-01-05T11:05:16.602Z] 	at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
[2022-01-05T11:05:16.602Z] 	at okhttp3.internal.ws.WebSocketWriter.writeControlFrame(WebSocketWriter.kt:142)
[2022-01-05T11:05:16.602Z] 	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.kt:102)
[2022-01-05T11:05:16.602Z] 	at okhttp3.internal.ws.RealWebSocket.writeOneFrame$okhttp(RealWebSocket.kt:533)
[2022-01-05T11:05:16.602Z] 	at okhttp3.internal.ws.RealWebSocket$WriterTask.runOnce(RealWebSocket.kt:620)
[2022-01-05T11:05:16.602Z] 	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
[2022-01-05T11:05:16.602Z] 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
[2022-01-05T11:05:16.602Z] 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
[2022-01-05T11:05:16.602Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-01-05T11:05:16.602Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-01-05T11:05:16.602Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
```
Printed here: https://github.com/kubernetes-client/java/blob/9360c35afa65a4cc79624eaac7dc1d6f540ff235/util/src/main/java/io/kubernetes/client/Exec.java#L521
