### ISSUE TITLE
ExecTest is flaky.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/java#2107]
```
Error:    ExecTest.testUrl:166 No requests exactly matched. Most similar request was:  expected:<
GET
/api/v1/namespaces/default/pods/apod/exec?stdin=true&stdout=true&stderr=true&tty=false&container=container&command=cmd

Query: stdin = false
stdout: true
Query: stderr = false
container: container
tty: false
command: cmd
> but was:<
GET
/api/v1/namespaces/default/pods/apod/exec?stdin=true&stdout=true&stderr=true&tty=false&container=container&command=cmd

stdin: true
stdout: true
stderr: true
container: container
tty: false
command: cmd
>
```

**Comment by brendandburns** [comment]
Error:  Failures: 
Error:    ExecTest.testUrl:231 No requests exactly matched. Most similar request was:  expected:<
GET
/api/v1/namespaces/default/pods/apod/exec?stdin=true&stdout=true&stderr=true&tty=false&container=container&command=cmd

Query: stdin = false
stdout: true
Query: stderr = false
container: container
tty: false
command: cmd
> but was:<
GET
/api/v1/namespaces/default/pods/apod/exec?stdin=true&stdout=true&stderr=true&tty=false&container=container&command=cmd

stdin: true
stdout: true
stderr: true
container: container
tty: false
command: cmd
>
Error:  Tests run: 251, Failures: 1, Errors: 0, S

**Comment by brendandburns** [comment]
This flaked again

Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.151 s <<< FAILURE! -- in io.kubernetes.client.ExecTest
Error:  io.kubernetes.client.ExecTest.testUrl -- Time elapsed: 0.027 s <<< FAILURE!
com.github.tomakehurst.wiremock.client.VerificationException: 
No requests exactly matched. Most similar request was:  expected:<
GET
/api/v1/namespaces/default/pods/apod/exec?stdin=true&stdout=true&stderr=true&tty=false&container=container&command=cmd

Query: stdin = false
stdout: true
Query: stderr = false
container: container
tty: false
command: cmd
> but was:<
GET
/api/v1/namespaces/default/pods/apod/exec?stdin=true&stdout=true&stderr=true&tty=false&container=container&command=cmd

stdin: true
stdout: true
stderr: true
container: container
tty: false
command: cmd
>
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:39)
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:548)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:538)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:517)
	at com.github.tomakehurst.wiremock.WireMockServer.verify(WireMockServer.java:266)
	at io.kubernetes.client.ExecTest.testUrl(ExecTest.java:231)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
