### ISSUE TITLE
PortForward.forward(V1Pod pod, List<Integer> ports) results in 404 errors

### ISSUE THREAD

**Issue by greglanthier** [kubernetes-client/java#214]
I think [io.kubernetes.client.PortForward#79](https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/PortForward.java#L79) has a copy & paste error.

I have sample code that looks something like this:

```java

    ApiClient client = Config.defaultClient();
    client.setDebugging(true).setVerifyingSsl(false);
    Configuration.setDefaultApiClient(client);       

    CoreV1Api api = new CoreV1Api();
    V1PodList list = api.listPodForAllNamespaces(null, null, null, "waca-app=waca-ca-kit-cm,release=waca-perf-test", null, null, null, null, null);
    for (V1Pod item : list.getItems()) {
        ...
        final PortForward.PortForwardResult result = forward.forward(item, ports);
```

When the code executes I see these logs:

```text
-> GET https://169.46.7.238:22285/api/v1/namespaces/waca-perf-test/pods/waca-perf-test/portforward?ports=9300 HTTP/1.1
authorization: Bearer eyJraWQiOiIyMDE3MTAzMC0wMDowMDowMCIsImFsZyI6IlJTMjU2In0.eyJpYW1faWQiOiJJQk1pZC0yNzAwMDFRM1I1IiwiaXNzIjoiaHR0cHM6Ly9pYW0ubmcuYmx1ZW1peC5uZXQva3ViZXJuZXRlcyIsInN1YiI6ImdyZWcubGFudGhpZXJAY2EuaWJtLmNvbSIsImF1ZCI6ImJ4IiwiZXhwIjoxNTIxNTEyNjQ0LCJpYXQiOjE1MjE1MDkwNDR9.NTE2qNk8PMFfc1ySWvgz3X0GZR0pA_v_YJ7T8fEnYz8YJRcudbsGo4QZ4majEyR0rrwTT_J0RrmpSmZbMeNt5d0U5nQkCwj_LRnvheZJHLymGg--XuByQTz0LaYNHgpn38BGnzTDlAHqja2eEBWczJJi_vu9a3_FOCOMRvNNMRxpqNRcsrijQI_ACuZa_ZaxBmCkgDMv0Rfuc-E0E8PNCAPAM0v5gi5859eaRwpozgKTEYZuwUEqkBZz-11xTpdQ1lbI8aEFYqmUSMzXLWUpJQ7eL1WW8IGY_EERVLS4N4x_FQD7vsJ7FKtTWXoJ-gTn-O2ex9u0WOU0XvUptZlPwA
X-Stream-Protocol-Version: v4.channel.k8s.io,v3.channel.k8s.io,v2.channel.k8s.io,channel.k8s.io
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: q7GYG98d+6w3K85wytGkoQ==
Sec-WebSocket-Version: 13
--> END GET
<-- HTTP/1.1 404 Not Found (349ms)
Content-Type: application/json
Date: Tue, 20 Mar 2018 02:15:42 GMT
Content-Length: 196
OkHttp-Sent-Millis: 1521512142786
OkHttp-Received-Millis: 1521512142842
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
        at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.access$100(Call.java:35)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The URL in the request appears to be using the pods namespace twice.

If I modify my PortForward call to look like this

```java
final PortForward.PortForwardResult result = forward.forward(item.getMetadata().getNamespace(), item.getMetadata().getName(), ports);
```

I see the port forward call succeed.

I applied the following diff to [io.kubernetes.client.PortForward#79](https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/PortForward.java#L79) in HEAD and the port-forward call behaves as expected.

```shell
diff --git a/util/src/main/java/io/kubernetes/client/PortForward.java b/util/src/main/java/io/kubernetes/client/PortForward.java
index 81cc47a..ed5f3ad 100644
--- a/util/src/main/java/io/kubernetes/client/PortForward.java
+++ b/util/src/main/java/io/kubernetes/client/PortForward.java
@@ -76,7 +76,7 @@ public class PortForward {
    */
   public PortForwardResult forward(V1Pod pod, List<Integer> ports)
       throws ApiException, IOException {
-    return forward(pod.getMetadata().getNamespace(), pod.getMetadata().getNamespace(), ports);
+    return forward(pod.getMetadata().getNamespace(), pod.getMetadata().getName(), ports);
   }
 
   /**
```

**Comment by greglanthier** [comment]
I'll need to update my CLA from my employer before I can submit a PR - which may take a few days.

**Comment by brendandburns** [comment]
@greglanthier yep, that's clearly a bug.  Thanks for the PR!

Closing this as the PR has merged.
