### ISSUE TITLE
A connection to xxx was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by momomobinx** [kubernetes-client/java#2156]
**Describe the bug**
```
2022-03-02 20:48:06.654  WARN 12572 --- [ ConnectionPool] okhttp3.OkHttpClient                     : A connection to https://192.168.21.134:39691/ was leaked. Did you forget to close a response body?

java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:149) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.connection.Transmitter.callStart(Transmitter.java:116) ~[okhttp-3.14.9.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:78) ~[okhttp-3.14.9.jar:na]
	at io.kubernetes.client.PodLogs.streamNamespacedPodLog(PodLogs.java:96) ~[client-java-14.0.0.jar:na]
	at io.kubernetes.client.PodLogs.streamNamespacedPodLog(PodLogs.java:70) ~[client-java-14.0.0.jar:na]
	at io.kubernetes.client.PodLogs.streamNamespacedPodLog(PodLogs.java:61) ~[client-java-14.0.0.jar:na]

```

**Client Version**
 `14.0.0`

**Kubernetes Version**
 `1.21.1`

**Java Version**
 Java 8

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
We need more details on what you were doing here.

Did you close the `InputStream` that you got back from the streamNamespacedPodLog() call?
