### ISSUE TITLE
Forbidden when calling AppsV1beta1Api#readNamespacedDeploymentStatus

### ISSUE THREAD

**Issue by mkarthiatgithub** [kubernetes-client/java#220]
Hi ,
I could able to 

- create Deployment,
- delete deployment,
- scale up and 
- List all deployments for a given nameSpace

However only during get deployment Status, I get error 

        try {
            AppsV1beta1DeploymentList result = apiInstanceV1beta1.listNamespacedDeployment(namespace, pretty, null, null, null, null, null);
            result.getItems().stream().filter(it -> it.getMetadata().getName().equalsIgnoreCase(name)).forEach(System.out::println);
        } catch (ApiException e) {
            System.err.println("Exception when calling AppsV1beta1Api#listNamespacedDeployment");
            e.printStackTrace();
        }

        try {
            AppsV1beta1Deployment result = apiInstanceV1beta1.readNamespacedDeploymentStatus(name, namespace, pretty);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling AppsV1beta1Api#readNamespacedDeploymentStatus");
            e.printStackTrace();
        } 

**StackTrace** 

Exception when calling AppsV1beta1Api#readNamespacedDeploymentStatus
io.kubernetes.client.ApiException: Forbidden
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.AppsV1beta1Api.readNamespacedDeploymentStatusWithHttpInfo(AppsV1beta1Api.java:2935)
	at io.kubernetes.client.apis.AppsV1beta1Api.readNamespacedDeploymentStatus(AppsV1beta1Api.java:2919)
	

**Response.body()** 

Response{protocol=http/1.1, code=403, message=Forbidden, url=https://121.1.1.1:6443/apis/apps/v1beta1/namespaces/tcs-dev/deployments/karthi-configservice/status?pretty=pretty_example}

`
{
	"kind": "Status",
	"apiVersion": "v1",
	"metadata": {		
	},
	"status": "Failure",
	"message": "deployments.apps \"karthi-configservice\" is forbidden: User \"system:serviceaccount:tcs-dev:adminuser\" cannot get deployments.apps/status in the namespace \"tcs-dev\"",
	"reason": "Forbidden",
	"details": {
		"name": "karthi-configservice",
		"group": "apps",
		"kind": "deployments"
	},
	"code": 403
}

'
I tried with  ExtensionsV1beta1Api apiInstance = new ExtensionsV1beta1Api(); 

Same error 

**Please let me know if I have done any usererror on my side Or you need some more debug info**

**Comment by mkarthiatgithub** [comment]
Also , I tried with all the secrets tokens available in 
https://hostname/#!/secret?namespace=tcs-dev

**Comment by brendandburns** [comment]
It's possible that RBAC is set up to prevent this? I kind of doubt it, but I don't think there is anything special in this path that would make this not work...

Can you try to make the equivalent call using `kubectl` and the same kubeconfig file?

If that works, then there's a problem in this library, if that fails, then the problem is RBAC in your server.

Thanks
