### ISSUE TITLE
unable to connect to kube cluster from inside of the cluster

### ISSUE THREAD

**Issue by cdkgenie** [kubernetes-client/java#2238]
I referred to the examples and tried to connect to kube cluster from a container running inside the cluster 

Please see the example below : 

 ```
ApiClient client = ClientBuilder.cluster().build();
            Configuration.setDefaultApiClient(client);
            System.out.println("Loading in app cluster 4");
            CoreV1Api api = new CoreV1Api();
            V1PodList list =
                    api.listPodForAllNamespaces(null,
                            null,
                            null,
                            null,
                            100,
                            null,
                            null,
                            null,
                            null,
                            null);
            System.out.println("Listing all pods: ");
            for (V1Pod item : list.getItems()) {
                System.out.println(item.getMetadata().getName());
            }
        }catch (Exception e){
            e.printStackTrace();
        }
```

I'm getting forbidden error inside of the cluster.

```
io.kubernetes.client.openapi.ApiException: Forbidden
        at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:993)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:905)
        at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:35956)
        at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:35848)
        at com.cdk.demo.DemoApplication.getCurrentTime(DemoApplication.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
```

How can I fix the issue. Is there any permission that I need to add?

**Comment by johnflavin-fw** [comment]
What service account is the pod configured to use, and does that service account have permissions to list pods in all namespaces?

**Comment by cdkgenie** [comment]
@johnflavin-fw 

Please check my service-account.yaml

`apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service-account
  namespace: default`

role.yaml

`apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: demo-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
`

role-binding.yaml

`apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-role-binding
  namespace: default
roleRef: # points to my Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-role # name of role
subjects: # points to my ServiceAccount
  - kind: ServiceAccount
    name: demo-service-account # service account to bind to
    namespace: default # ns of service account
`
deployment.yaml

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      serviceAccountName: demo-service-account
      containers:
        - name: demoapp
          image: test/demoapp
          # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
              # The port that the container is running on in the cluster


`

I shared all my configurations. How can I fix this issue?

**Comment by johnflavin-fw** [comment]
Note that I'm not an expert. I don't know if this will work.

My guess is that `api.listPodForAllNamespaces` is not allowed because your service account only has permissions to list pods in a single namespace, `default`, but you're asking to list pods in all namespaces. I would try switching to `api.listNamespacedPod`, passing it the namespace `"default"` explicitly.

**Comment by cdkgenie** [comment]
Do you want me to create a cluster role instead of a plain role to list pods from all namespaces?

**Comment by johnflavin-fw** [comment]
That isn't exactly what I was saying. I was only trying to tell you what you would need to change within your code to make it work given the permissions your `ServiceAccount` already has. Your `ServiceAccount` can only list pods within the namespace `"default"`, so if you change your code to do that then the code should work.

However, you've also asked a different question. If you do want to list pods across all namespaces, then yes, you would need to define a `ClusterRole`. That's one of the use cases listed in the [RBAC documentation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrole-example).

> **ClusterRole Example**
> 
> A ClusterRole can be used to grant the same permissions as a Role. Because ClusterRoles are cluster-scoped, you can also use them to grant access to:
> 
> * cluster-scoped resources (like [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/))
> * non-resource endpoints (like /healthz)
> * **namespaced resources (like Pods), across all namespaces**
> 
> For example: you can use a ClusterRole to allow a particular user to run `kubectl get pods --all-namespaces`
>
> _Emphasis mine_

You would also need to use a `ClusterRoleBinding` to bind the `ClusterRole` to your `ServiceAccount`, as the binding has more influence over the scope of the permissions than the role itself does.

**Comment by cdkgenie** [comment]
Thanks @johnflavin-fw . I just created clusterrole and clusterrolebinding it worked as expected

**Comment by brendandburns** [comment]
Closing this as resolved.

Thanks @johnflavin-fw for helping here!!
