### ISSUE TITLE
Unable to read meta-data for class  io.kubernetes.client.spring.extended.manifests.config.KubernetesManifestsAutoConfiguration

### ISSUE THREAD

**Issue by kevin807210561** [kubernetes-client/java#2269]
**Describe the bug**
I follow the [SpringControllerExample](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-15/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java) to add informers in my spring boot(v2.0.4.RELEASE) project, and after I add the following dependencies and codes to my spring boot project 
dependencies
```
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-api</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-extended</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-spring-integration</artifactId>
            <version>15.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java-proto</artifactId>
            <version>15.0.1</version>
        </dependency>
```
codes
```
@Configuration
@Slf4j
public class InformerFactory {
    @Bean
    public CommandLineRunner commandLineRunner(SharedInformerFactory sharedInformerFactory) {
        return args -> {
            log.info("starting informers...");
            sharedInformerFactory.startAllRegisteredInformers();
        };
    }

    @Bean
    public SharedIndexInformer<myclass> myInformer(ApiClient apiClient, SharedInformerFactory sharedInformerFactory) {
        GenericKubernetesApi<myclass, myclass> genericApi = new GenericKubernetesApi<>(
                myclass,
                myclass,
                API_GROUP,
                API_VERSION,
                PLURAL,
                apiClient
        );
        return sharedInformerFactory.sharedIndexInformerFor(genericApi, myclass, 0);
    }

    @Bean
    public SharedIndexInformer<myclass> myInformer(ApiClient apiClient, SharedInformerFactory sharedInformerFactory) {
        GenericKubernetesApi<myclass, myclass> genericApi = new GenericKubernetesApi<>(
                myclass,
                myclass,
                API_GROUP,
                API_VERSION,
                PLURAL,
                apiClient
        );
        return sharedInformerFactory.sharedIndexInformerFor(genericApi, myclass, 0);
    }
}
```
my spring application cannot run
```
2022-05-31 21:34:56.170 [main] ERROR o.s.boot.SpringApplication [RequestId=] 845 - Application run failed
java.lang.IllegalStateException: Unable to read meta-data for class  io.kubernetes.client.spring.extended.manifests.config.KubernetesManifestsAutoConfiguration
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:245)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getOrder(AutoConfigurationSorter.java:214)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.access$000(AutoConfigurationSorter.java:155)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter.lambda$getInPriorityOrder$0(AutoConfigurationSorter.java:62)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1464)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter.getInPriorityOrder(AutoConfigurationSorter.java:61)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.sortAutoConfigurations(AutoConfigurationImportSelector.java:408)
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.selectImports(AutoConfigurationImportSelector.java:394)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:831)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:563)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:271)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:91)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at com.nsf.cicd.WebApplication.main(WebApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.FileNotFoundException: class path resource [ io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsAutoConfiguration.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:51)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:88)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:75)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:241)
	... 34 common frames omitted
```
it seems like the `KubernetesManifestsAutoConfiguration` class in `client-java-spring-integration` package causes the problem because after i remove the `client-java-spring-integration` dependency, the above exceptions dispear. but  the `client-java-spring-integration` dependency is needed for informer factory bean injection.

**Client Version**
`15.0.1`

**Kubernetes Version**
`v1.19.12`

**Java Version**
`Java 8`

**Spring Boot Version**
`v2.0.4.RELEASE`

**Expected behavior**
spring application can run without throwing exceptions

**Server:**
 - OS: [Linux]
 - Environment [container]
 - Cloud [Kubernetes]

**Comment by yue9944882** [comment]
how about adding `kubernetes.manifests.enabled=false` in your spring context? looks like you are not using that in your application.
