### ISSUE TITLE
deleteNamespacedService 

### ISSUE THREAD

**Issue by Ljincheng0128** [kubernetes-client/java#2307]
the code is:
```
        ApiClient client =
                ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader("configaliyun"))).build();

        // set the global default api-client to the in-cluster one from above
        Configuration.setDefaultApiClient(client);

        // the CoreV1Api loads default api-client from global configuration.
        CoreV1Api api = new CoreV1Api();

        try {
            api.deleteNamespacedService("apinetwork-20220710233409-yodgtn","test",null,null,null,null,null,null);
        } catch (ApiException e) {
            e.printStackTrace();

            throw new GuliException(ResultCode.ERROR, ResponseMsg.DELETE_SERVICE_ERROR);
        }
```
but it throws an exception

Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 60 path $.status
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 34 more

Can you tell me how I need to find and fix this problem，thanks

**Comment by Ljincheng0128** [comment]
Thank you for your reply！The version of the kubernetes cluster is v1.20.6, and  the kubernetes-client's version is 16.0.0 .The service has been deleted, but it throws this exception. So I caught this exception and thought it would not affect my subsequent work.

**Comment by Ljincheng0128** [comment]
> What version of the client are you using? This sounds like:
> 
> #86
> 
> But it was fixed a while ago.
> 
> This can also be caused if your server in the kubeconfig is mis-configured so that you are not actually talking to Kubernetes.

Thank you for your reply！The version of the kubernetes cluster is v1.20.6, and the kubernetes-client's version is 16.0.0 .The service has been deleted, but it throws this exception. So I caught this exception and thought it would not affect my subsequent work.
