### ISSUE TITLE
ControllerManager encountered a deadlock fault after calling the shutdown method

### ISSUE THREAD

**Issue by hawkli-1994** [kubernetes-client/java#2508]
**Describe the bug**
In our implementation of the jenkins plugin, after calling the controllerManger.shutdown method, we encountered frequent deadlock failures

**Client Version**
`11.0.0`

**Kubernetes Version**
 `v1.23.13`

**Java Version**
 `Eclipse Temurin openjdk 11`

**To Reproduce**

**Expected behavior**
Expect no deadlock failures

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**
`jenkins version: 2.361.4`
`controller-reflector-io.alauda.devops.java.clusterregistry.client.models.V1alpha1Cluster-1
PRIORITY : 5

THREAD ID : 0X00007FF188002800

NATIVE ID : 0X63

NATIVE ID (DECIMAL) : 99

STATE : BLOCKED

stackTrace:
java.lang.Thread.State: BLOCKED (on object monitor)
at io.kubernetes.client.informer.cache.ReflectorRunnable.closeWatch(ReflectorRunnable.java:163)
- waiting to lock <0x00000007562d1e28> (a io.kubernetes.client.informer.cache.ReflectorRunnable)
at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:145)
at io.kubernetes.client.informer.cache.Controller$$Lambda$414/0x0000000800c64840.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.17/Executors.java:515)
at java.util.concurrent.FutureTask.runAndReset(java.base@11.0.17/FutureTask.java:305)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.17/ScheduledThreadPoolExecutor.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.17/ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.17/ThreadPoolExecutor.java:628)
at java.lang.Thread.run(java.base@11.0.17/Thread.java:829)
Locked ownable synchronizers:
- <0x00000007562da6c8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
- <0x00000007562da8e0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

Thread-18
PRIORITY : 5

THREAD ID : 0X00007FF110023000

NATIVE ID : 0XE3

NATIVE ID (DECIMAL) : 227

STATE : WAITING

stackTrace:
java.lang.Thread.State: WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@11.0.17/Native Method)
- parking to wait for <0x00000007562da6c8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.17/LockSupport.java:194)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.17/AbstractQueuedSynchronizer.java:885)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.17/AbstractQueuedSynchronizer.java:917)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.17/AbstractQueuedSynchronizer.java:1240)
at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.17/ReentrantLock.java:267)
at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@11.0.17/SSLSocketImpl.java:1038)
at okio.Okio$2.read(Okio.java:140)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:489)
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
at okhttp3.internal.Util.skipAll(Util.java:204)
at okhttp3.internal.Util.discard(Util.java:186)
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.close(Http1ExchangeCodec.java:511)
at okio.ForwardingSource.close(ForwardingSource.java:43)
at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.java:313)
at okio.RealBufferedSource.close(RealBufferedSource.java:476)
at okhttp3.internal.Util.closeQuietly(Util.java:139)
at okhttp3.ResponseBody.close(ResponseBody.java:192)
at io.kubernetes.client.util.Watch.close(Watch.java:195)
at io.kubernetes.client.informer.cache.ReflectorRunnable.closeWatch(ReflectorRunnable.java:164)
- locked <0x00000007562d1e28> (a io.kubernetes.client.informer.cache.ReflectorRunnable)
at io.kubernetes.client.informer.cache.ReflectorRunnable.stop(ReflectorRunnable.java:156)
at io.kubernetes.client.informer.cache.Controller.stop(Controller.java:137)
- locked <0x00000007562cacb8> (a io.kubernetes.client.informer.cache.Controller)
at io.kubernetes.client.informer.impl.DefaultSharedIndexInformer.stop(DefaultSharedIndexInformer.java:201)
at io.kubernetes.client.informer.SharedInformerFactory.lambda$stopAllRegisteredInformers$2(SharedInformerFactory.java:310)
at io.kubernetes.client.informer.SharedInformerFactory$$Lambda$767/0x0000000800fb6c40.accept(Unknown Source)
at java.util.HashMap.forEach(java.base@11.0.17/HashMap.java:1337)
at io.kubernetes.client.informer.SharedInformerFactory.stopAllRegisteredInformers(SharedInformerFactory.java:307)
- locked <0x00000007562d1b28> (a io.kubernetes.client.informer.SharedInformerFactory)
at io.kubernetes.client.informer.SharedInformerFactory.stopAllRegisteredInformers(SharedInformerFactory.java:295)
- locked <0x00000007562d1b28> (a io.kubernetes.client.informer.SharedInformerFactory)
at com.alauda.jenkins.plugins.cluster.DefaultClusterRegistry.watch(DefaultClusterRegistry.java:71)
at com.alauda.jenkins.plugins.cluster.DefaultClusterRegistry.onConfigChange(DefaultClusterRegistry.java:60)
at io.alauda.jenkins.devops.support.KubernetesClusterConfiguration.lambda$null$2(KubernetesClusterConfiguration.java:101)
at io.alauda.jenkins.devops.support.KubernetesClusterConfiguration$$Lambda$366/0x0000000800c2e840.run(Unknown Source)
at java.lang.Thread.run(java.base@11.0.17/Thread.java:829)
Locked ownable synchronizers:
- None`

**Comment by hawkli-1994** [comment]
This is the jstack log file [jstack.log](https://github.com/kubernetes-client/java/files/10318301/jstack.log)

**Comment by hawkli-1994** [comment]
Analysis report of fastthread [ft-report-locked.pdf](https://github.com/kubernetes-client/java/files/10318310/ft-report-locked.pdf)

**Comment by brendandburns** [comment]
`11.0.0` is a pretty old version of this SDK. Can you try upgrading to the latest SDK and see if it reproduces?

**Comment by hawkli-1994** [comment]
After I changed the version of jdk11 and adopted openjdk11 from another vendor, the problem disappeared
