### ISSUE TITLE
deleteNamespacedPod throw Throwable e : Expected a string but was BEGIN_OBJECT at line 1 column 1912 path $.status

### ISSUE THREAD

**Issue by tingweiwu** [kubernetes-client/java#252]
i use java-client 1.0.0-beta3  and my Kubernetes cluster verison is v1.9.6

when i  user deleteNamespacedPod interface to delete a pod   i caught a Throwable  e
I debug into and find that occur when deserialize(Response response, Type returnType)

**here is the more infomation Exception**
```java
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1912 path $.status
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at io.kubernetes.client.JSON.deserialize(JSON.java:110)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPodWithHttpInfo(CoreV1Api.java:13152)
	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPod(CoreV1Api.java:13132)
.......
```

**and also i get the Response  body string is:**

```xml
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "singleddb2f112-3e1a-48b4-a52a-d9b306163db0-single-0",
    "namespace": "cv",
    "selfLink": "/api/v1/namespaces/cv/pods/singleddb2f112-3e1a-48b4-a52a-d9b306163db0-single-0",
    "uid": "28d66613-492d-11e8-ba34-02429a858df3",
    "resourceVersion": "1837306",
    "creationTimestamp": "2018-04-26T08:38:14Z",
    "deletionTimestamp": "2018-04-26T08:39:11Z",
    "deletionGracePeriodSeconds": 30,
    "labels": {
      "name": "singleddb2f112-3e1a-48b4-a52a-d9b306163db0-single-0"
    }
  },
  "spec": {
    "volumes": [
      {
        "name": "notebookpath",
        "nfs": {
          "server": "10.31.3.221",
          "path": "/root/nfs/cv/w00377714"
        }
      },
      {
        "name": "default-token-4kpc4",
        "secret": {
          "secretName": "default-token-4kpc4",
          "defaultMode": 420
        }
      }
    ],
    "containers": [
      {
        "name": "singleddb2f112-3e1a-48b4-a52a-d9b306163db0-single-0",
        "image": "tensorflow/tensorflow:latest",
        "command": [
          "/bin/sh",
          "-c"
        ],
        "args": [
          "cd /notebooks/code/mnist  && python mnist_train.py --DATA_DIR=/notebooks/data/mnist --MODEL_SAVE_DIR=/notebooks/model/mnist --LOG_BASIC_DIR=/notebooks/log/mnist/instance01"
        ],
        "ports": [
          {
            "containerPort": 2222,
            "protocol": "TCP"
          }
        ],
        "resources": {
          "limits": {
            "cpu": "1",
            "memory": "1Gi"
          },
          "requests": {
            "cpu": "1",
            "memory": "1Gi"
          }
        },
        "volumeMounts": [
          {
            "name": "notebookpath",
            "mountPath": "/notebooks"
          },
          {
            "name": "default-token-4kpc4",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent"
      }
    ],
    "restartPolicy": "Never",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "host-10-71-0-173",
    "securityContext": {},
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      }
    ]
  },
  "**status**": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-04-26T08:38:14Z"
      },
      {
        "type": "Ready",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-04-26T08:38:15Z"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-04-26T08:38:14Z"
      }
    ],
    "hostIP": "10.71.0.173",
    "podIP": "192.168.14.209",
    "startTime": "2018-04-26T08:38:14Z",
    "containerStatuses": [
      {
        "name": "singleddb2f112-3e1a-48b4-a52a-d9b306163db0-single-0",
        "state": {
          "running": {
            "startedAt": "2018-04-26T08:38:15Z"
          }
        },
        "lastState": {},
        "ready": true,
        "restartCount": 0,
        "image": "tensorflow/tensorflow:latest",
        "imageID": "docker://sha256:b52a7196d31e7a3efc9b78d5ec7326814e011bb242bbb04323ecc78d858cd53b",
        "containerID": "docker://daefa19cf82c86062d7d7736bb22581b514b29b974a87b3b12f2c3bd5463b51f"
      }
    ],
    "qosClass": "Guaranteed"
  }
}

```

and notice V1Status define status as String but k8s respnose body status is a obeject

I notice that java-client 1.0.0-beta3 and Kubernetes 1.9 are
- The Kubernetes cluster has features the java-client library can't use (additional API objects, etc).

is the k8s  DELETE /api/v1/namespaces/{namespace}/pods/{name} respnose body 
changed from 1.8 and 1.9?
and should deleteNamespacedPod interface handle throwable e  when http response code is 200 OK ?

**Comment by kondapally1989** [comment]
This is know issue https://github.com/kubernetes-client/java/issues/86
https://github.com/kubernetes-client/java/issues/86#issuecomment-334981383
This error may arise for all delete K8 objects.

**Comment by kondapally1989** [comment]
this depends on upstream swagger code-gen issue/feature getting fixed.
or some else finds  other way to fix it.

**Comment by tingweiwu** [comment]
@kondapally1989 ok, I close this issue first

**Comment by ybhatnagar** [comment]
Still facing this issue...Any fix or workaround available?

**Comment by krishnakumarakurathi** [comment]
Still facing this issue...Any fix or workaround available?
