### ISSUE TITLE
Kubectl get V1Node not working

### ISSUE THREAD

**Issue by pawank0411** [kubernetes-client/java#2525]
**Describe the bug**
As per the [suggestion](https://github.com/kubernetes-client/java/issues/2521#issuecomment-1382380013) on adding `ModelMapper.addModelMap("","v1","Node","nodes",false,V1Node.class)` I started getting one weired exception
`java.lang.NoSuchMethodError: io.kubernetes.client.openapi.apis.CustomObjectsApi.listClusterCustomObjectCall(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/Boolean;Lio/kubernetes/client/openapi/ApiCallback;)Lokhttp3/Call; at io.kubernetes.client.util.generic.GenericKubernetesApi.lambda$list$2(GenericKubernetesApi.java:341) at
io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:787) at io.kubernetes.client.util.generic.GenericKubernetesApi.list(GenericKubernetesApi.java:337) at io.kubernetes.client.extended.kubectl.KubectlGet.execute(KubectlGet.java:72)...`
This exception is getting called by the `execute` method of 
`Kubectl.get(V1Node.class).execute()`

**Client Version**
`15.0.1`

**Kubernetes Version**
`1.21.12-gke.1700`

**Java Version**
Java 8

**To Reproduce**

**Expected behavior**
I should get the list of Nodes under a cluster

**KubeConfig**
Using `Config.defaultClient()`

**Server:**
 - OS: [Linux]
 - Environment [e.g. container]
 - Cloud [GKE]

**Additional context**
pom.xml and code - [Link](https://github.com/kubernetes-client/java/issues/2521#issuecomment-1382752808)

**Comment by pawank0411** [comment]
@brendandburns how can I make sure there is no mismatch between the extension and the main client ?
