### ISSUE TITLE
Kubectl get crashing on one instance

### ISSUE THREAD

**Issue by kevjumba** [kubernetes-client/java#2537]
**Describe the bug**
Kubectl crashes at RefreshDiscovery.

**Client Version**
`15.0.1`

**Kubernetes Version**
`1.26.1`

**Java Version**
e.g. Java 8

**To Reproduce**

Only happens on one of our deployments with no error message. Everything works on all of my other cluster deployments and the API works fine. But when calling the deployment, we see this stack trace with no error message. Any ideas what is causing this?

```
val client: ApiClient = ClientBuilder.cluster().build()
Configuration.setDefaultApiClient(client)
val deployment: V1Deployment =
          Kubectl.get(V1Deployment::class.java).namespace("namespace").name("name").execute()
```
```
io.kubernetes.client.extended.kubectl.exception.KubectlException: io.kubernetes.client.openapi.ApiException: 
	at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.refreshDiscovery(Kubectl.java:235)
	at io.kubernetes.client.extended.kubectl.KubectlGet$KubectlGetSingle.execute(KubectlGet.java:100)
	at com.tecton.metadataservice.MetadataService.getFeatureServerConfig(MetadataService.kt:2666)
	at com.tecton.metadataservice.MetadataServiceGrpc$MethodHandlers.invoke(MetadataServiceGrpc.java:6037)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at com.tecton.grpc.ExceptionHandlingServerInterceptor$interceptCall$1.onHalfClose(ExceptionHandlingServerInterceptor.kt:30)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at com.tecton.grpc.ExceptionHandlingServerInterceptor$interceptCall$1.onHalfClose(ExceptionHandlingServerInterceptor.kt:30)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at com.tecton.grpc.ExceptionHandlingServerInterceptor$interceptCall$1.onHalfClose(ExceptionHandlingServerInterceptor.kt:30)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$1.onHalfClose(TransmitStatusRuntimeExceptionInterceptor.java:74)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.kubernetes.client.openapi.ApiException: 
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:973)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
	at io.kubernetes.client.Discovery.get(Discovery.java:174)
	at io.kubernetes.client.Discovery.resourceDiscovery(Discovery.java:156)
	at io.kubernetes.client.Discovery.findAll(Discovery.java:71)
	at io.kubernetes.client.Discovery.findAll(Discovery.java:65)
	at io.kubernetes.client.Discovery.findAll(Discovery.java:55)
	at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:260)
	at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:240)
	at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.refreshDiscovery(Kubectl.java:233)
	... 50 more
```

**Expected behavior**
It doesn't crash

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Linux
 - Environment Container
 - Cloud AWS

**Comment by brendandburns** [comment]
Unfortunately, this crash shows an instance where we don't return a good message for ApiException (#2066) if you print the body of the exception (`ApiException.getResponseBody()`) you should get more details. There is a problem happening with your server.

**Comment by kevjumba** [comment]
I tried printing out the responsebody but I'm not getting anything in the output. The responsebody seems empty..

**Comment by kevjumba** [comment]
So I'm catching this as a `KubectlException`. How do I cast this to an `ApiException`. If I change the catch block to an `ApiException` the catch block is getting triggered.

**Comment by yue9944882** [comment]
the ApiException means that your client retrieved an error from the cluster. btw it looks the namespace of your target deployment is "namespace" and the name is "name", this looks specious. can you confirm that?

**Comment by brendandburns** [comment]
You should be able to get the api exception with `KubectlException.getCause()`
