### ISSUE TITLE
java.lang.IllegalStateException: Not a string

### ISSUE THREAD

**Issue by a364176773** [kubernetes-client/java#2593]
**Describe the bug**
My pod doesn't set livenessProbe, why does k8sclient have to read it instead of determining if it's null or not?
```
com.fasterxml.jackson.databind.JsonMappingException: Not a string (through reference chain: io.kubernetes.client.util.Watch$Response["object"]->io.kubernetes.client.openapi.models.V1Pod["spec"]->io.kubernetes.client.openapi.models.V1PodSpec["containers"]->java.util.ArrayList[0]->io.kubernetes.client.openapi.models.V1Container["livenessProbe"]->io.kubernetes.client.openapi.models.V1Probe["httpGet"]->io.kubernetes.client.openapi.models.V1HTTPGetAction["port"]->io.kubernetes.client.custom.IntOrString["strValue"])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356)
at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:763)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4409)
at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3663)
at cn.tongdun.arch.uig.kubernetes.process.PodWatchProcess.lambda$createWatchTask$3(PodWatchProcess.java:387)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Not a string
at io.kubernetes.client.custom.IntOrString.getStrValue(IntOrString.java:47)
at jdk.internal.reflect.GeneratedMethodAccessor390.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
... 30 common frames omitted
```

**Client Version**
e.g. `15.0.1`

**Kubernetes Version**
e.g. `1.23`

**Java Version**
e.g. Java 17

**To Reproduce**

**Expected behavior**

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Environment [e.g. container]
 - Cloud [e.g. Azure]

**Additional context**

**Comment by brendandburns** [comment]
Hrm, it looks to me like you are trying to serialize this object as XML?

I think that the XML serializer expects things to obey the Java Bean protocol, but these objects don't.

Is there a reason why you want to serialize as XML?

**Comment by brendandburns** [comment]
If you do want to serialize this as JSON, use GSON and it should work correctly, assuming that our serializer has been registered:

https://github.com/kubernetes-client/java/blob/0620017f19d530dbcc2b033ba4cd6e73849e85de/kubernetes/src/main/java/io/kubernetes/client/custom/IntOrString.java#L23

**Comment by a364176773** [comment]
Thank you very much, I was serializing for log output

**Comment by theAkito** [comment]
@brendandburns

I am trying to serialise Kubernetes objects returned by this client library via Jackson's `ObjectMapper(YAMLFactory())`. Any way to make this one respect the adapter's purpose?

Otherwise, I haven't found a way to serialise to YAML with `GSON`. I would probably need to serialise it as JSON with `GSON`, then deserialise it with ObjectMapper, then re-serialise it again... 😖

**Comment by theAkito** [comment]
Well, turned out to be even worse than that.

https://stackoverflow.com/questions/69352207/jdk-17-spring-boot-unable-to-make-private-java-time-localdatetime

Gson does not seem to be very compatible in general.

It seems like not even this workaround might work without heavy customisation, just to serialise some Kubernetes object.
