### ISSUE TITLE
401 Unauthorized Error when using SharedInformer 

### ISSUE THREAD

**Issue by georgejdli** [kubernetes-client/java#2614]
**Describe the bug**
401 Unauthorized Error when using SharedInformer while running on my local environment (SpringBoot App running with Maven). This app is intended to run on AKS in a container (and it runs without errors there) but I'm getting this issue when running locally.

**Client Version**
e.g. `17.0.1`

**Kubernetes Version**
e.g. `1.25.5`

**Java Version**
e.g. Java 11

**To Reproduce**
Code Snippet below in a Spring Boot App
```java


@Component
public class MyClass {

  @Autowired 
  private ApiClient k8sClient;

  @Autowired
  private SharedInformerFactory sharedInformerFactory;

  @PostConstruct
  private void postConstruct() throws IOException {
    Configuration.setDefaultApiClient(k8sClient);
    
    addInformer(V1Job.class, V1JobList.class, jobEventHandler, "batch", "v1", "jobs");
    sharedInformerFactory.startAllRegisteredInformers();
  }
  private <ApiType extends KubernetesObject, ApiListType extends KubernetesListObject> SharedIndexInformer<ApiType> addInformer(
			Class<ApiType> apiType, Class<ApiListType> apiListType,
			ResourceEventHandler<ApiType> eventHandler, String apiGroup, String apiVersion,
			String resourcePlural) {

		GenericKubernetesApi<ApiType, ApiListType> api =
				new GenericKubernetesApi<>(apiType, apiListType, apiGroup, apiVersion, resourcePlural);

		logger.info("Adding K8S informer for {} with handler {}", apiType.getSimpleName(),
				eventHandler.getClass().getSimpleName());
		SharedIndexInformer<ApiType> sharedIndexInformer =
				sharedInformerFactory.sharedIndexInformerFor(api, apiType, 0, namespace);

		sharedIndexInformer.addEventHandler(eventHandler);
		return sharedIndexInformer;
	}
}
```

**Expected behavior**
For the informer to start up without immediately producing errors

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.
```
contexts:
- context:
    cluster: mycluster
    namespace: mynamespace
    user: myuser
  name: mycontext

clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://<my_cluster>.privatelink.eastus2.azmk8s.io:443
  name: mycluster

users:
- name: myuser
  user:
    client-certificate-data: <redacted>
    client-key-data: <redacted>
    token: <redacted>

```

**Server (please complete the following information):**
 - OS: Linux
 - Environment [e.g. container]
 - Cloud: Azure

**Additional context**
I get the following runtime error:
```log
ERROR 85070 --- [.models.V1Job-1] i.k.c.informer.cache.ReflectorRunnable   : class io.kubernetes.client.openapi.models.V1Job#Reflector loop failed unexpectedly

io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: v1
    code: 401
    details: null
    kind: Status
    message: Unauthorized
    metadata: class V1ListMeta {
        _continue: null
        remainingItemCount: null
        resourceVersion: null
        selfLink: null
    }
    reason: Unauthorized
    status: Failure
}
        at io.kubernetes.client.util.generic.KubernetesApiResponse.lambda$throwsApiException$0(KubernetesApiResponse.java:64) ~[client-java-17.0.1.jar:na]
        at io.kubernetes.client.util.generic.KubernetesApiResponse.onFailure(KubernetesApiResponse.java:78) ~[client-java-17.0.1.jar:na]
        at io.kubernetes.client.util.generic.KubernetesApiResponse.throwsApiException(KubernetesApiResponse.java:62) ~[client-java-17.0.1.jar:na]
        at io.kubernetes.client.informer.SharedInformerFactory$2.list(SharedInformerFactory.java:269) ~[client-java-17.0.1.jar:na]
        at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:91) ~[client-java-17.0.1.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

Based on the default ApiClient behavior it should be using my kube config stored at $HOME/.kube/config

I have full permissions on the cluster. I'm also using kubelogin to manage access to the AKS cluster if that matters.
```
k auth can-i --list
Warning: the list may be incomplete: webhook authorizer does not support user rule resolution
Resources                                       Non-Resource URLs   Resource Names   Verbs
*.*                                             []                  []               [*]
                                                [*]                 []               [*]
selfsubjectaccessreviews.authorization.k8s.io   []                  []               [create]
selfsubjectrulesreviews.authorization.k8s.io    []                  []               [create]
                                                [/api/*]            []               [get]
                                                [/api]              []               [get]
                                                [/apis/*]           []               [get]
                                                [/apis]             []               [get]
                                                [/healthz]          []               [get]
                                                [/healthz]          []               [get]
                                                [/livez]            []               [get]
                                                [/livez]            []               [get]
                                                [/openapi/*]        []               [get]
                                                [/openapi]          []               [get]
                                                [/readyz]           []               [get]
                                                [/readyz]           []               [get]
                                                [/version/]         []               [get]
                                                [/version/]         []               [get]
                                                [/version]          []               [get]
                                                [/version]          []               [get]
```

I'm not sure what the issue is. Is there a way to enable debug/verbose logging similar to kubectl?

**Comment by brendandburns** [comment]
Where is your Kubeconfig file located? The best way to start debugging would be to print `ApiException.getResponseBody()` which hopefully has more details. My best guess is that something in the way that your setup locally is messing with `HOME` or some other environment variable that the client tries to use to get things setup.

I would also try it without Spring in the mix if possible (e.g. try one of the really simple examples) to make sure that it's not Spring that is causing problems.

**Comment by georgejdli** [comment]
So I guess there was an issue with my kubeconfig for this particular cluster.
I re-ran `az aks get-credentials` and it works now. 

Somehow kubelogin wasn't working properly with this kube context (my other clusters worked with the simple example above) and wasn't printing the following debug statement:
```
14:40:23.522 [main] DEBUG io.kubernetes.client.util.KubeConfig - Obtained a token from kubelogin
```
