### ISSUE TITLE
Unexpected char 0x07 in authorization value

### ISSUE THREAD

**Issue by joshuadwinn** [kubernetes-client/java#2637]
**Describe the bug**
In CoreV1API.class, when issuing a build call, the header parameters populated in the localVarHeaderParams have invalid characters for the okhttp3 checkvalue check. Based on the code, the "Accept" header parameter should be application/json, and the "Content-Type" should also be application/json since the localVarContentTypes length is 0. 
Following the stack trace, the check value is failing for values between 

```
private fun checkValue(value: String, name: String) {
      for (i in value.indices) {
        val c = value[i]
        require(c == '\t' || c in '\u0020'..'\u007e') {
          format("Unexpected char %#04x at %d in %s value", c.toInt(), i, name) +
              (if (isSensitiveHeader(name)) "" else ": $value")
        }
      }
    }
```

**Client Version**
`17.0.0`

**Kubernetes Version**
`1.25`

**Java Version**
Java 8

**To Reproduce**
Call CoreV1API.listNamespacedPod("default", "false", null, null, "status.phase=Pending", "", null, null, null, 60, false)

**Expected behavior**
I would expect the value to be set in the map and proceed to list all the pods in the namespace.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - Cloud [AWS]

**Additional context**
Stack trace: 
```
Unexpected char 0x07 at 71 in authorization value: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Unexpected char 0x07 at 71 in authorization value
	at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
	at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362)
	at okhttp3.Headers$Builder.set(Headers.kt:344)
	at okhttp3.Request$Builder.header(Request.kt:199)
	at io.kubernetes.client.openapi.ApiClient.processHeaderParams(ApiClient.java:1156)
	at io.kubernetes.client.openapi.ApiClient.buildRequest(ApiClient.java:1055)
	at io.kubernetes.client.openapi.ApiClient.buildCall(ApiClient.java:1007)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPodCall(CoreV1Api.java:32673)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPodValidateBeforeCall(CoreV1Api.java:32709)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:32904)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:32807)
```

**Comment by brendandburns** [comment]
I believe that this value is the auth token that is either provided by the `aws` command line (if you are using the `exec` provider) or stored in your kubeconfig file.

You will want to check to see where the token is coming from and validate that the values are correct. `0x07` is a control character in UTF-8, so it really shouldn't be a part of the token.

**Comment by joshuadwinn** [comment]
I checked out configuration with a java junit test, it is passing.  Is there a header limit size with the calls that are allowed?  I'm wondering if it's perhaps getting truncated and that might create the invalid character?

**Comment by joshuadwinn** [comment]
I believe that gave me what I needed, I was able to resolve the issue.  Thanks!
