### ISSUE TITLE
PodLogs API not working as expected

### ISSUE THREAD

**Issue by vibhupratap** [kubernetes-client/java#267]
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:454)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:435)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:571)
	... 41 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 55 more

**Comment by vibhupratap** [comment]
/* This function creates the kubeclient from the Kubeconfig file */
public void setKubeConfig(String filename) {
		try {
			_kubeApiClient = Config.fromConfig(filename);
			//Increasing the TimeOut
			_kubeApiClient.getHttpClient().setReadTimeout(60,TimeUnit.SECONDS);
			Configuration.setDefaultApiClient(_kubeApiClient);
			_api = new CoreV1Api();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			_kubeApiClient = null;
		}
	}

/**
	 * Dump Logs for the POD
	 * @param pod
	 */
	public void dumpLogs(V1Pod pod) {
		PodLogs logs = new PodLogs(this.getApiClient());
		InputStream is;
		System.out.println("*********");
		try {
			is = logs.streamNamespacedPodLog(pod);
			ByteStreams.copy(is, System.out);
		} catch (ApiException | IOException e) {
			e.printStackTrace();
		}
		System.out.println("*********");
	}

**Comment by brendandburns** [comment]
Is it timing out after 60 seconds? or sooner? This code looks like it should work...

**Comment by vibhupratap** [comment]
I will try it again , wasn't working previously.
