### ISSUE TITLE
mapping values are not allowed here

### ISSUE THREAD

**Issue by youngledo** [kubernetes-client/java#2729]
**Describe the bug**
Here yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dzhglfw-test-dzhglfw
  namespace: dzhglfw-test
  uid: 3254f68e-3898-4c57-b21b-6c6d92512b10
  resourceVersion: '110024'
  generation: 1
  creationTimestamp: '2023-07-05T13:33:09Z'
  labels:
    app: dzhglfw
    app.kubernetes.io/managed-by: Helm
    chart: dzhglfw-1.0.0-test.xc-java-op-test
    heritage: Helm
    release: dzhglfw-test
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: dzhglfw-test
    meta.helm.sh/release-namespace: dzhglfw-test

# ...
```
error:

```
mapping values are not allowed here
 in 'reader', line 3, column 9:
    metadata:
            ^


	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:890)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:379)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:271)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:286)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:456)
	at io.kubernetes.client.util.Yaml.loadAs(Yaml.java:106)
```

**Client Version**
e.g. `16.0.0`

**Java Version**
e.g. Java 11

**To Reproduce**
the test code:

```java
    @Test
    void testYaml() {
        String yaml = "apiVersion: apps/v1\n" +
                "kind: Deployment\n" +
                "metadata:\n" +
                "  name: dzhglfw-test-dzhglfw\n" +
                "  namespace: dzhglfw-test\n" +
                "  uid: 3254f68e-3898-4c57-b21b-6c6d92512b10\n" +
                "  resourceVersion: '110024'\n" +
                "  generation: 1\n" +
                "  creationTimestamp: '2023-07-05T13:33:09Z'\n" +
                "  labels:\n" +
                "    app: dzhglfw\n" +
                "    app.kubernetes.io/managed-by: Helm\n" +
                "    chart: dzhglfw-1.0.0-test.xc-java-op-test\n" +
                "    heritage: Helm\n" +
                "    release: dzhglfw-test\n" +
                "  annotations:\n" +
                "    deployment.kubernetes.io/revision: '1'\n" +
                "    meta.helm.sh/release-name: dzhglfw-test\n" +
                "    meta.helm.sh/release-namespace: dzhglfw-test\n";
        System.out.println(yaml);
        V1Deployment v1Deployment = Yaml.loadAs(yaml, V1Deployment.class);
        System.out.println(v1Deployment);
    }
```

Help, thanks.

**Comment by youngledo** [comment]
<img width="747" alt="image" src="https://github.com/kubernetes-client/java/assets/68590897/ef2be78e-9126-49a5-b95f-4d30556430b7">
I know why. It's 'nbsp'.
