### ISSUE TITLE
NullPointer Exception using Kubectl.apply when receiving empty string response body for PATCH request

### ISSUE THREAD

**Issue by PTas24** [kubernetes-client/java#2733]
When a 
```
Kubectl.apply(V1Secret.class)
                    .apiClient(apiClient)
                    .namespace(helmReleaseProperties.getNamespace())
                    .resource(secret)
                    .skipDiscovery()
                    .execute();
```

call was performed by our application, the previous k8s java client library (**17.0.0**)'s KubectlApply implementation just called the PatchUtils.patch method (via the GenericKubernetesApi) and simply returned the ApiClient.execute method's ApiResponse's response body's value.

[KubectlApply.java](
https://github.com/kubernetes-client/java/blob/release-17/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java#L64)
[GenericKubernetesApi.java](https://github.com/kubernetes-client/java/blob/release-17/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L551)
[PatchUtils.java](https://github.com/kubernetes-client/java/blob/release-17/util/src/main/java/io/kubernetes/client/util/PatchUtils.java#L51)
[ApiClient.java](https://github.com/kubernetes-client/java/blob/release-17/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L882)

The new k8s client java library (**18.0.0**)'s KubectlApply implementation is updated and finally the executeCall private method does not just simply returns the response body's value of the ApiResponse, but further process it and extracts a subelement of the response json in GenericKubernetesApi.java line 1317; 
`JsonElement kindElement = element.getAsJsonObject().get("kind");`

[KubectlApply.java](https://github.com/kubernetes-client/java/blob/release-18/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java#L64)
[GenericKubernetesApi.java 1019](https://github.com/kubernetes-client/java/blob/release-18/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L1019)
[GenericKubernetesApi.java 1355](https://github.com/kubernetes-client/java/blob/release-18/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L1355)
[GenericKubernetesApi.java 1360](https://github.com/kubernetes-client/java/blob/release-18/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L1360)
[GenericKubernetesApi.java 1317](https://github.com/kubernetes-client/java/blob/release-18/util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java#L1317)

The problem is that while the previous, 17.0.0 k8s java client implementation allowed the empty string response body value for the PATCH response, the new version fails on it because 18.0.0 k8s java client library wants to extract a further json sub-element (the kind value) which does not necessarily exist. 

Our kubernetes cluster is behind a cluster proxy server and the response does not always comes in time, I suppose. We always receive the response code, but sometimes we got empty string response body back. This is fine for us because we are not processing the response body.
But the 18.0.0 library produces a NullpointerException if the response body is an empty string.
The old, null response for an empty string response body would be very helpful for us. The current changed implementation thus causes a problem.

```
    Jul 17, @ 09:31:21.620	2023-07-17 13:31:21.620  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : User-Agent: Kubernetes Java Client/18.0.0-SNAPSHOT

	Jul 17, @ 09:31:21.620	2023-07-17 13:31:21.620  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : Accept: application/json

	Jul 17, @ 09:31:21.620	2023-07-17 13:31:21.620  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : authorization: Bearer eyJhbGciOi ....

	Jul 17, @ 09:31:21.620	2023-07-17 13:31:21.620  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : --> PATCH https://....cluster.local/.../kubernetes/api/v1/namespaces/.../secrets/...?fieldManager=kubernetes-java-kubectl-apply&force=false

	Jul 17, @ 09:31:21.621	2023-07-17 13:31:21.620  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : 
	Jul 17, @ 09:31:21.620	2023-07-17 13:31:21.620  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : Content-Type: application/json-patch+json

	Jul 17, @ 09:31:21.621	2023-07-17 13:31:21.621  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : {"apiVersion":"v1","data":{"values.yaml":"eyJpbWFnZVB ....
	Jul 17, @ 09:31:21.621	3JRV2twb05NaXpkclV2QS...UiOjc1L
	Jul 17, @ 09:31:21.621	CJzY2FsZVVwU3RhYmlsaXphdGlvblNlY29uZHMiOjMwMCwic2NhbGVVcFBvbGljeVBlcmlvZFNlY29uZHMiOjE4MDAsInNjYWxlVXBQb2xpY3lQZXJjZW50YWdlIjoxMCwic2NhbGVEb3duU3RhYmlsaXphdGlvblNlY29uZHMiOjMwMCwic2NhbGVEb3duUG9saWN5UGVyaW9kU2Vjb25kcyI6MTgwMCwic2NhbGVEb3duUG9saWN5UGVyY2VudGFnZSI6MTB9fQ=="},"kind":"Secret","metadata":{"name":"...","namespace":"..."}}

	Jul 17, @ 09:31:21.621	2023-07-17 13:31:21.621  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : --> END PATCH (-1-byte body)


	Jul 17, @ 09:31:22.285	2023-07-17 13:31:22.285  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : Content-Length: 0

	Jul 17, @ 09:31:22.285	2023-07-17 13:31:22.285  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : Date: Mon, 17 Jul 2023 13:31:22 GMT

	Jul 17, @ 09:31:22.285	2023-07-17 13:31:22.285  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : <-- END HTTP (0-byte body)

	Jul 17, @ 09:31:22.285	2023-07-17 13:31:22.285  INFO 1 --- [app": 10] okhttp3.OkHttpClient                     : <-- 200 OK https://....cluster.local/.../kubernetes/api/v1/namespaces/.../secrets/...?fieldManager=kubernetes-java-kubectl-apply&force=false (663ms)

	Jul 17, @ 09:31:22.385	2023-07-17 13:31:22.384 ERROR 1 --- [  xxx]  : Failed ....


Caused by: java.lang.NullPointerException: null
	at io.kubernetes.client.util.generic.GenericKubernetesApi.getKubernetesApiResponse(GenericKubernetesApi.java:1317)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.getKubernetesApiResponse(GenericKubernetesApi.java:1311)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.executeCall(GenericKubernetesApi.java:1360)
	at io.kubernetes.client.util.generic.GenericKubernetesApi.patch(GenericKubernetesApi.java:1031)
	at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:93)
	at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:66)
```

**Client Version**
`18.0.0`

**Kubernetes Version**
`1.25` and `1.26`

**Java Version**
Java 11

**To Reproduce**
Make a PATCH request that responds with 200 OK and with an empty body.

**Expected behavior**
I would like to get back the old behavior, which was the null result in case of empty response body.

**KubeConfig**

**Server (please complete the following information):**
 - OS: [Linux]
 - Environment [container]
 - Cloud [Azure and AWS]

**Comment by brendandburns** [comment]
Hrm, I believe that the k8s server should always return a body, so it feels a little weird to change the kubectl to match the behavior of your proxy. It feels like a better solution is for you to catch the `NullPointerException` in your code. Does that cause a problem?

**Comment by PTas24** [comment]
I admit that this is a weird case but so far the 
```
Kubectl.apply(V1Secret.class)
                    .apiClient(apiClient)
                    .namespace(helmReleaseProperties.getNamespace())
                    .resource(secret)
                    .skipDiscovery()
                    .execute();
```
was permissive in that case.
We try to investigate and fix the proxy server's implementation in parallel.
Could the `executeCall` method throw a checked ApiException when the content of `element` is null in that statement?

`JsonElement kindElement = element.getAsJsonObject().get("kind");`

Still, catching a checked exception would look better in our code than a null pointer

**Comment by brendandburns** [comment]
I'm ok with adding code to throw a checked exception with a message like "Unexpected body" or something like that. Please send a PR with that fix.
