### ISSUE TITLE
Unprocessable Entity when trying to create a pod with a probe

### ISSUE THREAD

**Issue by fiftoine** [kubernetes-client/java#274]
Hi,

I want to create a pod with a livelinessProbe and/or a readinessProbe but I receive this exception : 

```
io.kubernetes.client.ApiException: Unprocessable Entity
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPodWithHttpInfo(CoreV1Api.java:8223)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPod(CoreV1Api.java:8207)
```

If I remove the definition of the probes, the creation works well.

Here is the code I use to create the pod with the probes : 

```
                CoreV1Api api = new CoreV1Api();

		V1Pod pod = new V1Pod();
		pod.setApiVersion("v1");
		pod.setKind("Pod");

		V1ObjectMeta metadata = new V1ObjectMeta();
		metadata.setName("test-pod");
		metadata.setLabels(new HashMap<>());
		metadata.getLabels().put("app", "someapp");
		pod.setMetadata(metadata);

		V1PodSpec spec = new V1PodSpec();
		spec.setContainers(new ArrayList<>());
		V1Container container = new V1Container();
		container.setName("test-pod-wordpress");
		container.setImage("wordpress:4-php7.0");
		V1ContainerPort port = new V1ContainerPort();
		port.containerPort(8080);
		container.setPorts(Arrays.asList(port));

		V1Probe readinessProbe = new V1Probe();
		V1HTTPGetAction readinessHttpGet = new V1HTTPGetAction();
		readinessHttpGet.setPath("/alive");
		readinessHttpGet.setPort(new IntOrString("8080"));
		readinessProbe.setHttpGet(readinessHttpGet);
		container.setReadinessProbe(readinessProbe);

		spec.getContainers().add(container);
		pod.setSpec(spec);
		try {
			api.createNamespacedPod("default", pod, "true");
		} catch (ApiException e) {
			e.printStackTrace();
		}
```

Thanks in advance for your help.

**Comment by brendandburns** [comment]
Unprocessable entity indicates there is some sort of semantic error in your object. Can you dump the `ApiException.getResponseBody()` and see what it says? There should be a better error message in there.

--brendan

**Comment by ZhuXiaomin** [comment]
I got the same exception and status code 422 while creating a deployment.
As @brendandburns mentioned, I checked the response body and found that :  
```
"field":"spec.strategy.rollingUpdate.maxUnavailable"},{"reason":"FieldValueInvalid","message":"Invalid value: intstr.IntOrString{Type:1, IntVal:0, StrVal:\"1\"}: a valid percent string must be a numeric string followed by an ending '%' (e.g. '1%',  or '93%', regex used for validation is '[0-9]+%')"
```

**Comment by kondapally1989** [comment]
@fiftoine  
if you are still getting the error, its because of this line

```java
readinessHttpGet.setPort(new IntOrString("8080"));
```
but should be 
```java
readinessHttpGet.setPort(new IntOrString(8080));
```
@ZhuXiaomin  i think you are also setting string.
i believe string is used to specify percentage of pods 
```java
rollingUpdate.setMaxUnavailable(new IntOrString(1)); //1 means that there will be at most 1 pod unavailable during the update process
rollingUpdate.setMaxUnavailable(new IntOrString("10%")); // personally never tried though
```
you can read further about this on 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#rollingupdatedeployment-v1beta1-apps

**Comment by fiftoine** [comment]
@kondapally1989 
Thanks this is the cause of the 422. Using int or converting String to int did the trick.
