### ISSUE TITLE
13.0.0 sharedIndexInformerFor “java.lang.IllegalStateException: Already Executed”

### ISSUE THREAD

**Issue by lixiaopengqyl** [kubernetes-client/java#2772]
**Describe the bug**
**_code is ：_**

    private void initInformer() {
        this.factory = new SharedInformerFactory(apiClient, Executors.newSingleThreadExecutor());
        CallGenerator params = (ignored) -> {
            BatchV1Api api = new BatchV1Api(apiClient);
            return api.listNamespacedJobAsync("Test",null,null,null,null,null,null,null,null,null,true,null);
        };

        SharedIndexInformer<V1Job> informer = this.factory.sharedIndexInformerFor(params, V1Job.class, V1JobList.class, 600000L);
        this.indexer = informer.getIndexer();
        this.indexer.addIndexers(new HashMap<String, Function<V1Job, List<String>>>() {{
            put("namespace/name", job -> Collections.singletonList(job.getMetadata().getNamespace() + "/" + job.getMetadata().getName()));
        }});
        this.factory.startAllRegisteredInformers();
    }

**_apiclient is initialized outside of initInformer.  An error is reported when starting the server.Is this a bug？_**

2023-08-23 18:53:44,522  INFO [controller-reflector-io.kubernetes.client.openapi.models.V1Job-1] io.kubernetes.client.informer.cache.ReflectorRunnable.run:83: class io.kubernetes.client.openapi.models.V1Job#Start listing and watching...
2023-08-23 18:53:44,561 ERROR [controller-reflector-io.kubernetes.client.openapi.models.V1Job-1] io.kubernetes.client.informer.cache.ReflectorRunnable.defaultWatchErrorHandler:273: class io.kubernetes.client.openapi.models.V1Job#Reflector loop failed unexpectedly
java.lang.IllegalStateException: Already Executed
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
        at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:207)
        at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:87)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Client Version**

e.g. `13.0.0`

**Kubernetes Version**
e.g. `1.21.1`

**Java Version**
e.g. Java 8

**Additional context**

**Comment by lixiaopengqyl** [comment]
please help me,thanks.

**Comment by lixiaopengqyl** [comment]
please help me , thanks

**Comment by lixiaopengqyl** [comment]
**_I tried version=13.0.2 with the same error._**

2023-08-23 19:45:24,046  INFO [controller-reflector-io.kubernetes.client.openapi.models.V1Job-1] io.kubernetes.client.informer.cache.ReflectorRunnable.run:84: class io.kubernetes.client.openapi.models.V1Job#Start listing and watching...
2023-08-23 19:45:24,050 ERROR [controller-reflector-io.kubernetes.client.openapi.models.V1Job-1] io.kubernetes.client.informer.cache.ReflectorRunnable.defaultWatchErrorHandler:286: class io.kubernetes.client.openapi.models.V1Job#Reflector loop failed unexpectedly
java.lang.IllegalStateException: Already Executed
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
        at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:207)
        at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:88)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by brendandburns** [comment]
13.0.0 is a pretty old client library.

I believe that the issue is that the function that you are using to return a `Call` for the watch is returning the same instance of the `Call` multiple times.

You need to return a new instance of the Call every time the function is invoked.

**Comment by lixiaopengqyl** [comment]
Thank you Brendan Burns for your response。I tried version 17.0.2 and it exist the same problem. So I modify the code like this：

    private void initInformer() {
        this.factory = new SharedInformerFactory(apiClient, Executors.newSingleThreadExecutor());
        GenericKubernetesApi<V1Job, V1JobList> jobApi =
                new GenericKubernetesApi<>(V1Job.class, V1JobList.class, "batch", "v1", "jobs",apiClient);
        SharedIndexInformer<V1Job> informer =  this.factory.sharedIndexInformerFor(jobApi,V1Job.class,60000,"Test");
        this.indexer = informer.getIndexer();
        this.indexer.addIndexers(new HashMap<String, Function<V1Job, List<String>>>() {{
            put("namespace/name", job -> Collections.singletonList(job.getMetadata().getNamespace() + "/" + job.getMetadata().getName()));
        }});
        this.factory.startAllRegisteredInformers();
        LOG.info("{} informer start..." , this.cluster);
    }

**_I  use the api like : GenericKubernetesApi.  The code run successfully!_**   Previously used api like ：CallGenerator。 my code is : 

private void initInformer() {
    this.factory = new SharedInformerFactory(apiClient, Executors.newSingleThreadExecutor());
    CallGenerator params = (ignored) -> {
        BatchV1Api api = new BatchV1Api(apiClient);
        return api.listNamespacedJobAsync("Test",null,null,null,null,null,null,null,null,null,true,null);
    };

    SharedIndexInformer<V1Job> informer = this.factory.sharedIndexInformerFor(params, V1Job.class, V1JobList.class, 600000L);
    this.indexer = informer.getIndexer();
    this.indexer.addIndexers(new HashMap<String, Function<V1Job, List<String>>>() {{
        put("namespace/name", job -> Collections.singletonList(job.getMetadata().getNamespace() + "/" + job.getMetadata().getName()));
    }});
    this.factory.startAllRegisteredInformers();
}

I think my code is : a new instance of the Call every time the function is invoked. The same way you think. So  What's the problem？ thanks.

**Comment by yue9944882** [comment]
https://github.com/kubernetes-client/java/blob/4740c85f62ce17a81b50cd5ca2506986bac8bb16/examples/examples-release-18/src/main/java/io/kubernetes/client/examples/InformerExample.java#L53-L67

the callGenerator's input parameter shouldn't be ignored, following the example above should make the informer work ^^
