### ISSUE TITLE
InterruptedException during graceful shutdown with Kubernetes Java Client

### ISSUE THREAD

**Issue by junger-dev** [kubernetes-client/java#2778]
### Issue Description:

During the graceful shutdown process of my Spring Boot application in a Kubernetes environment, I noticed that the Kubernetes Client's informer and related threads are getting interrupted. Here's a snippet of the logs during the shutdown process:

```
2023-08-30 19:01:07.515 [SpringApplicationShutdownHook] INFO o.s.b.w.e.t.GracefulShutdown:shutDownGracefully:53 - Commencing graceful shutdown. Waiting for active requests to complete
2023-08-30 19:01:07.521 [tomcat-shutdown] INFO o.s.b.w.e.t.GracefulShutdown:doShutdown:78 - Graceful shutdown complete
2023-08-30 19:01:07.539 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO i.k.c.i.c.ReflectorRunnable:run:162 - class io.kubernetes.client.openapi.models.V1ConfigMap#Read timeout retry list and watch
2023-08-30 19:01:07.542 [informer-controller-V1ConfigMap] ERROR i.k.c.i.c.Controller:processLoop:164 - DefaultController#processLoop get interrupted null
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1638)
	at io.kubernetes.client.informer.cache.DeltaFIFO.pop(DeltaFIFO.java:318)
	at io.kubernetes.client.informer.cache.Controller.processLoop(Controller.java:162)
	at io.kubernetes.client.informer.cache.Controller.run(Controller.java:130)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 19:01:07.542 [pool-11-thread-1] ERROR i.k.c.i.c.ProcessorListener:run:96 - processor interrupted: {}
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1638)
	at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at io.kubernetes.client.informer.cache.ProcessorListener.run(ProcessorListener.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-30 19:01:09.860 [SpringApplicationShutdownHook] INFO o.s.o.j.LocalContainerEntityManagerFactoryBean:destroy:651 - Closing JPA EntityManagerFactory for persistence unit 'default'
```

### Environment:

- Kubernetes Java Client Version: 13.0.2
- Spring Boot Version: 2.7.8
  - implementation ("org.springframework.cloud:spring-cloud-starter-kubernetes-client-config:2.1.3") 
- Java Version: 17
- Kubernetes Version: client : 1.17.0, server : 1.15.10
- Deployment Environment: Kubernetes 

```yaml
# configmap.yaml

apiVersion: v1
data:
  application.properties: |
    my-api.use-db=false
kind: ConfigMap
metadata:
  name: my-api-config
  namespace: my-namespace
..
```

```yaml
# bootstrap.yaml

spring:
  cloud:
    kubernetes:
      enabled: true
      config:
        sources:
        - name: my-api-config
        use-name-as-prefix: false
        enabled: true
        namespace: my-namespace
        name: my-api-config
      reload:
        enabled: true
```

### Expected Behavior:
The Kubernetes Client's threads (like the informer) should not be interrupted during a graceful shutdown, or should be able to handle interruptions more gracefully.

### Actual Behavior:
The threads are getting interrupted and are throwing InterruptedException.

### Question:

Is there a recommended way to cleanup Kubernetes Client resources during a pod's preStop hook or any other mechanism to avoid such interruptions?

Any insights or recommendations on how to handle this situation would be greatly appreciated.

**Comment by brendandburns** [comment]
Is this causing a problem? The situation is that the informer is waiting for an event. When you chose to shutdown, that wait needs to be broken, or the shutdown will hang until another event comes.

I suppose we could deliver a "watch stopping" event or something like that on shutdown, but this really shouldn't cause any problems (other than printing the exception into the logs) if you are shutting down your application anyway.

**Comment by brendandburns** [comment]
cc @yue9944882 for thoughts.

**Comment by junger-dev** [comment]
@brendandburns Thank you for the swift response.

> Is this causing a problem?

: There are no issues with the application. 

I understand that the informer waits for an event and needs to be interrupted to ensure the application doesn't hang during shutdown. My primary concern arises from the exception being logged, even if the application seems to shut down properly. In an environment where monitoring and alerting tools are sensitive to such exceptions, this can trigger false alarms — and it currently does.

Is there an existing configuration or workaround to address this behavior in the current version? If not, would excluding this error log from our monitoring alert tool be the best approach?

Thank you again.

**Comment by brendandburns** [comment]
The SharedIndexInformerFactory class allows you to pass in a custom exception handler:

https://github.com/kubernetes-client/java/blob/a14d0f30cc85ef2ed8cccff7eab7a183ee8190e3/util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java#L140

Which will control what happens when an exception is thrown (or at least it should)

It's possible that not all of the right plumbing is in the right places to make this happen from Spring. 

Please take a look at that code and see if it works for you. If not, can you add more details here about what is needed?

Thanks!

**Comment by brendandburns** [comment]
Given that interrupting the wait as you suggest is complicated to implement and we have a custom exception handler to suppress the log, I don't think this is a high priority to fix. However, if you want to send a PR implementing the approach that you suggest we would be happy to review that PR.

Thanks!
