### ISSUE TITLE
Watch example from readme throws `java.net.SocketTimeoutException: Read timed out`

### ISSUE THREAD

**Issue by vromero** [kubernetes-client/java#287]
The very same example of the `README.md` for watch:

```java
import com.google.gson.reflect.TypeToken;
import io.kubernetes.client.ApiClient;
import io.kubernetes.client.ApiException;
import io.kubernetes.client.Configuration;
import io.kubernetes.client.apis.CoreV1Api;
import io.kubernetes.client.models.V1Namespace;
import io.kubernetes.client.util.Config;
import io.kubernetes.client.util.Watch;

import java.io.IOException;

public class WatchExample {
    public static void main(String[] args) throws IOException, ApiException{
        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);

        CoreV1Api api = new CoreV1Api();

        Watch<V1Namespace> watch = Watch.createWatch(
                client,
                api.listNamespaceCall(null, null, null, null, null, 5, null, null, Boolean.TRUE, null, null),
                new TypeToken<Watch.Response<V1Namespace>>(){}.getType());

        for (Watch.Response<V1Namespace> item : watch) {
            System.out.printf("%s : %s%n", item.type, item.object.getMetadata().getName());
        }
    }
}
```

Will return the namespaces to then get the following exception:

```java
ADDED : default
ADDED : hola
ADDED : kube-public
ADDED : kube-system
ADDED : about-test
ADDED : about
Exception in thread "main" java.lang.RuntimeException: IO Exception during hasNext method.
	at io.kubernetes.client.util.Watch.hasNext(Watch.java:130)
	at Main.main(Main.java:46)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:454)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:435)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at io.kubernetes.client.util.Watch.hasNext(Watch.java:128)
	... 1 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 8 more

Process finished with exit code 1
```

I guess it is related with my GKE 1.9 cluster but I don't have a 1.8 handy right now. I figured I'd report it as a compatibility issue:

```console
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by kondapally1989** [comment]
@vromero 
you can increase timeout 
```java
client.getHttpClient().setReadTimeout(60, TimeUnit.SECONDS);
```
it is there in example 
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

**Comment by vromero** [comment]
Thanks @kondapally1989 but it doesn't make a big different, it will just show the namespaces as before, wait for whatever the time for timeout is, and then throw exception as before.

I don't believe it is a connectivity problem given that I can see the initial list of namespaces.

**Comment by brendandburns** [comment]
You can set it to zero to have no timeout.
https://square.github.io/okhttp/2.x/okhttp/index.html?com/squareup/okhttp/OkHttpClient.html

But I wouldn't do that. I'd expect Watch calls to drop (the network is an unreliable place) and wrap the Watch in a loop that retries.
