### ISSUE TITLE
Can't read `yaml` config properly using `Config.fromConfig`

### ISSUE THREAD

**Issue by maifeeulasad** [kubernetes-client/java#3004]
**Describe the bug**
Can't read a `k8s.config.yaml` properly.

**Client Version**
e.g. `v1.27.2`

**Kubernetes Version**
e.g. `v1.23.17`

**Java Version**
e.g. `OpenJDK21`

**To Reproduce**
```java
private ApiClient readConfigFromFile(String filePath) throws IOException {
        String yamlContent = new String(Files.readAllBytes(Paths.get(filePath)));
        return Config.fromConfig(yamlContent);
}
```

I'm using this code, I have tried reading my config, but it fails. I have put a debug point there, and it loads the `.yaml` correctly as a string. But it throws exception on `Config.fromConfig`

**Expected behavior**
It should have loaded the config properly.

**KubeConfig**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxx
    server: https://api.mydomain.com.bd:port
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-super
  name: kubernetes-super@kubernetes
current-context: kubernetes-super@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-super
  user:
    client-certificate-data: xxxxx
    client-key-data: xxxxx
```

**Server (please complete the following information):**
 - OS: Windows 11

**Additional context**

Complete log:
```
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at io.kubernetes.client.util.Config.fromConfig(Config.java:80)
	at com.mua.testservice.k8s.K8sService.readConfigFromFile(K8sService.java:39)
	at com.mua.testservice.k8s.K8sService.readPods(K8sService.java:47)
	at com.mua.testservice.k8s.K8sService$$FastClassBySpringCGLIB$$f7a2349d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.mua.testservice.k8s.K8sService$$EnhancerBySpringCGLIB$$305cd403.readPods(<generated>)
	at com.mua.testCliRun.run(CliRun.java:25)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at com.mua.testK8sExpApplication.main(K8sExpApplication.java:10)
```

**Comment by brendandburns** [comment]
`fromConfig(String)` takes a file path to the YAML file, not the contents of the YAML file. If you want to pass the contents, use `fromConfig(Reader)`

**Comment by maifeeulasad** [comment]
@brendandburns thanks.

Exactly this was the issue. Now my problem has been solved.
