### ISSUE TITLE
Bad Request exception on CoreV1Api.replaceNode

### ISSUE THREAD

**Issue by aboudzakaria** [kubernetes-client/java#306]
I'm trying to cordon a node (mark node as Unschedulable) the following way:

```
        V1Node node = listNode.getItems().get(1);
        node.getSpec().setUnschedulable(Boolean.TRUE);
        coreapi.replaceNode(node.getMetadata().getName(), node, null);
```

however it throws an exception:
```
Exception in thread "main" io.kubernetes.client.ApiException: Bad Request
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPodEvictionWithHttpInfo(CoreV1Api.java:8526)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedPodEviction(CoreV1Api.java:8509)
```

**Comment by CathySha** [comment]
@aboudzakaria 
How did you solve this problem?
Thank you.

**Comment by aboudzakaria** [comment]
@CathySha 
in my case, when the node is already cordoned it gives conflict exception but otherwise it works well.
I just had to do this check:
`if (!node.getSpec().isUnschedulable())`
