### ISSUE TITLE
SocketTimeoutException while trying to port-forward and access Postgresql db  which is present in kubernetes

### ISSUE THREAD

**Issue by ChitraSelvaprabhu** [kubernetes-client/java#307]
In my project, the requirement is to access Postgresql database which is running in k8s.

Postgresql database is running inside the k8s cluster. I need to access this database and execute some queries from my java application.
SocketTimeoutException while trying to port-forward and access Postgresql db  which is present in kubernetes.

Look at PortForward sample provided under k8s api but unable to resolve the issue. Could any one you please help me here?

Exception in thread "main" io.kubernetes.client.ApiException: java.net.SocketTimeoutException: timeout
        at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:655)
        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
        at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:16967)
        at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:16948)
        at io.kubernetes.client.examples.Example.main(Example.java:50)
Caused by: java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:207)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:439)
        at okio.Buffer.writeAll(Buffer.java:956)
        at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
        at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
        at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
        at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:651)
        ... 5 more

**Comment by brendandburns** [comment]
It appears to be unable to talk to your cluster. Does 'kubectl get pods' work?

**Comment by brendandburns** [comment]
Closing this due to no response, please re-open if you have more questions.

**Comment by mhmd97** [comment]
Hi! I've got the same issue while trying to run the "InClusterClientExample" and kubectl get pods works for me

**Comment by yue9944882** [comment]
@mhmd97 are you running the example inside a pod in running cluster?

**Comment by mhmd97** [comment]
@yue9944882 Yes!

**Comment by yue9944882** [comment]
/reopen

@mhmd97 enable the debugging logging by `ApiClient#setDebugging` and get back w/ some more inputs?
