### ISSUE TITLE
Watch.close throws IllegalStateException exception

### ISSUE THREAD

**Issue by Hendrik-H** [kubernetes-client/java#318]
Hi,

I'm trying to cleanly close all resources when my program is supposed to exit. So I tried to invoke `Watch.close()`. I guess it kinda closed the watch but it did so by throwing an `IllegalStateException` like this:
```
java.lang.IllegalStateException: Unbalanced enter/exit
	at okio.AsyncTimeout.enter(AsyncTimeout.java:62)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:451)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:435)
	at com.squareup.okhttp.internal.Util.skipAll(Util.java:159)
	at com.squareup.okhttp.internal.Util.discard(Util.java:141)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.close(Http1xStream.java:472)
	at okio.RealBufferedSource.close(RealBufferedSource.java:396)
	at com.squareup.okhttp.ResponseBody.close(ResponseBody.java:92)
	at io.kubernetes.client.util.Watch.close(Watch.java:155)
```

I'm using version `2.0.0`.

**Comment by Hendrik-H** [comment]
Actually the `close` call does not stop the watch. My watch still blocks until the read timeout is reached. So far I have not found a way to stop the watch. Not even interrupting the thread that uses the watch has an effect.

**Comment by Hendrik-H** [comment]
I noticed that a quite old version of the OkHttp library is being used and thus checked if they might have a fix in later versions. There are a few issues around similar issues, like these:
  https://github.com/square/okhttp/issues/4110
  https://github.com/square/okhttp/issues/3632
  https://github.com/square/okhttp/issues/1902

The problem seems to be that `close` does not work correctly and that one should call `cancel` on the `Call` object. So I tried that and it worked just fine.

So a solution could be to pass `call` into the `Watch` constructor here: https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Watch.java#L108
Then you would just need to invoke `call.cancel` in the `close` method instead of trying to close the response body.

**Comment by brendandburns** [comment]
Thanks for digging into this, I filed PR #322 to try to close this.
