### ISSUE TITLE
Caused by: java.io.IOException: Unknown apiVersionKind: extensions/v1beta1/DaemonSet known kinds are: {}

### ISSUE THREAD

**Issue by alexchansun** [kubernetes-client/java#346]
Caused by: java.io.IOException: Unknown apiVersionKind: extensions/v1beta1/DaemonSet known kinds are: {}
  at io.kubernetes.client.util.Yaml.modelMapper(Yaml.java:318)
  at io.kubernetes.client.util.Yaml.loadAll(Yaml.java:255)
  at io.kubernetes.client.util.Yaml.loadAll(Yaml.java:221)

client-java-2.0.0.jar

**Comment by brendandburns** [comment]
I think that you may not have this PR:

https://github.com/kubernetes-client/java/pull/314

Please try upgrading to the 3.0.0-betaX library.

Thanks
