### ISSUE TITLE
CKR_SESSION_READ_ONLY in FIPS enabled environment

### ISSUE THREAD

**Issue by florin-szilagyi** [kubernetes-client/java#3621]
**Describe the bug**
Unable to connect to kubernetes in a fips enabled environment.
Seems very similar to this: https://github.com/fabric8io/kubernetes-client/pull/3867

So I dug around a bit and it seems ApiClient is using the default keystore, instead of initializing it from the system one (as the fix was made [here](https://github.com/fabric8io/kubernetes-client/pull/3867/files#diff-635ccbb5e5e90f719f378bbd7aa12a4c22d6af1c232879fa112bb30f1b6fc4c8R89)

**Client Version**
20.0.0

**Kubernetes Version**
1.28

**Java Version**
Java 17

**To Reproduce**
`io.kubernetes.client.util.Config.fromCluster().getBasePath();`

**Expected behavior**

**Server (please complete the following information):**
 - OS: RHEL
 - Container
 - Azure

**Additional context**
```
sun.security.pkcs11.wrapper.PKCS11Exception: CKR_SESSION_READ_ONLY
	at sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(PKCS11.java)
	at sun.security.pkcs11.wrapper.PKCS11.C_CreateObject(PKCS11.java:1961)
	at sun.security.pkcs11.P11KeyStore.storeCert(P11KeyStore.java:1567)
	at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1045)
	... 99 common frames omitted
Wrapped by: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_SESSION_READ_ONLY
	at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1049)
	at sun.security.pkcs11.P11KeyStore.engineSetCertificateEntry(P11KeyStore.java:515)
	at java.security.KeyStore.setCertificateEntry(KeyStore.java:1235)
	at io.kubernetes.client.openapi.ApiClient.applySslSettings(ApiClient.java:1336)
```

**Comment by brendandburns** [comment]
The current client does not use the FIPS compliant version of bouncy castle, this was fixed recently:

https://github.com/kubernetes-client/java/pull/3595

But is not in any release. If you can rebuild this client at HEAD you can see if that fixes things for you.

**Comment by DeanTupper** [comment]
is there any chance this going to be released any time soon? I don't see any releases for August or September. Is the suggestion here to fork and release our own artifacts for the time being?
