### ISSUE TITLE
When building a controller with `DefaultControllerBuilder` and overriding the queue with `withWorkQueue`, there will be a thread leakage issue.

### ISSUE THREAD

**Issue by yuzp1996** [kubernetes-client/java#3738]
**Describe the bug**
When I utilize `DefaultControllerBuilder` to construct my controller and override the queue by creating a new one using `withWorkQueue`, the default queue will not be shut down even after I shut down the controller.

**Client Version**
`11.0.1`

**Kubernetes Version**
`1.21`

**Java Version**
Java 11

**To Reproduce**
1. Create a controller with `DefaultControllerBuilder` and override the queue with a newly created queue using `withWorkQueue`.
2. Shut down the controller and restart it multiple times.
3. Check the threads and you will find there are many `timed_waiting` threads.

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/36c33df1-38a9-421c-b2db-ca98dcdecc04">

```
stackTrace:
java.lang.Thread.State: TIMED_WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@11.0.18/Native Method)
- parking to wait for <0x000000056bd50a58> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.18/LockSupport.java:234)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.18/AbstractQueuedSynchronizer.java:2123)
at java.util.concurrent.LinkedBlockingQueue.poll(java.base@11.0.18/LinkedBlockingQueue.java:458)
at io.kubernetes.client.extended.workqueue.DefaultDelayingQueue.waitingLoop(DefaultDelayingQueue.java:93)
at io.kubernetes.client.extended.workqueue.DefaultDelayingQueue$$Lambda$347/0x0000000800a1bc40.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.18/Executors.java:515)
at java.util.concurrent.FutureTask.run(java.base@11.0.18/FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/ThreadPoolExecutor.java:628)
at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)

```

**Expected behavior**
When the controller is shut down, the queue should also be shut down.

**Comment by yuzp1996** [comment]
https://github.com/kubernetes-client/java/pull/3737

**Comment by yuzp1996** [comment]
@brendandburns @yue9944882, Should we think about backporting this fix to the previous release?
