### ISSUE TITLE
PodLogs method streamNamespacedPodLog access private method of CoreV1Api

### ISSUE THREAD

**Issue by mtinel** [kubernetes-client/java#3791]
**Describe the bug**
The io.kubernetes.client.PodLogs.streamNamespacedPodLog method call the private method io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedPodLogCall. As a result, the method throw an java.lang.IllegalAccessError

```
java.lang.IllegalAccessError: class io.kubernetes.client.PodLogs tried to access private method 'okhttp3.Call io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedPodLogCall(java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Integer, java.lang.String, java.lang.Boolean, java.lang.Integer, java.lang.Integer, java.lang.Boolean, io.kubernetes.client.openapi.ApiCallback)' (io.kubernetes.client.PodLogs and io.kubernetes.client.openapi.apis.CoreV1Api are in unnamed module of loader 'app')
	at io.kubernetes.client.PodLogs.streamNamespacedPodLog(PodLogs.java:83)
	at io.kubernetes.client.PodLogs.streamNamespacedPodLog(PodLogs.java:70)
	...
```

**Client Version**
`22.0.0`

**Kubernetes Version**
`1.30.4`

**Java Version**
Java 17

**To Reproduce**
V1Pod pod = ...
Call the method PodLog.streamNamespacedPodLog(pod.getMetadata().getNamespace(), pod.getMetadata().getName(), containerName)

**Expected behavior**
The method io.kubernetes.client.PodLogs.streamNamespacedPodLog should not throw java.lang.IllegalAccessError.

**KubeConfig**
Unrelated

**Server (please complete the following information):**
 - OS: Linux
 - Environment : Kind 0.24.0

**Additional context**
Nothing

**Comment by mtinel** [comment]
Hum, it seems it is a problem with my environment. Despite reloading maven project several times, my IDE continue to use the `-legacy` lib instead of the new one.
