### ISSUE TITLE
MalformedJsonException exception when executing listNamespacedPod call with watch parameter set to true

### ISSUE THREAD

**Issue by jinlxz** [kubernetes-client/java#392]
Hi,

It threw a MalformedJsonException exception when executing listNamespacedPod call with watch parameter set to true, the following is my code:
```
//first I deleted the POD with the label and invoke the call.
defaultTimeout=this.client.getHttpClient().getReadTimeout();
this.client.getHttpClient().setReadTimeout(probleTimeout+1000, TimeUnit.MILLISECONDS);
pods=coreV1.listNamespacedPod(namespace, "no_pretty", null, null, true, label, null, resourceVersion, probleTimeout/1000, true);
```
exception stacks:
```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:864)
	at com.google.gson.Gson.fromJson(Gson.java:854)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at io.kubernetes.client.JSON.deserialize(JSON.java:110)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:16718)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:16695)
	at com.nuance.qa.helpers.KubeActions.checkReadinessStatus(KubeActions.java:289)
	at com.nuance.qa.helpers.KubeActions.main(KubeActions.java:334)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:860)
	... 10 more
```
I debugged and  found the responses at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668) contained 2 JSON object, one was the MODIFIED item, the other was the ADD item which ended with a string **....**, the whole message was malformed.
```
{"type":"MODIFIED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"xxxxrc-hsh-3f4266418168742160d1561d3579a558-b5x6p","generateName":"xxxxrc-hsh-3f4266418168742160d1561d3579a558-","namespace":"ntg6-xianzhouall-xxx","selfLink":"/api/v1/namespaces/ntg6-xianzhouall-xxx/pods/xxxxrc-hsh-3f4266418168742160d1561d3579a558-b5x6p","uid":"0dec37c6-d057-11e8-941b-000d3a059e10","resourceVersion":"95152842","creationTimestamp":"2018-10-15T08:48:14Z","deletionTimestamp":"2018-10-15T09:05:51Z","deletionGracePeriodSeconds":30,"labels":{"app":"xxxx","app_group_id":"xxxxrc","name":"xxxx","parent_manifest_name_with_hash":"xxxxrc-hsh-3f4266418168742160d1561d3579a558"},"annotations":{"kubernetes.io/psp":"privileged","sspni-info-scheduling-explanation":"App_Group-Spreadout: try (strong preference weight=100) NOT to pick nodes where a pod of the same app_group_id (xxxxrc) already exists and is running ..... AND try (weak preference weight=10 x 3 to not interfere with the strong preference for spreadout above) NOT to pick a node in either [AzureCloudUpdateDomain OR K8sFailureZone OR K8sFailureRegion] where the same app_group_id (xxxxrc) is already running if possible ..... AND try (even weaker preference weight=5) to pick nodes where nothing is running."},"ownerReferences":[{"apiVersion":"v1","kind":"ReplicationController","name":"xxxxrc-hsh-3f4266418168742160d1561d3579a558","uid":"22020a08-caa4-11e8-8cb5-000d3a059ec6","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"log-directory","hostPath":{"path":"/var/opt/xxx/logs","type":""}},{"name":"xxxsa-token-k2sn7","secret":{"secretName":"xxxsa-token-k2sn7","defaultMode":420}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"ntg6-xianzhouall-xxx.node_pool":"generic"},"serviceAccountName":"xxxsa","serviceAccount":"xxxsa","nodeName":"kn-gg","securityContext":{},"imagePullSecrets":[{"name":"docker-registry-secret"}],"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}]},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2018-10-15T08:48:14Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2018-10-15T08:48:52Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2018-10-15T08:48:14Z"}],"hostIP":"10.33.61.53","podIP":"10.244.80.151","startTime":"2018-10-15T08:48:14Z","containerStatuses":[{"name":"xxxx","state":{"running":{"startedAt":"2018-10-15T08:48:17Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"xxx-service:7.2.000.119326","imageID":"ha256:d74a609b1faed99defd7753899a49a8849c13b80b608aabc47c9ea75d0dfa5a4","containerID":"docker://65fe9d3d922bde3ab6219e130b304d5dc00169506e8e6151efb50e32254a0b7b"}],"qosClass":"Burstable"}}}
{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"xxxxrc-hsh-3f4266418168742160d1561d3579a558-78cvr","generateName":"xxxxrc-hsh-3f4266418168742160d1561d3579a558-","namespace":"ntg6-xianzhouall-xxx","selfLink":"/api/v1/namespaces/ntg6-xianzhouall-xxx/pods/xxxxrc-hsh-3f4266418168742160d1561d3579a558-78cvr","uid":"7195e42c-d059-11e8-941b-000d3a059e10","resourceVersion":"95152845","creationTimestamp":"2018-10-15T09:05:21Z","labels":{"app":"xxxx","app_group_id":"xxxxrc","name":"xxxx","parent_manifest_name_with_hash":"xxxxrc-hsh-3f4266418168742160d1561d3579a558"},"annotations":{"kubernetes.io/psp":"privileged","sspni-info-scheduling-explanation":"App_Group-Spreadout: try (strong preference weight=100) NOT to pick nodes where a pod of the same app_group_id (xxxxrc) already exists and is running ..... AND try (weak preference weight=10 x 3 to not interfere with the strong preference for spreadout above) NOT to pick a node in either [AzureCloudUpdateDomain OR K8sFailureZone OR K8sFailureRegion] where the same app_group_id (xxxxrc) is already running if possible ..... AND try (even weaker preference weight=5) to pick nodes where nothing is running."},"ownerReferences":[{"apiVersion":"v1","kind":"ReplicationController","name":"xxxxrc-hsh-3f4266418168742160d1561d3579a558","uid":"22020a08-caa4-11e8-8cb5-000d3a059ec6","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"log-directory","hostPath":{"path":"/var/opt/nuance/kubernetes/volumes/ntg6-xianzhouall-xxx/xxx/logs","type":""}},{"name":"xxxsa-token-k2sn7","secret":{"secretName":"xxxsa-token-k2sn7","defaultMode":420}}],"containers":[{"name":"xxxx","image":"registry-pri-eastus2.dev.nuancemobility.net:5000/build-ncs/xxx-service:7.2.000.119326","ports":[{"containerPort":17911,"protocol":"TCP"}],"env":[{"name":"POD_ID","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"GRAPHITE_ENABLED","value":"true"},{"name":"GRAPHITE_HOST","value":"10.0.3.5"},{"name":"GRAPHITE_PORT","value":"2003"},{"name":"GRAPHITE_PREFIX","value":"ncs.k8s_cluster.azeastus2dev-ntg6.ntg6-xianzhouall-xxx.xxx.xxxx.${HOSTNAME}"},{"name":"GRAPHITE_INTERVAL","value":"10000"},{"name":"HTTP_ALARMS_ENABLED","value":"true"},{"name":"HTTP_ALARMS_HOST","value":"10.0.5.5"},{"name":"HTTP_ALARMS_PORT","value":"5003"},{"name":"HTTP_ALARMS_PATH","value":"/"},{"name":"STDOUT_ALARMS_ENABLED","value":"true"},{"name":"LEGACY_WATCHER_ALARMS_ENABLED","value":"false"},{"name":"ALARMS_METADATA_KV","value":"{\\\"k8s_namespace\\\":\\\"ntg6-xianzhouall-xxx\\\", \\\"k8s_api_server\\\":\\\"xxxxx\\\", \\\"hostname\\\":\\\"${POD_I...
```

I think it might be a bug, it should return a valid JSON string.

I am using kubernetes cluster set up by kubeadm, version is v1.10.5 and kubernetes-client version is 2.0.0

**Comment by brendandburns** [comment]
When you activate `watch` it doesn't return a single JSON object (as you have discovered) it returns multiple JSON objects.

If you want to use watch, you need to use the `Watch` class as is shown in this example:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java

**Comment by jinlxz** [comment]
Thank you, it works.
