### ISSUE TITLE
io.kubernetes.client.ApiException: Internal Server Error

### ISSUE THREAD

**Issue by li1191863273** [kubernetes-client/java#428]
when I create a CRD, occur this error 

	io.kubernetes.client.ApiException: Internal Server Error
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CustomObjectsApi.createNamespacedCustomObjectWithHttpInfo(CustomObjectsApi.java:349)
	at io.kubernetes.client.apis.CustomObjectsApi.createNamespacedCustomObject(CustomObjectsApi.java:330)
	at com.shuwen.service.mesh.demo.proto.ProtoTest.test(ProtoTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

this code is

        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);

        CustomObjectsApi apiInstance = new CustomObjectsApi();
        String group = "networking.istio.io"; 
        String version = "v1alpha3";
        String namespace = "istio"; 
        String plural = "gateways"; 
        String pretty = "true";
        String labelSelector = null;
        String resourceVersion = null; 
        Boolean watch = false; 

        try {
            String json = "{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"Gateway\",\"metadata\":{\"name\":\"bookinfo-gateway2222222\",\"namespace\":\"istio\"},\"spec\":{\"selector\":{\"istio\":\"ingressgateway\"},\"servers\":[{\"hosts\":[\"bookinfo-gateway2222222\"],\"port\":{\"name\":\"http\",\"number\":80,\"protocol\":\"HTTP\"}}]}}";
            Object object = apiInstance.createNamespacedCustomObject(group, version, namespace, plural, json, pretty);
        } catch (ApiException e) {
            System.err.println("Exception when calling CustomObjectsApi#listClusterCustomObject");
            e.printStackTrace();
        }

**Comment by cliveseldon** [comment]
I think the error messages are sometimes not very helpful. Can you step through the code and see what the Kubernetes server is returning in the raw API call.
BTW: are you sure a "Gateway", CRD exists?

**Comment by li1191863273** [comment]
yes, it exit, I see the k8s code later


	➜  ~ kubectl get crd gateways.networking.istio.io -o yaml
	apiVersion: apiextensions.k8s.io/v1beta1
	kind: CustomResourceDefinition
	metadata:
	  annotations:
	    helm.sh/hook: crd-install
	    helm.sh/hook-weight: "-5"
	  creationTimestamp: 2018-10-24T06:12:41Z
	  generation: 1
	  labels:
	    app: istio-pilot
	  name: gateways.networking.istio.io
	  resourceVersion: "191406"
	  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/gateways.networking.istio.io
	  uid: d0884af4-d753-11e8-99da-00163e134b6a
	spec:
	  additionalPrinterColumns:
	  - JSONPath: .metadata.creationTimestamp
	    description: |-
	      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

	      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
	    name: Age
	    type: date
	  group: networking.istio.io
	  names:
	    categories:
	    - istio-io
	    - networking-istio-io
	    kind: Gateway
	    listKind: GatewayList
	    plural: gateways
	    singular: gateway
	  scope: Namespaced
	  version: v1alpha3
	  versions:
	  - name: v1alpha3
	    served: true
	    storage: true
	status:
	  acceptedNames:
	    categories:
	    - istio-io
	    - networking-istio-io
	    kind: Gateway
	    listKind: GatewayList
	    plural: gateways
	    singular: gateway
	  conditions:
	  - lastTransitionTime: 2018-10-24T06:12:41Z
	    message: no conflicts found
	    reason: NoConflicts
	    status: "True"
	    type: NamesAccepted
	  - lastTransitionTime: null
	    message: the initial names have been accepted
	    reason: InitialNamesAccepted
	    status: "True"
	    type: Established
	  storedVersions:
  - v1alpha3

**Comment by li1191863273** [comment]
k8s respond Internal Server Error

![Uploading image.png…]()

**Comment by brendandburns** [comment]
The client library is doing the right thing here and reporting that the server had an internal server error.

I don't think this is a bug in the client library. Please re-open if you feel otherwise.

**Comment by shrids** [comment]
Observing a similar issue where `createNamespacedCustomObject` fails.

The following command `kubectl create -f zk.yaml` works fine and a new pod(s) are created.
zk.yaml contains.
```
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "example"
spec:
  size: 3
```
But the same request with the k8 java client does not work and the api-server returns a 500...

```
--> POST https://k8-apiserver:8443/apis/zookeeper.pravega.io/v1beta1/namespaces/default/zookeeper-clusters?pretty=true HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 165
authorization: Bearer 
Accept: application/json
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java

"{\"apiVersion\":\"zookeeper.pravega.io/v1beta1\",\"kind\":\"ZookeeperCluster\",\"metadata\":{\"name\":\"example\",\"namespace\":\"default\"},\"spec\":{\"size\":3}}"
--> END POST (165-byte body)
<-- HTTP/1.1 500 Internal Server Error (4591ms)
Audit-Id: c08e24df-079c-48dc-a0e0-04deca664685
Content-Type: application/json
Date: Mon, 12 Nov 2018 05:09:27 GMT
Content-Length: 180
OkHttp-Sent-Millis: 1541999366957
OkHttp-Received-Millis: 1541999367553

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Object 'Kind' is missing in 'object has no kind field '",
  "code": 500
}
<-- END HTTP (180-byte body)
```

**Comment by li1191863273** [comment]
I solved this issue, the body can not be a string, passing a map object can be

**Comment by shrids** [comment]
Thanks @li1191863273  it worked. Used a Map<String, Object> as the `body` parameter ...
