### ISSUE TITLE
EventsV1beta1Api.listNamespacedEvent throws io.kubernetes.client.ApiException: Bad Request when I list event with labelSelector "involvedObject.name=xxxxxx"

### ISSUE THREAD

**Issue by aronica** [kubernetes-client/java#450]
Kubelet version:v1.10.2
kubenetes-java-client version: client-java:2.0.0
Exception code:
**### EventApi.java**
`  @Override
    public V1beta1EventList list(String namespace, String fieldSelector, String resourceVersion) throws MotanException {
        EventsV1beta1Api eventsV1beta1Api = new EventsV1beta1Api(apiClient);
        try {
            return eventsV1beta1Api.listNamespacedEvent(namespace,
                    "false", null, fieldSelector, true,
                    null, 10, resourceVersion, 56, true
                    );
        } catch (ApiException e) {
            log.error("", e);
            throw new MotanException(e.getCode(), e);
        }
    }`
### **Unit Test**
`try {
            V1beta1EventList list = eventApi.list("ml-demo5",
                    "involvedObject.name=demo1-5", null);
            System.out.println(list);
        } catch (MotanException e) {
            e.printStackTrace();
        }`
**Output:**
`Caused by: io.kubernetes.client.ApiException: Bad Request
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEventWithHttpInfo(EventsV1beta1Api.java:977)
	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEvent(EventsV1beta1Api.java:954)`
But when I execute kubectl get event with same fieldSelector, it returns events as expected.

`$ kubectl get event -n ml-demo4 --field-selector involvedObject.name=demo1-5
LAST SEEN   FIRST SEEN   COUNT     NAME                       KIND      SUBOBJECT   TYPE      REASON             SOURCE           MESSAGE
39s         39s          1         demo1-5.156be3f3da048290   Job                   Normal    SuccessfulCreate   job-controller   Created pod: demo1-5-xqpk2`

Expected output: Calling method EventsV1beta1Api.listNamespacedEvent with specified fieldSelectors returns expected events .

**Comment by brendandburns** [comment]
I wonder if you need to url-encode the `=` sign?

You can pull the full message body from the `ApiException` object, hopefully that has some more details about why the request is failing. Can you do that and add that to this issue?

**Comment by aronica** [comment]
> I wonder if you need to url-encode the `=` sign?
> 
> You can pull the full message body from the `ApiException` object, hopefully that has some more details about why the request is failing. Can you do that and add that to this issue?

Firstly, sorry for such a late reply.
I have test with url encoded sign '=' but nothing changed and below is the exception stack

io.kubernetes.client.ApiException: Bad Request#012	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)#012	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)#012	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEventWithHttpInfo(EventsV1beta1Api.java:977)#012	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEvent(EventsV1beta1Api.java:954)#012	at motan.core.k8s.api.impl.EventApiImpl.list(EventApiImpl.java:26)#012	at
motan.core.k8s.api.impl.EventApiTest.testList(EventApiTest.java:18)#012	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)#012	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)#012	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)#012	at java.lang.reflect.Method.invoke(Method.java:498)#012	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)#012	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)#012	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)#012	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)#012	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)#012	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)#012	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)#012	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)#012	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)#012	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)#012	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)#012	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)#012	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)#012	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)#012	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)#012	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)#012	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)#012	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)#012	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)#012	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)#012	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)#012	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)#012	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)#012	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)#012io.kubernetes.client.ApiException: Bad Request
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEventWithHttpInfo(EventsV1beta1Api.java:977)
	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEvent(EventsV1beta1Api.java:954)
	at motan.core.k8s.api.impl.EventApiImpl.list(EventApiImpl.java:26)
	at motan.core.k8s.api.impl.EventApiTest.testList(EventApiTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
2018-12-11 15:01:08.673 DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener[main]: [1 ] ## After test method: context [DefaultTestContext@7e38a7fe testClass = EventApiTest, testInstance = motan.core.k8s.api.impl.EventApiTest@3f446bef, testMethod = testList@EventApiTest, testException = [null], mergedContextConfiguration = [MergedContextConfiguration@366ef90e testClass = EventApiTest, locations = '{classpath:core.xml}', classes = '{}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null]. 
MotanException(code=400)
	at motan.core.k8s.api.impl.EventApiImpl.list(EventApiImpl.java:33)
	at motan.core.k8s.api.impl.EventApiTest.testList(EventApiTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: io.kubernetes.client.ApiException: Bad Request
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEventWithHttpInfo(EventsV1beta1Api.java:977)
	at io.kubernetes.client.apis.EventsV1beta1Api.listNamespacedEvent(EventsV1beta1Api.java:954)
	at motan.core.k8s.api.impl.EventApiImpl.list(EventApiImpl.java:26)
	... 29 more

**Comment by brendandburns** [comment]
You need to print the body from the `ApiException` (`ApiException.getResponseBody()`

That will contain more information about why the request is failing, please add it to this issue.

**Comment by reaperes** [comment]
I have same issue on k8s 1.12. It seems '/apis/events.k8s.io/v1beta1/namespaces/{namespace}/events' api spec.

Try to use CoreV1Api instead of EventsV1beta1Api.
```
coreV1Api.listNamespacedEvent( ... )
```

**Comment by yue9944882** [comment]
`events.k8s.io` is a half-done (or even not implemented) work. use the v1 group instead.

[https://github.com/gmarek/community/blob/f452e8e335d29b13089700c2b8b434027283fe37/contributors/devel/event-style-guide.md](https://github.com/gmarek/community/blob/f452e8e335d29b13089700c2b8b434027283fe37/contributors/devel/event-style-guide.md)
