### ISSUE TITLE
Unable to authenticate using token and ca.crt files

### ISSUE THREAD

**Issue by darren-rose** [kubernetes-client/java#454]
I am unable to auth from a docker container inside kubernetes. My dockerfile contains

ADD token /var/run/secrets/kubernetes.io/serviceaccount/token
ADD ca.crt /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

and I am using         return Config.fromCluster();

Error reported:

Caused by: io.kubernetes.client.ApiException: Forbidden
at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882) ~[client-java-3.0.0.jar!/:?]
at io.kubernetes.client.ApiClient.execute(ApiClient.java:798) ~[client-java-3.0.0.jar!/:?]
at io.kubernetes.client.apis.BatchV1Api.createNamespacedJobWithHttpInfo(BatchV1Api.java:164) ~[client-java-api-3.0.0.jar!/:?]
at io.kubernetes.client.apis.BatchV1Api.createNamespacedJob(BatchV1Api.java:148) ~[client-java-api-3.0.0.jar!/:?]

**Comment by brendandburns** [comment]
You shouldn't add those files to your container image. Kubernetes will mount them in automatically when you run the container in the cluster.

See:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server

(and in general, it's a pretty bad idea to place secrets inside a container image, since they can easily leak)

If you continue to get an error, please dump the full response body from the `ApiException` object it should contain more details.

**Comment by darren-rose** [comment]
Thanks, I am no longer mounting those files, as you said, they are mounted anyway. the issue was that I needed to refer to a service account with the appropriate privileges
