### ISSUE TITLE
Google Kubernetes Engine: io.kubernetes.client.ApiException: Forbidden

### ISSUE THREAD

**Issue by PascalKu** [kubernetes-client/java#457]
```
 KubeConfig.registerAuthenticator( new GCPAuthenticator() );
        final ApiClient client = new ApiClient();
        client.setBasePath( "https://kubernetes.default.svc" );
        
        client.setUsername( "rapi-user" );
        client.setVerifyingSsl( false );

        Configuration.setDefaultApiClient( client );

        this.api = new CoreV1Api();
```

My user cannot access cause "Forbidden".

> io.kubernetes.client.ApiException: Forbidden
>         at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882) ~[client-java-3.0.0.jar!/:na]
>         at io.kubernetes.client.ApiClient.execute(ApiClient.java:798) ~[client-java-3.0.0.jar!/:na]
>         at io.kubernetes.client.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:16718) ~[client-java-api-3.0.0.jar!/:na]
>         at io.kubernetes.client.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:16695) ~[client-java-api-3.0.0.jar!/:na]
>         at com.github.pascalku.teamspeakrestapi.components.SpaceComponent.lambda$isSpaceRunning$2(SpaceComponent.java:139) ~[classes!/:0.0.1-SNAPSHOT]
>         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) ~[guava-19.0.jar!/:na]
>         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) ~[guava-19.0.jar!/:na]
>         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) ~[guava-19.0.jar!/:na]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
>         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

The container has access to the serviceAccount: rapi-user

Pls help me.

**Comment by PascalKu** [comment]
Just used the wrong method. Using a token with admin access works well.
