### ISSUE TITLE
ClassCastException observed while trying to read ~/.kube/config file.

### ISSUE THREAD

**Issue by shrids** [kubernetes-client/java#460]
Hi,

Observing a class cast exception when kubernetes client tries to verify if the key has expired. 
```
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Date
	at io.kubernetes.client.util.authenticators.GCPAuthenticator.isExpired(GCPAuthenticator.java:40)
	at io.kubernetes.client.util.KubeConfig.getAccessToken(KubeConfig.java:200)
	at io.kubernetes.client.util.credentials.KubeconfigAuthentication.<init>(KubeconfigAuthentication.java:33)
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:212)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:96)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:75)
	at io.kubernetes.client.util.Config.defaultClient(Config.java:104)
```

The kubectl config was generated using gcloud. 

The config file snippet is as follows.
```
current-context: cluster-1
kind: Config
preferences: {}
users:
- name: cluster-1
  user:
    auth-provider:
      config:
        access-token:  REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "2018-12-10T08:46:57Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

```
Interestingly I observe that there is a unit test for the same. https://github.com/kubernetes-client/java/blob/master/util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java

Any pointers on to resolve this issue would be super helpful...

**Comment by brendandburns** [comment]
I think it's the quote marks around the `expiry` field.  Can you try removing those?

**Comment by shrids** [comment]
Thanks. Yes, it work if we remove the quote marks.

I am currently using a gcloud version 227, which is the latest. Need to figure why this version of gcloud is generating the quote marks...
```
gcloud --version
Google Cloud SDK 227.0.0
alpha 2018.11.30
beta 2018.11.30
bq 2.0.39
core 2018.11.30
gsutil 4.34
kubectl 2018.11.30
```

**Comment by brendandburns** [comment]
Well, I also think that we can do better here, I'll see if we can improve the code for this case too.
