### ISSUE TITLE
Custom Spark-Operator build error: var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

### ISSUE THREAD

**Issue by roksolana-d** [kubernetes-client/java#466]
I have been trying to build a custom image from the Dockerfile (I have cloned repository to the local machine). For that I have defined a docker-compose.yml file. I set up envs for Kubernetes service port and host. When I run this image with `docker-compose up` I get such an error:

```
Starting sparkairflowk8s_spark-operator-k8s_1 ... done
Attaching to sparkairflowk8s_spark-operator-k8s_1
spark-operator-k8s_1  | F1214 15:37:23.119824       1 main.go:80] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
spark-operator-k8s_1  | goroutine 1 [running]:
spark-operator-k8s_1  | github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.stacks(0xc000306200, 0xc0003c2000, 0x7e, 0xd3)
spark-operator-k8s_1  |         /go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:769 +0xd4
spark-operator-k8s_1  | github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.(*loggingT).output(0x1f9ed80, 0xc000000003, 0xc0003bc000, 0x1f203a1, 0x7, 0x50, 0x0)
spark-operator-k8s_1  |         /go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:720 +0x329
spark-operator-k8s_1  | github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.(*loggingT).printDepth(0x1f9ed80, 0xc000000003, 0x1, 0xc0000e1ed0, 0x1, 0x1)
spark-operator-k8s_1  |         /go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:646 +0x129
spark-operator-k8s_1  | github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.(*loggingT).print(0x1f9ed80, 0x3, 0xc0000e1ed0, 0x1, 0x1)
spark-operator-k8s_1  |         /go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:637 +0x5a
spark-operator-k8s_1  | github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.Fatal(0xc0000e1ed0, 0x1, 0x1)
spark-operator-k8s_1  |         /go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:1128 +0x53
spark-operator-k8s_1  | main.main()
spark-operator-k8s_1  |         /go/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/main.go:80 +0x144
sparkairflowk8s_spark-operator-k8s_1 exited with code 255
```

What could be the reason for such an error? Is there something wrong in the docker-compose definition?

Docker-compose file looks like this:
```
version: "3.2"
services:
  spark-operator-k8s:
    image: spark:2.4.0
    environment:
      KUBERNETES_SERVICE_HOST: 'kubernetes.default.svc.cluster.local'
      KUBERNETES_SERVICE_PORT: '443'
```

**Comment by brendandburns** [comment]
It looks like you are trying to use an in-cluster configuration, but your Pod doesn't have the right service account files.

See details here:

**Comment by brendandburns** [comment]
Are you running this in Kubernetes? or just Docker? loading from an in-cluster config only works if you run it in Kubernetes (or map the right files into the right locations, but that's tricky)

If you want to run it locally, you should load from `$KUBECONFIG` or `$HOME/.kube/config`

**Comment by roksolana-d** [comment]
I run it using Docker image defined in docker-compose. I thought that I should run this Docker image, then run my application file for the operator. Did I understand it in a wrong way?

**Comment by brendandburns** [comment]
In-cluster config is designed to be used from within a Kubernetes cluster. It can be made to work elsewhere, but it's probably not the suggested approach. In other environments you want to pass in a `kubeconfig` file somehow.
