### ISSUE TITLE
Webhooks on pods creation ApiException: Unprocessable Entity

### ISSUE THREAD

**Issue by roksolana-d** [kubernetes-client/java#472]
I create webhook on pods creation in the test suite (class SparkExampleIntegrationTest). BeforeAll method contains a call for the creation of the webhook. I am not sure what is wrong with the definition of the webhook as when I define the name and nothing else, webhook is created properly. Where can be a problem of the configuration? And is it possible to read webhook configs from the yaml file (same as for other object)?

This is how I define the webhook:

```
    val webhookBody = new V1beta1ValidatingWebhookConfiguration
    val objectMeta = new  V1ObjectMeta
    objectMeta.setName("pods-webhook")

    val webhook = new V1beta1Webhook
    val podsCreationRule = new V1beta1RuleWithOperations

    webhook.setName("create-pods-webhook")

    val webhookClientConfig = new V1beta1WebhookClientConfig
    val webhookService = new AdmissionregistrationV1beta1ServiceReference
    webhookService.setName("create-pods-webhook-svc")
    webhookService.setNamespace("default")
    webhookService.setPath("/validate")

    webhookClientConfig.setService(webhookService)
    webhook.setClientConfig(webhookClientConfig)

    podsCreationRule.setApiGroups(ListBuffer("pods").asJava)
    podsCreationRule.setApiVersions(ListBuffer("v1").asJava)
    podsCreationRule.setOperations(ListBuffer("CREATE").asJava)
    podsCreationRule.setResources(ListBuffer("pods").asJava)
    webhook.setRules(ListBuffer(podsCreationRule).asJava)


    webhookBody.setMetadata(objectMeta)
    webhookBody.setWebhooks(ListBuffer(webhook).asJava)

    val webhookCreation = admissionApiInstance.createValidatingWebhookConfiguration(webhookBody, "true")
```

Here is the stack trace of the exception:

```
io.kubernetes.client.ApiException: Unprocessable Entity
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.AdmissionregistrationV1beta1Api.createValidatingWebhookConfigurationWithHttpInfo(AdmissionregistrationV1beta1Api.java:289)
	at io.kubernetes.client.apis.AdmissionregistrationV1beta1Api.createValidatingWebhookConfiguration(AdmissionregistrationV1beta1Api.java:274)
	at it_tests.SparkExampleIntegrationTest.createWebhookOnPods(SparkExampleIntegrationTest.scala:105)
	at it_tests.SparkExampleIntegrationTest.beforeAll(SparkExampleIntegrationTest.scala:116)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at it_tests.SparkExampleIntegrationTest.run(SparkExampleIntegrationTest.scala:19)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1357)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1351)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1351)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1048)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1027)

()	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1517)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1027)
	at org.scalatest.tools.Runner$.run(Runner.scala:855)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by roksolana-d** [comment]
I tried this option `apiClient.setDebugging(true)` and found out that the name of the webhook was wrong. I changed it to `create.pods.webhook` and the webhook was created
