### ISSUE TITLE
APINotFound Exception when watch on CustomObjectStatus is created

### ISSUE THREAD

**Issue by roksolana-d** [kubernetes-client/java#476]
I have created a watch on custom object status call , but the creation line keeps returning APINorFound exception:

```
An exception or error caused a run to abort: Not Found 
io.kubernetes.client.ApiException: Not Found
	at io.kubernetes.client.util.Watch.createWatch(Watch.java:107)
	at it_tests.SparkExampleIntegrationTest.beforeAll(SparkExampleIntegrationTest.scala:89)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at it_tests.SparkExampleIntegrationTest.run(SparkExampleIntegrationTest.scala:19)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1357)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1351)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1351)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1048)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1027)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1517)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1027)
	at org.scalatest.tools.Runner$.run(Runner.scala:855)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

I have created a custom object before that with the same group, namespace, version and so on. This custom object gets created without any problems and can be viewed using kubectl. I can't use debug mode with a watch to see exactly what is happening. But I suspect the reason is the fact that Status for custom objects produces null all the time.
What could be the reason for such an error?
Here is how it looks in code:

```
    val sparkAppCreation = apiInstance.createNamespacedCustomObject(crdGroup, crdVersion, crdNamespace, crdPlural, customObjectBody,"false")

    val watchCustomObjects: Watch[V1Namespace]  = Watch.createWatch(apiClient, apiInstance.getNamespacedCustomObjectStatusCall(crdGroup, crdVersion,  crdNamespace, crdPlural, crdInstanceName, null, null), new TypeToken[Watch.Response[V1Namespace]]{}.getType)
```

**Comment by yue9944882** [comment]
> But I suspect the reason is the fact that Status for custom objects produces null all the time.

what version is ur cluster? subresource (status, scale..) is dropped to be null at server unless u enabled its feature gate

**Comment by roksolana-d** [comment]
I use K8s from Minikube.  How to enable subresource in this case?

**Comment by cliveseldon** [comment]
Its alpha in 1.10 and beta in 1.13
See [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#subresources) and [here](https://blog.openshift.com/kubernetes-custom-resources-grow-up-in-v1-10/)

You should add to your CRD:
```
"subresources": {
            "status": {}
        }
```
The latest version of minikube 0.32.0 runs 1.12.4 k8s API

You might have to run with minikube (not tried)
```
--feature-gates=CustomResourceSubresources=true
```

**Comment by roksolana-d** [comment]
I have added this lines to my CRD definition and I still get the same error:

```
  subresources:
    status: {}
```
I started Minikube with this flag `--feature-gates=CustomResourceSubresources=true`. Minikube is with Kubernetes version v1.12.0 cluster

**Comment by roksolana-d** [comment]
So I tried `getNamespacedCustomObjectStatusCall` and `getNamespacedCustomObjectStatusWithHttpInfo`. They all return `ApiException: NotFound` like there is no status. Although, Status is displayed in the custom object events sections (using kubectl) and returns null if I try to output this status using this java-client.

**Comment by roksolana-d** [comment]
The Response body for this exception looks like this:

`the server could not find the requested resource`

The whole stack trace looks like this:
```

An exception or error caused a run to abort: Not Found 
io.kubernetes.client.ApiException: Not Found
	at io.kubernetes.client.util.Watch.createWatch(Watch.java:107)
	at it_tests.SparkExampleIntegrationTest.createCustomObjectWatch(SparkExampleIntegrationTest.scala:80)
	at it_tests.SparkExampleIntegrationTest.beforeAll(SparkExampleIntegrationTest.scala:111)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at it_tests.SparkExampleIntegrationTest.run(SparkExampleIntegrationTest.scala:21)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1357)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1351)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1351)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1048)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1027)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1517)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1027)
	at org.scalatest.tools.Runner$.run(Runner.scala:855)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

Could it be connected with subresources feature (status as custom object subresources) which is only available in Kubernetes cluster v1.13.0 beta version?

**Comment by cliveseldon** [comment]
It looks to me like it can't find that resource as you suggest. What version of Minikube are you using and how do you start it? Can you confirm which version of the k8s API minikube starts?

**Comment by roksolana-d** [comment]
This is how I start minikube (version: v0.32.0):

`minikube start --kubernetes-version v1.13.0 --memory 8048 --cpus 3`

**Comment by roksolana-d** [comment]
I checked `curl http://localhost:8090/apis/sparkoperator.k8s.io/v1alpha1/namespaces/default/sparkapplications/` output and I get all the custom object information.
However, when I try to get the status with `curl http://localhost:8090/apis/sparkoperator.k8s.io/v1alpha1/namespaces/default/sparkapplications/status` the response looks like this:
```
 {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "sparkapplications.sparkoperator.k8s.io \"status\" not found",
  "reason": "NotFound",
  "details": {
    "name": "status",
    "group": "sparkoperator.k8s.io",
    "kind": "sparkapplications"
  },
  "code": 404
```
