### ISSUE TITLE
Transform object to yaml and back has problem

### ISSUE THREAD

**Issue by lephix** [kubernetes-client/java#479]
Pom as following:

            <dependency>
              <groupId>io.kubernetes</groupId>
              <artifactId>client-java</artifactId>
              <version>3.0.0</version>
            </dependency>

I am using io.kubernetes.client.util.Yaml class to do the transformation from object and back. Codes as following.

    V1Pod pod = coreV1Api.readNamespacedPod(podName, namespace, null, null, null);
    String yaml = Yaml.dump(pod);
    V1Pod pod2 = Yaml.loadAs(yaml, V1Pod.class)

I encounter the error with line 3 like following:

    org.yaml.snakeyaml.nodes.MappingNode cannot be cast to org.yaml.snakeyaml.nodes.ScalarNode
     in 'reader', line 4, column 22:
          creationTimestamp: {}
                             ^
    
      at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:270)
      at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
      at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
      at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
      at io.kubernetes.client.util.Yaml$CustomConstructor.constructObject(Yaml.java:334)
      at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:247)
      ... 12 more
    Caused by: java.lang.ClassCastException: org.yaml.snakeyaml.nodes.MappingNode cannot be cast to org.yaml.snakeyaml.nodes.ScalarNode
      at io.kubernetes.client.util.Yaml$CustomConstructor.constructObject(Yaml.java:331)
      at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:247)
      ... 17 more
    
Here is the snippet of the yaml transformed from object

    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: {}
      generateName: test-776d6c86cc-
      labels:
        app: test
        app-version: '19911'
        pod-template-hash: '3328274277'
      name: test-776d6c86cc-4zwj5
      namespace: default
    ...

Here is the snippet of the yaml when I use `kubectl edit pod xxxx` command:

    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: "2018-12-23T01:09:18Z"
      generateName: test-776d6c86cc-
      labels:
        app: test
        app-version: "19911"
        pod-template-hash: "3328274277"
      name: test-776d6c86cc-4zwj5
      namespace: default

It seems Yaml class has some problem to convert DateTime to String

**Comment by brendandburns** [comment]
Sorry about the delay here, but I finally had time to find the problem and send a PR with the fix.

**Comment by jingb** [comment]
@brendandburns   hi brendandburns .
When would you publish a new version to fix it ？ I have already upgrade to 4.0.0-betal version, but it dose not work, and I can't find the RepresentDateTime  class in util/src/main/java/io/kubernetes/client/util/Yaml.java
