### ISSUE TITLE
Running exec and attach example get 400 Bad request

### ISSUE THREAD

**Issue by lephix** [kubernetes-client/java#481]
I set the apiclient correctly, I can get pod, replace pod etc,.
But when I ran the example of exec and attach get following errors:

    --> GET https://xxxx.com:6443/api/v1/namespaces/default/pods/plan-task-test-548756c754-4trnw/exec?stdin=true&stdout=true&stderr=true&tty=true&command=sh     HTTP/1.1
    Sec-WebSocket-Protocol: v4.channel.k8s.io
    User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Key: tCWA75OzR3YO6LlNj39xXg==
    Sec-WebSocket-Version: 13
    --> END GET
    <-- HTTP/1.1 400 Bad Request (109ms)
    Content-Type: application/json
    Date: Wed, 09 Jan 2019 10:54:45 GMT
    Content-Length: 234
    OkHttp-Sent-Millis: 1547031285380
    OkHttp-Received-Millis: 1547031285398
    Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
    	at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
    	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
    	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
    	at com.squareup.okhttp.Call.access$100(Call.java:35)
    	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
    	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

Anyone please help me to identify the problem.

**Comment by brendandburns** [comment]
What version of the library are you running?

This looks like the same issue as #180 but that has been fixed...

**Comment by lephix** [comment]
@brendandburns 
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>3.0.0</version>
        </dependency>

**Comment by radhe-sravan** [comment]
@lephix is this resolved for you? I am facing the exact same issue with the same version of client library.

**Comment by lephix** [comment]
@radhe-sravan No. I am using fabric8 library for this func instead.

**Comment by zdf068** [comment]
is this resolved for you? I have a same issue too

**Comment by ZhenghaeHo** [comment]
@lephix how did you resolved this issue？
