### ISSUE TITLE
Issue using defaultClient on Windows

### ISSUE THREAD

**Issue by falken** [kubernetes-client/java#486]
Running this code on windows
ApiClient client = Config.defaultClient();

Generates this exception:
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at io.kubernetes.client.util.ClientBuilder.findHomeDir(ClientBuilder.java:121)
	at io.kubernetes.client.util.ClientBuilder.findConfigInHomeDir(ClientBuilder.java:149)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:89)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:75)
	at io.kubernetes.client.util.Config.defaultClient(Config.java:104)

The problem seems to be that System.getenv(ENV_HOME) in this line:
final File config = new File(System.getenv(ENV_HOME));
returns null, causing the File constructor to fail.

I would suggest a simple null check or default to empty string.

**Comment by brendandburns** [comment]
This was fixed at HEAD by #455 

Looks like I need to cut a new release....

**Comment by brendandburns** [comment]
Release 4.0.0 was cut in february so this should be fixed there.
