### ISSUE TITLE
IllegalStateException: Expected BEGIN_OBJECT but was STRING while getting namespacedPod

### ISSUE THREAD

**Issue by roksolana-d** [kubernetes-client/java#493]
I am trying to retrieve pod logs. When I try to get the information about it with `kubectl get pod -l spark-role=driver` I can get the pod so it exists. However, when I try to get the pod with Java-client I keep getting the error.

Here is the code for the pod logs retrieval:

```
    val podLogs = new PodLogs()
    val pods = coreApi.listNamespacedPod(crdNamespace, null, null, null, null, "spark-role=driver", null, null, 0, false)
    val podInstance = pods.getItems.get(0)
    val inputStream = podLogs.streamNamespacedPodLog(podInstance)
    ByteStreams.copy(inputStream, System.out)
```
What could be the reason of it?

Stack trace:
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2301
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2301
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at io.kubernetes.client.JSON.deserialize(JSON.java:108)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:16718)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:16695)
	at it_tests.EmptyIntegrationTest$$anonfun$1.apply$mcV$sp(EmptyIntegrationTest.scala:42)
	at it_tests.EmptyIntegrationTest$$anonfun$1.apply(EmptyIntegrationTest.scala:32)
	at it_tests.EmptyIntegrationTest$$anonfun$1.apply(EmptyIntegrationTest.scala:32)
```

**Comment by brendandburns** [comment]
Its a little hard to know without seeing the response, but I suspect that you are hitting an endpoint that isn't the Kubernetes API server...

**Comment by roksolana-d** [comment]
For some reason, when I stop Minikube and start it again, everything may work fine. But at some point I get this error

**Comment by brendandburns** [comment]
Closing this, since I'm pretty sure your apiserver was unhappy somehow.
