### ISSUE TITLE
TimeOut Exception in portForwarding

### ISSUE THREAD

**Issue by karunakarl** [kubernetes-client/java#518]
Hi..
I am port-forwarding a pod from cluster to my local machine and I have example for port-forwarding and I am getting socketTimeout Exception.

code and exception as follows. could some one help me how to resolve this.

Code as follows.

```
ApiClient client =     Config.defaultClient();
        Configuration.setDefaultApiClient(client);
       CoreV1Api api = new CoreV1Api();
       V1NamespaceList list = api.listNamespace(null, null, null, null, null, null, null, null, null);
       String solutionId = "2514z820wd2";
       String requiredNameSpace = "";
        for (V1Namespace namespace : list.getItems()) {
            if(namespace.getMetadata().getName().contains(solutionId)){
                requiredNameSpace = namespace.getMetadata().getName();
            }
        }

        PortForward forward = new PortForward();
       // forward.
        List<Integer> ports = new ArrayList<>();
        ports.add(27017);
        ports.add(27017);
        final PortForward.PortForwardResult result =
                forward.forward(requiredNameSpace, "mongo-service-0", ports);

        ServerSocket ss = new ServerSocket(27010);
        ss.setSoTimeout(0);
        final Socket s = ss.accept();
        System.out.println("Connected!");
        new Thread(
                new Runnable() {
                    public void run() {
                        try {
                            ByteStreams.copy(result.getInputStream(80), s.getOutputStream());
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                })
                .start();

        new Thread(
                new Runnable() {
                    public void run() {
                        try {
                            ByteStreams.copy(s.getInputStream(), result.getOutboundStream(80));
                        } catch (IOException ex) {
                            ex.printStackTrace();
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                })
                .start();
        System.out.println("Connected!");


        Thread.sleep(60 * 1000);
        System.out.println("timed out");
    }
}
```
Exception as follows.

java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 14 more

Could some one help me..

**Comment by brendandburns** [comment]
PortForward will eventually timeout. You can adjust the timeout as per here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/WatchExample.java#L30

But in general socket timeouts will likely eventually happen anyway and your code should handle them.
