### ISSUE TITLE
Issue while creating Deployment and Service

### ISSUE THREAD

**Issue by CloudDevBe** [kubernetes-client/java#528]
I am using kubernetes-client 4.1.3 and kubernetes-api 3.0.12 jars.
There was no issue while connecting to the GKE cluster via GCP authenticator

Here is my code snippet:
```
         KubeConfig.registerAuthenticator(new GCPAuthenticator());
    
        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);

        CoreV1Api api = new CoreV1Api();
      
        HashMap<String,String> hm = new HashMap<String,String>();
        hm.put("app", "hello-be");
        
        V1Deployment deployment = new V1DeploymentBuilder()
        		.withApiVersion("apps/v1beta1")
        		.withNewMetadata()
        		.withName("hello-be-deployment")
        		.endMetadata()
        		.withNewSpec()
        		.withNewTemplate()
        		.withNewMetadata()
        		.withLabels(hm)
        		.endMetadata()
        		.withNewSpec()
        		.addNewContainer()
        		.withName("hello-be")
        		.withImage("nginx")
        		.endContainer()
        		.endSpec()
        		.endTemplate()
        		.endSpec()
        		.build();
  
        
        V1Service svc = new V1ServiceBuilder()
        	    .withApiVersion("v1")
                    .withNewMetadata()
                    .withName("fdservice")
                    .endMetadata()
                    .withNewSpec()
                    .withSelector(hm)
                    .addNewPort()
                    .withProtocol("TCP")
                    .withName("client")
                    .withPort(8108)
                    .endPort()
                    .withType("LoadBalancer")
                    .endSpec()
                    .build();
      
        api.createNamespacedService("default", svc, true, "true", ""); 
```

But while creating Service and Deployment, following issue occurs:

```
 Exception in thread "main" io.kubernetes.client.ApiException: Bad Request
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedServiceWithHttpInfo(CoreV1Api.java:9415)
	at io.kubernetes.client.apis.CoreV1Api.createNamespacedService(CoreV1Api.java:9397)
	at src.com.amazonaws.services.cloudformation.hellocdk.src.main.java.com.myorg.HelloStack5.<init>(HelloStack5.java:164)
	at src.com.amazonaws.services.cloudformation.hellocdk.src.main.java.com.myorg.HelloStack5.<init>(HelloStack5.java:59)
	at src.com.amazonaws.services.cloudformation.hellocdk.src.main.java.com.myorg.HelloApp.main(HelloApp.java:16) ```


Anyone have advice on fixing this error?

**Comment by brendandburns** [comment]
Your Service or Deployment is invalid somehow. If you print `ApiException.getBody()` you should get more info about why.

This isn't a bug in the library, it's in your code, so closing.

**Comment by CloudDevBe** [comment]
@brendanburns Please suggest, what should be the value for dryRun in above code.

I am facing below issue:
```
{Audit-Id=[020c2b90-cb45-4910-967d-9e9bbda65a62], Content-Type=[application/json], Date=[Mon, 18 Mar 2019 17:25:46 GMT], Content-Length=[178], OkHttp-Sent-Millis=[1552929908272], OkHttp-Received-Millis=[1552929908330]}
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "dryRun is not supported yet",
  "reason": "BadRequest",
  "code": 400
} ```

**Comment by CloudDevBe** [comment]
@brendandburns dryRun is not supported yet is the issue.

**Comment by lephix** [comment]
> @brendandburns dryRun is not supported yet is the issue.

I saw you put an empty String for the dryRun parameter.  Can you show the ApiException for the error?

Following is the JavaDoc about the dryRun param. I cannot figure out what is the potential value for it.

>  dryRun – When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed (optional)

@brendanburns

**Comment by yue9944882** [comment]
whats your sever version? `dryrun` won't work before 1.13 unless the feature gate is on.

**Comment by lephix** [comment]
Thanks for you explanation. @yue9944882 I am testing on 1.10.
