### ISSUE TITLE
io.kubernetes.client.ApiException: Forbidden at K8S pod

### ISSUE THREAD

**Issue by headiron** [kubernetes-client/java#542]
Hello All.

I'm writing cronjob which is scheduled ( & running ) at K8S to fetch some K8S data.

I confirmed that it is working well at minkikube so I try to run it on K8S and got Forbidden error .

Do I need to add some config on it ? 
I see Skuber ( Scala k8s library ) support in-cluster config , so I believe java library also has similar thing.
https://github.com/doriordan/skuber/issues/234

import skuber._
import skuber.api.Configuration
...
val k8s = k8sInit(Configuration.inClusterConfig.get)

I'm using java library 4.0.0 in Scala and below is error message
 

Caused by: io.kubernetes.client.ApiException: Forbidden
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.BatchV1beta1Api.listNamespacedCronJobWithHttpInfo(BatchV1beta1Api.java:995)
	at io.kubernetes.client.apis.BatchV1beta1Api.listNamespacedCronJob(BatchV1beta1Api.java:972)

**Comment by brendandburns** [comment]
The k8s service account that your cluster is giving you probably doesn't have the right permissions.

Please see details here:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

Closing as this is outside the scope of this library.
