### ISSUE TITLE
JNI error when run example jar by 'java -jar'

### ISSUE THREAD

**Issue by keaxu-exp** [kubernetes-client/java#545]
Main class:

```
public class Main {
    public static void main(String[] args) throws IOException, ApiException {
        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);

        CoreV1Api api = new CoreV1Api();
        V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
        for (V1Pod item : list.getItems()) {
            System.out.println(item.getMetadata().getName());
        }
    }
}
```

When I run jar by this:

```
java -jar example.jar
```

I got:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: io/kubernetes/client/ApiException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.kubernetes.client.ApiException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

I build jar by gradle, here is gradle build:
```
plugins {
    id 'java'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'example.Main'
        )
    }
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {

    compile 'io.kubernetes:client-java:4.0.0'

    testCompile group: 'junit', name: 'junit', version: '4.12'
}

```

**Comment by keaxu-exp** [comment]
I think I found the solution. should use "./gradlew shadowJar" from https://github.com/johnrengelman/shadow

"./gradlew  showJar" includes all dependencies while "./gradlew jar" only includes source code in the project itself.

**Comment by Lavie526** [comment]
Thanks for sharing, i meet the same issue with you.
