### ISSUE TITLE
Access token expiry cannot be parsed

### ISSUE THREAD

**Issue by robinkanters** [kubernetes-client/java#549]
There must be something weird about my access token or something, because even the following line will throw an error:

```kotlin
val client = Config.defaultClient()
```

Stack trace:

```
Exception in thread "main" java.time.format.DateTimeParseException: Text '2019-04-08T14:03:14.311732+02:00' could not be parsed at index 26
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.Instant.parse(Instant.java:395)
	at io.kubernetes.client.util.authenticators.GCPAuthenticator.isExpired(GCPAuthenticator.java:52)
	at io.kubernetes.client.util.KubeConfig.getAccessToken(KubeConfig.java:201)
	at io.kubernetes.client.util.credentials.KubeconfigAuthentication.<init>(KubeconfigAuthentication.java:33)
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:215)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:96)
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:75)
	at io.kubernetes.client.util.Config.defaultClient(Config.java:104)
```

**Comment by brendandburns** [comment]
Can you attach your kubeconfig file (after removing any tokens/certificates/personal data)

Thanks!

**Comment by robinkanters** [comment]
I think this is the part you care about. It has the date format from the stack trace. If you need more, I can give that.

```
apiVersion: v1
....
users:
- name: <removed>
  user:
    auth-provider:
      config:
        access-token: <token>
        expiry: "2019-03-27T13:59:16.815241+01:00"
      name: gcp
```

**Comment by yue9944882** [comment]
field `auth-provider` should be deserialized as a string-string map but the client is parsing the in-tree fields to DateTime. 

[https://github.com/kubernetes/client-go/blob/ca8df85b1798c94b0545976f8c87747a112cf41e/tools/clientcmd/api/types.go#L152](https://github.com/kubernetes/client-go/blob/ca8df85b1798c94b0545976f8c87747a112cf41e/tools/clientcmd/api/types.go#L152)
