### ISSUE TITLE
 java.net.UnknownServiceException: Unable to find acceptable protocols.

### ISSUE THREAD

**Issue by surbhibakhtiyar** [kubernetes-client/java#551]
I m getting the following exception while calling `listNamespacedPod` function

> 

[4/8/19 9:48:42:179 UTC] 000000dc id=         SystemErr                                                    R io.kubernetes.client.ApiException: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true), ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_0], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1]

[4/8/19 9:48:42:180 UTC] 000000dc id=         SystemErr                                                    R 	at io.kubernetes.client.ApiClient.execute(ApiClient.java:801)

[4/8/19 9:48:42:181 UTC] 000000dc id=         SystemErr                                                    R 	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:17024)

[4/8/19 9:48:42:181 UTC] 000000dc id=         SystemErr                                                    R 	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:17001)

**Code used :**
```
ApiClient client=Config.fromToken(url,token,false);
CoreV1Api api =new CoreV1Api(client);
V1PodList list = api.listNamespacedPod(namespace,null, null, null, null, null, null, null, null, null);
```

**Comment by surbhibakhtiyar** [comment]
@brendandburns ^^

**Comment by brendandburns** [comment]
This is in the SSL layer, this library isn't involved afaik, see this issue for example:

https://github.com/square/okhttp/issues/2947

**Comment by brendandburns** [comment]
Closing this.
