### ISSUE TITLE
NullPinterException when call stopAllRegisteredInformers immediately after startAllRegisteredInformers

### ISSUE THREAD

**Issue by cizezsy** [kubernetes-client/java#578]
Stack trace:
```java
Exception in thread "main" java.lang.NullPointerException
	at io.kubernetes.client.informer.cache.Controller.stop(Controller.java:113)
	at io.kubernetes.client.informer.impl.DefaultSharedIndexInformer.stop(DefaultSharedIndexInformer.java:149)
	at io.kubernetes.client.informer.SharedInformerFactory.lambda$stopAllRegisteredInformers$1(SharedInformerFactory.java:131)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.kubernetes.client.informer.SharedInformerFactory.stopAllRegisteredInformers(SharedInformerFactory.java:127)
```

Codes to reproduce this error:
```java
ApiClient client = Config.fromCluster();
CoreV1Api api = new CoreV1Api();
Configuration.setDefaultApiClient(client);

SharedInformerFactory factory = new SharedInformerFactory();
factory.sharedIndexInformerFor(
      (CallGeneratorParams params) -> {
          try {
              return api.listNamespaceCall(
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      params.resourceVersion,
                      params.timeoutSeconds,
                      params.watch,
                      null,
                      null);
          } catch (ApiException e) {
              throw new RuntimeException(e);
          }
      }, V1Namespace.class, V1NamespaceList.class);


factory.startAllRegisteredInformers();
factory.stopAllRegisteredInformers();
```

**Comment by brendandburns** [comment]
cc @yue9944882
