### ISSUE TITLE
Copy is not working, due PKIX path building failed

### ISSUE THREAD

**Issue by nianjiang** [kubernetes-client/java#601]
HI, 
I try to copy file from pod, but java client is not working (See details below).

Then,  I try the kubectl, it works, see my command:
kubectl cp ingress-nginx/nginx-ingress-controller-78474696b4-lxhr8:/etc/nginx/nginx.conf .

I do the same thing with java client, but it failed:
see the code
```
public static void printNginxConfWithkubeConf(String p_namespace) throws ApiException, IOException {
		ApiClient client = Config.defaultClient();	
		CoreV1Api coreApi = new CoreV1Api(client);
		
		Copy copy = new Copy();
		V1PodList pods = coreApi.listNamespacedPod(p_namespace, null, null, null, null, null, null, null, null, null);
		log.info("Size: {}" ,pods.getItems().size());
		V1Pod pod = pods.getItems().get(0);
		log.info("Name: {}, Namespace: {}" ,pod.getMetadata().getName(), pod.getMetadata().getNamespace());
		InputStream fileStream = copy.copyFileFromPod(pod, "/etc/nginx/nginx.conf");
		String context = inputStream2String(fileStream);
		log.info("Context: {}", context);
	}
```
see the log:
```
11:34:15.637 IngressAPI [main] INFO   - Size: 1
11:34:15.641 IngressAPI [main] INFO   - Name: nginx-ingress-controller-78474696b4-lxhr8, Namespace: ingress-nginx
11:34:15.674 IngressAPI [main] INFO   - Context: 
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.access$100(Call.java:35)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 30 more
```

**Comment by yue9944882** [comment]
it's failing on SSL handshaking.. to build a in-cluster client, consider using `ClientBuilder` 

```java
CoreV1Api coreApi = new CoreV1Api(ClientBuilder.cluster().build());
```

**Comment by nianjiang** [comment]
FIxed the issue. It is my code issue. Missing some config.

missing configt are:
CoreV1Api coreApi = new CoreV1Api(**client**);
new ClientBuilder().setVerifyingSsl(**false**)


See the whole code:
```
public static void printNginxConf(String url, String token, String certFile, String p_namespace) throws ApiException, IOException {
		ApiClient client = new ClientBuilder().setBasePath(url).setAuthentication(new AccessTokenAuthentication(token)).setVerifyingSsl(false)
				.setCertificateAuthority(Files.readAllBytes(new File(certFile).toPath())).build();
		CoreV1Api coreApi = new CoreV1Api(client);
		Copy copy = new Copy(client);
		V1PodList pods = coreApi.listNamespacedPod(p_namespace, null, null, null, null, null, null, null, null, null);
		V1Pod pod = pods.getItems().get(0);
		log.info("Name: {}, Namespace: {}" ,pod.getMetadata().getName(), pod.getMetadata().getNamespace());
		InputStream fileStream = copy.copyFileFromPod(pod, "/etc/nginx/nginx.conf");
		String context = inputStream2String(fileStream);
		log.info("Context: {}", context);
	}
```

my request is copy file from pod, using token and cert file.
