### ISSUE TITLE
ExecExample does not work properly with stdin and throws a SocketTimeoutException

### ISSUE THREAD

**Issue by slyoldfox** [kubernetes-client/java#603]
There seems to be something wrong with the ExecSample (or deeper) in how the stdin is passed to the exec api. It seems to be waiting to the websocket to generate more data, while no data will come.

A normal command seems to work:
```
$ mvn exec:java -Dexec.mainClass="io.kubernetes.client.examples.ExecExample" -Dexec.args="botkube-558567576f-vdwrz botkube hostname"

botkube-558567576f-vdwrz
```

A command using stdin via kubectl works also
```
$ kubectl exec -i botkube-558567576f-vdwrz -n botkube cat  < test.sh
echo 'hello'
```
I'm not sure where to begin debugging this, it seems that the websocket from Exec in combination with stdin seems to remain open. This does not seem to happen with Exec without stdin.

```
$ mvn exec:java -Dexec.mainClass="io.kubernetes.client.examples.ExecExample" -Dexec.args="botkube-558567576f-vdwrz botkube cat" < test.sh
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] -----------------< io.kubernetes:client-java-examples >-----------------
[INFO] Building client-java-examples 5.0.0
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ client-java-examples ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
echo 'hello'
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 14 more
```

To reproduce:
```
$ git clone --recursive https://github.com/kubernetes-client/java
$ git checkout -f release-5.0
$ cd java/examples
$ echo "echo 'hello'"> test.sh
$ mvn exec:java -Dexec.mainClass="io.kubernetes.client.examples.ExecExample" -Dexec.args="pod namespace sh" < test.sh
```

**Comment by brendandburns** [comment]
Is the issue that the example hangs?

This is because the thread copying stdin will never stop. I suppose the example could call `System.exit(0)` in the example code...

**Comment by brendandburns** [comment]
e.g. it's not really a bug in the library, it's a bug/incompleteness in the example code.

**Comment by slyoldfox** [comment]
I’ll have a look if i can improve the example somewhat after i get back from holidays, thanks for the pointer!
I thought i could have just closed the stdin stream, but i basically need to abort the stdin thread.
