### ISSUE TITLE
java.lang.LinkageError: loader constraint violation: loader

### ISSUE THREAD

**Issue by Nancy-Chauhan** [kubernetes-client/java#663]
I try to use Kubernetes client in groovy script and call it with Grab , I get the following error when I run the script to Jenkins

```
java.lang.LinkageError: loader constraint violation: loader (instance of org/jenkinsci/plugins/workflow/cps/CpsGroovyShell$CleanGroovyClassLoader) previously initiated loading for a different type with name "okio/BufferedSource"
	at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:224)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:801)
	at io.kubernetes.client.apis.CoreV1Api.listNamespaceWithHttpInfo(CoreV1Api.java:15864)
	at io.kubernetes.client.apis.CoreV1Api.listNamespace(CoreV1Api.java:15842)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.grofers.K8sClient.getNamespaces(K8sClient.groovy:27)
	at k8Deployment.call(k8Deployment.groovy:9)
	at WorkflowScript.run(WorkflowScript:8)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:84)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	```

Does it happen with the contradiction of versions

**Comment by Nancy-Chauhan** [comment]
@yue9944882 Can you please help me with this issue

**Comment by yue9944882** [comment]
sounds like a duplicate of #474

**Comment by Nancy-Chauhan** [comment]
Thank you @yue9944882
