### ISSUE TITLE
How to use Exec with stdin correctly?

### ISSUE THREAD

**Issue by Traderjoe95** [kubernetes-client/java#685]
I am trying to implement a utility to copy files to pods, not only the other way round. I am using the 6.0.1 client with a Kubernetes 1.14 cluster. 

For copying, I create a `Base64InputStream` and open an exec session, using the `Exec` utility like described in the `ExecExample`. The input stream is then piped into the process. The command I use is `new String[]{"sh", "-c", "base64 -d > test.txt"}`.  This is the relevant part of my reproducer:

```java
ApiClient apiClient = ClientBuilder.kubeconfig(
KubeConfig.loadKubeConfig(new FileReader(System.getProperty("user.home") + "/.kube/config"))).build();
apiClient.getHttpClient().setReadTimeout(0, TimeUnit.SECONDS);
apiClient.getHttpClient().setWriteTimeout(0, TimeUnit.SECONDS);

Base64InputStream b64is = new Base64InputStream(new ByteArrayInputStream("test-content".getBytes()), true);

Exec exec = new Exec(apiClient);
Process proc = exec.exec("mtt-kube", "cassandra-0", new String[]{"sh", "-c", "base64 -d > test2.txt"}, true);

Thread in = new Thread(() -> {
    try {
        ByteStreams.copy(b64is, proc.getOutputStream());
    } catch (IOException ex) {
        ex.printStackTrace();
    }
});
in.start();

Thread out = new Thread(() -> {
    try {
        ByteStreams.copy(proc.getInputStream(), System.out);
    } catch (IOException ex) {
        ex.printStackTrace();
    }
});
out.start();

proc.waitFor();
in.join();
out.join();

proc.destroy();

System.exit(proc.exitValue());
```

#### Expected behavior
The process terminates after the input stream is fully piped into the process.

#### Actual behavior
The call for `process.waitFor()` never terminates.

**Comment by brendandburns** [comment]
I will try to reproduce this with your code sample.

**Comment by brendandburns** [comment]
I thought about this some more. I believe that you need to explicitly close `proc.getOutputStream()`

`ByteStreams.copy(...)` won't do that for you and if you don't close that stream, then there is no way that `cat` knows that you're done writing to `stdin`

Try updating your code to add `proc.getOutputStream().close()` after the copy. I bet that will fix things for you.

**Comment by Traderjoe95** [comment]
Thank you for your suggestion. I just tried closing the output stream of the process but it doesn't terminate the process. Apparently, the stdin of the remote process isn't closed when the web socket stream closes. When investigating this further, I found that `WebSocketOutputStream` inherits from the abstract `OutputStream` which has an empty `close()` method - that means the stream isn't actually closed. I guess, that is because closing a single stream without closing the entire `WebSocketStreamHandler` is not supported (which is reasonable, I believe). That said, the only option I can think of to close the stream, or rather, handler, would be subclassing the `Exec` class to get access to the handler. But that could mean that possible output will be cut off, because the web socket is closed before the output is written.

Apart from that, I tried another thing: I thought about how terminating the stdin on a regular bash works. In that case you would type your input and press `Ctrl+D` (twice?) to send EOF on the stdin. So I tried sending a two `proc.getOutputStream().write(new byte[]{4, 4})` bytes, which corresponds to pressing `Ctrl+D` twice on the actual shell. At first it didn't change anything but when I activated the TTY mode, it actually terminated the process. Also, the file was copied successfully. There are two things remaining, though:

1. Surprisingly, the input to the `base64` command is reflected to the output stream, i.e. appears on my console, which is not normal behavior of `base64`.
2. When the `ExecProcess` terminates, it tries to close the web socket handler, which fails with an `IOException` because the socket was already closed before. I suppose, that happens on the server side when the shell closes the input stream to `base64`. The stacktrace is below:
```
09:55:58.960 [OkHttp https://192.168.3.47:6443/api/v1/namespaces/mtt-kube/pods/cassandra-0/exec?stdin=true&stdout=true&stderr=true&tty=true&command=bash&command=-c&command=base64+-d+%3E+test2.txt WebSocket Close Reply] ERROR io.kubernetes.client.util.WebSocketStreamHandler - Error on close socket
java.io.IOException: closed
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:119) ~[okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111) ~[okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket.close(RealWebSocket.java:168) ~[okhttp-ws-2.7.5.jar:?]
	at io.kubernetes.client.util.WebSocketStreamHandler.close(WebSocketStreamHandler.java:98) [client-java-6.0.1.jar:?]
	at io.kubernetes.client.Exec$ExecProcess$1.close(Exec.java:282) [client-java-6.0.1.jar:?]
	at io.kubernetes.client.util.WebSockets$Listener.onClose(WebSockets.java:145) [client-java-6.0.1.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:197) [okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket.access$200(RealWebSocket.java:38) [okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:84) [okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) [okhttp-2.7.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by brendandburns** [comment]
One other note that I noticed, I actually implemented `Process.destroy()` to close the stream(s) so you could always call that once all of the output is written...

**Comment by frezbo** [comment]
I'm using the example provided and the code doesn't seem to close the stream.

**Code:**

```java
package com.frezbo.k8s;

import java.io.FileReader;
import java.io.IOException;

import com.google.common.io.ByteStreams;

import io.kubernetes.client.Exec;
import io.kubernetes.client.openapi.ApiClient;
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.Configuration;
import io.kubernetes.client.util.ClientBuilder;
import io.kubernetes.client.util.KubeConfig;


/**
 * Sample code to run commands on a running pod
 */
public class K8sExec {
    public static void main(String[] args) throws IOException, ApiException, InterruptedException {
        // file path to your KubeConfig
        String kubeConfigPath = System.getenv("HOME") + "/work/k8s/rootless/kube_config.yml";

        // loading the out-of-cluster config, a kubeconfig from file-system
        ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();

        // set the global default api-client to the in-cluster one from above
        Configuration.setDefaultApiClient(client);

        Exec exec = new Exec();
        final Process proc = exec.exec("frezbo", "rootless", new String[] { "sh", "-c", "echo foo && exit" }, false);

        Thread in = new Thread(new Runnable() {
            public void run() {
                try {
                    ByteStreams.copy(System.in, proc.getOutputStream());
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        });
        in.start();

        Thread out = new Thread(new Runnable() {
            public void run() {
                try {
                    ByteStreams.copy(proc.getInputStream(), System.out);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        });
        out.start();

        // wait for any last output; no need to wait for input thread
        out.join();

        proc.destroy();
        System.out.println(proc.exitValue());
        // System.out.println(proc.getOutputStream());
        // System.out.println(proc.getErrorStream());
    }
}

```

**Output:**

```bash
k8s_exec (aws:none)(kc:none)$ mvn exec:java -Dexec.mainClass="com.frezbo.k8s.K8sExec"
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.frezbo.k8s:k8s_exec:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 15, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------------------< com.frezbo.k8s:k8s_exec >-----------------------
[INFO] Building k8s_exec 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ k8s_exec ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/Users/ngeorgi/.m2/repository/org/bouncycastle/bcprov-ext-jdk15on/1.61/bcprov-ext-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
foo
java.io.IOException: Pipe broken
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:321)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.InputStream.read(InputStream.java:213)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:109)
	at com.frezbo.k8s.K8sExec$2.run(K8sExec.java:47)
	at java.base/java.lang.Thread.run(Thread.java:830)
0
^Ck8s_exec (aws:none)(kc:none)$
```

The code get's stuck there, and I have to `Ctrl + C` to exit

**Comment by frezbo** [comment]
**Update**

The thread dies after around 5 minutes of waiting with this error:

```bash
[WARNING] thread Thread[OkHttp ConnectionPool,5,com.frezbo.k8s.K8sExec] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[OkHttp ConnectionPool,5,com.frezbo.k8s.K8sExec] will linger despite being asked to die via interruption
[WARNING] NOTE: 1 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.frezbo.k8s.K8sExec,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:775)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:18 min
[INFO] Finished at: 2020-02-25T07:17:08+05:30
[INFO] ------------------------------------------------------------------------
```


If I remove the `in` and `out` threads and just use the `exitValue()`, I don't get the broken pipe error but still it waits around 5 minutes for the proc to exit.

**Comment by swzaaaaaaa** [comment]
> tract `OutputStream` whi

Can you send me the full code? Thank you
