### ISSUE TITLE
copyFileFromPod (and likely exec) does not propagate errors

### ISSUE THREAD

**Issue by ceeaspb** [kubernetes-client/java#686]
Running copyFileFromPod on a non existent from file to copy results in some log lines printed but no error to the calling code:

```
java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
    at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
    at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
    at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

If the namespace does not exist then a different log message but again not passed on for handling:

```
java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
    at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
    at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
    at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

There are probably other instances of this.
Exec doesn't appear to handle errors or return codes.

**Comment by yue9944882** [comment]
> 500 Internal Server Error

500 error normally suggests a BUG in the kube-apiserver, appreciated if you can provide more details..

basically, EXEC is trying to establish a web-socket connection w/ the apiserver, so it will surely be failing when the server doesn't respond to promote the connection.. i'm slight leaning on using a try-catch block to wrap the call

**Comment by ceeaspb** [comment]
ok `kubectl -v=9` shows 500 error response when the container is stopped but the pod exists because there are other containers in the pod still running.

This ticket is more about the lack of error handling as the exec process used by copy does not check the exec return code. As far as I can tell It is not possible to determine whether the copy was successful or not.

https://github.com/kubernetes-client/java/blob/632d6c5a17e9bc2d3c69d5d05cb36ee42044d072/util/src/main/java/io/kubernetes/client/Copy.java#L65

https://github.com/kubernetes-client/java/blob/632d6c5a17e9bc2d3c69d5d05cb36ee42044d072/util/src/main/java/io/kubernetes/client/Copy.java#L110

Compared with for example the exec example:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java#L108
