### ISSUE TITLE
How to find out root cause "io.kubernetes.client.ApiException: Bad Request" exception?

### ISSUE THREAD

**Issue by liboyue23** [kubernetes-client/java#695]
Here is my code:
```
public class Test {
    private CoreV1Api api;
    protected static final Logger logger = LoggerFactory.getLogger(Test.class);
    private static final String ANTI_AFFINITY_KEY = "app";
    private static final int VM_CALL_RETRY_TIMES = 0;

    @Before
    public void init() throws IOException {
        ApiClient client = Config.fromConfig("/Users/lee/.kube/config");
        client.setDebugging(true);
        Configuration.setDefaultApiClient(client);
        api = new CoreV1Api();

    }

    @Test
    public void testDrds() {
        String name = createVmInstance("zxc","nginx:1.7.9","1c2g","xxx");

    }

    public String createVmInstance(String name, String image, String specType, String affinity) {

        String dockerName = "drds-server-" + name;
        int retryTimes = 0;
        V1Pod body = new V1Pod();
        while (true) {
            try {
                body.setApiVersion("v1");
                body.setKind("Pod");
                V1ObjectMeta meta = new V1ObjectMeta();
                meta.setName(dockerName);
                Map<String, String> labelMap = Maps.newHashMap();
                labelMap.put(ANTI_AFFINITY_KEY, dockerName);
                meta.setLabels(labelMap);
                body.setMetadata(meta);
                V1PodSpec spec = new V1PodSpec();
                V1Container container = new V1Container();
                container.setName("drds-server");
                container.setImage(image);
                container.setImagePullPolicy("Always");
                container.setEnv(buildEnv());
                container.setResources(buildResource(specType));
                container.setLivenessProbe(buildLivenessProbe());
                container.setReadinessProbe(buildReadinessProbe());

                List<V1Container> list = Lists.newArrayList();
                list.add(container);
                spec.setContainers(list);
                spec.setRestartPolicy("Always");
                //spec.setAffinity(buildAffinity(affinity));
                body.setSpec(spec);
                logger.info("V1Pod body is : " + body.toString());
                V1Pod result = api.createNamespacedPod(getDefaultNamespace(), body, false, "true", null);

                return dockerName;
            } catch (Throwable e) {
                String error = String.format(
                    "failed calling k8s Api createVmInstance , ErrorMessage: %s , V1Pod body : %s",
                    e.getMessage(), body.toString());
                logger.error(String
                    .format("failed calling k8s Api createVmInstance , V1Pod body : %s",
                        body.toString()), e);
                if (++retryTimes < VM_CALL_RETRY_TIMES) {
                    try {
                        Thread.sleep(3000);
                    } catch (InterruptedException e1) {
                        logger.error("retry sleep error", e1);
                    }
                    logger.warn(error, e);
                } else {
                    logger.error(String
                        .format("failed calling k8s Api createVmInstance : %s , V1Pod body : %s",
                            body.toString()), e);
                }
            }

        }

    }

    private V1Affinity buildAffinity(String labelName) {
        V1Affinity affinity = new V1Affinity();
        V1PodAntiAffinity podAntiAffinity = new V1PodAntiAffinity();
        List<V1PodAffinityTerm> podAffinityTermList = Lists.newArrayList();
        V1PodAffinityTerm podAffinityTerm = new V1PodAffinityTerm();
        V1LabelSelector v1LabelSelector = new V1LabelSelector();
        List<V1LabelSelectorRequirement> v1LabelSelectorRequirementList = Lists.newArrayList();
        V1LabelSelectorRequirement v1LabelSelectorRequirement = new V1LabelSelectorRequirement();
        v1LabelSelectorRequirement.setKey(ANTI_AFFINITY_KEY);
        v1LabelSelectorRequirement.setOperator("In");
        List<String> values = Lists.newArrayList();
        values.add(labelName);
        v1LabelSelectorRequirement.setValues(values);
        v1LabelSelectorRequirementList.add(v1LabelSelectorRequirement);
        v1LabelSelector.setMatchExpressions(v1LabelSelectorRequirementList);
        podAffinityTerm.setLabelSelector(v1LabelSelector);
        podAffinityTerm.setTopologyKey("kubernetes.io/hostname");
        podAffinityTermList.add(podAffinityTerm);
        podAntiAffinity.setRequiredDuringSchedulingIgnoredDuringExecution(podAffinityTermList);
        affinity.setPodAntiAffinity(podAntiAffinity);
        return affinity;
    }

    //private String buildImageId(ARequestCreateVmInstance requestCreateVmInstance) {
    //    String ecsImageId = requestCreateVmInstance.getImageId();
    //    if (ecsImageId != null) {
    //        ecsImageId = ecsImageId.replace('#', ':');
    //    }
    //    return ecsImageId;
    //}

    private V1Probe buildLivenessProbe() {
        V1Probe probe = new V1Probe();
        V1ExecAction execAction = new V1ExecAction();
        execAction.addCommandItem("/bin/sh").addCommandItem("-c").addCommandItem("python /checkHealth.py");
        probe.setExec(execAction);
        probe.setTimeoutSeconds(300);
        probe.setInitialDelaySeconds(600);
        return probe;
    }

    private V1Probe buildReadinessProbe() {
        V1Probe probe = new V1Probe();
        V1ExecAction execAction = new V1ExecAction();
        execAction.addCommandItem("/bin/sh").addCommandItem("-c").addCommandItem("python /checkHealth.py");
        probe.setExec(execAction);
        probe.setPeriodSeconds(5);
        probe.setInitialDelaySeconds(10);
        return probe;
    }

    private Map<String, String> getEnvMap() {
        Properties props = null;
        try {
            props = PropertiesLoaderUtils.loadAllProperties("test.properties");
        } catch (IOException e) {
            e.printStackTrace();
        }
        Map<String, String> immutableMapmap = Maps.fromProperties(props);
        Map<String, String> map = Maps.newHashMap(immutableMapmap);
        return map;
    }

    private String getDefaultNamespace() {
        return "default";
    }

    private List<V1EnvVar> buildEnv() {
        Map<String, String> map = getEnvMap();
        List<V1EnvVar> envList = map2List(map);
        return envList;
    }

    private List<V1EnvVar> map2List(Map<String, String> envMap) {
        List<Map.Entry<String, String>> list = new ArrayList<Map.Entry<String, String>>(envMap.entrySet());
        List<V1EnvVar> result = Lists.newArrayList();

        for (Map.Entry<String, String> e : list) {
            V1EnvVar envVar = new V1EnvVar();
            envVar.setName(e.getKey());
            envVar.setValue(e.getValue());
            result.add(envVar);
        }
        return result;
    }

    private V1ResourceRequirements buildResource(String spec) {
        Map<String, String> parseSpec = parseSpec(spec);
        String mem = parseSpec.get("mem");
        String cpu = parseSpec.get("cpu");
        V1ResourceRequirements resourceRequirements = new V1ResourceRequirements();
        Long m = Integer.valueOf(mem) * 1024L;
        Quantity memoryQuantity = new QuantityFormatter().parse(String.valueOf(m) + "Mi");
        Quantity cpuQuantity = new QuantityFormatter().parse(cpu);
        resourceRequirements.putLimitsItem("memory", memoryQuantity);
        resourceRequirements.putLimitsItem("cpu", cpuQuantity);
        resourceRequirements.putRequestsItem("memory", memoryQuantity);
        resourceRequirements.putRequestsItem("cpu", cpuQuantity);
        return resourceRequirements;
    }

    private Map<String, String> parseSpec(String spec) {
        Map<String, String> map = Maps.newHashMap();

        char[] charArray = spec.toCharArray();
        StringBuilder cpuSb = new StringBuilder();
        StringBuilder memSb = new StringBuilder();
        boolean isCpu = true;
        for (int i = 0; i < charArray.length; i++) {
            if (charArray[i] != 'c' && isCpu) {
                cpuSb.append(charArray[i]);
            } else if (charArray[i] == 'c') {
                isCpu = false;
            } else if (charArray[i] != 'g' && !isCpu) {
                memSb.append(charArray[i]);
            } else if (charArray[i] == 'g') {
                break;
            }
        }

        String cpu = cpuSb.toString();
        String mem = memSb.toString();
        map.put("cpu", cpu);
        map.put("mem", mem);
        return map;
    }
}

```

I print V1Pod body: 
```
class V1Pod {
    apiVersion: v1
    kind: Pod
    metadata: class V1ObjectMeta {
        annotations: null
        clusterName: null
        creationTimestamp: null
        deletionGracePeriodSeconds: null
        deletionTimestamp: null
        finalizers: null
        generateName: null
        generation: null
        initializers: null
        labels: {app=drds-server-f397e1a4-e121-4a82-a5fd-6816b5a820b9}
        name: drds-server-f397e1a4-e121-4a82-a5fd-6816b5a820b9
        namespace: null
        ownerReferences: null
        resourceVersion: null
        selfLink: null
        uid: null
    }
    spec: class V1PodSpec {
        activeDeadlineSeconds: null
        affinity: class V1Affinity {
            nodeAffinity: null
            podAffinity: null
            podAntiAffinity: class V1PodAntiAffinity {
                preferredDuringSchedulingIgnoredDuringExecution: null
                requiredDuringSchedulingIgnoredDuringExecution: [class V1PodAffinityTerm {
                    labelSelector: class V1LabelSelector {
                        matchExpressions: [class V1LabelSelectorRequirement {
                            key: app
                            operator: In
                            values: [f397e1a4-e121-4a82-a5fd-6816b5a820b9]
                        }]
                        matchLabels: null
                    }
                    namespaces: null
                    topologyKey: kubernetes.io/hostname
                }]
            }
        }
        automountServiceAccountToken: null
        containers: [class V1Container {
            args: null
            command: null
            env: [class V1EnvVar {
                name: room_id
                value: cn-qd-hyq-d01
                valueFrom: null
            }, class V1EnvVar {
                name: deploy_mode
                value: private
                valueFrom: null
            }, class V1EnvVar {
                name: advancedSecurity
                value: true
                valueFrom: null
            }, class V1EnvVar {
                name: dncs_server_list
                value: 
                valueFrom: null
            }, class V1EnvVar {
                name: manager_reg_domain
                value: 172.16.190.244,172.16.190.245
                valueFrom: null
            }, class V1EnvVar {
                name: manager_domain_ip
                value: drds-manager-inner.drds.cn-qd-hyq-d01.paas.com
                valueFrom: null
            }, class V1EnvVar {
                name: manager_grab_port
                value: 8080
                valueFrom: null
            }, class V1EnvVar {
                name: region_id
                value: cn-qd-hyq-d01
                valueFrom: null
            }, class V1EnvVar {
                name: enable_vipclient
                value: 
                valueFrom: null
            }, class V1EnvVar {
                name: default_namespace
                value: drds
                valueFrom: null
            }]
            envFrom: null
            image: drds-server@sha256:d9752d2cb36141f0430cd5b8827c198d7fc7b5bf02dfa09d5580c8d5ddfe3f17
            imagePullPolicy: Always
            lifecycle: null
            livenessProbe: class V1Probe {
                exec: class V1ExecAction {
                    command: [/bin/sh, -c, python /checkHealth.py]
                }
                failureThreshold: null
                httpGet: null
                initialDelaySeconds: 600
                periodSeconds: null
                successThreshold: null
                tcpSocket: null
                timeoutSeconds: 300
            }
            name: drds-server
            ports: null
            readinessProbe: class V1Probe {
                exec: class V1ExecAction {
                    command: [/bin/sh, -c, python /checkHealth.py]
                }
                failureThreshold: null
                httpGet: null
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: null
                tcpSocket: null
                timeoutSeconds: null
            }
            resources: class V1ResourceRequirements {
                limits: {memory=Quantity{number=8589934592, format=BINARY_SI}, cpu=Quantity{number=4, format=DECIMAL_SI}}
                requests: {memory=Quantity{number=8589934592, format=BINARY_SI}, cpu=Quantity{number=4, format=DECIMAL_SI}}
            }
            securityContext: null
            stdin: null
            stdinOnce: null
            terminationMessagePath: null
            terminationMessagePolicy: null
            tty: null
            volumeDevices: null
            volumeMounts: null
            workingDir: null
        }]
        dnsConfig: null
        dnsPolicy: null
        hostAliases: null
        hostIPC: null
        hostNetwork: null
        hostPID: null
        hostname: null
        imagePullSecrets: null
        initContainers: null
        nodeName: null
        nodeSelector: null
        priority: null
        priorityClassName: null
        readinessGates: null
        restartPolicy: Always
        runtimeClassName: null
        schedulerName: null
        securityContext: null
        serviceAccount: null
        serviceAccountName: null
        shareProcessNamespace: null
        subdomain: null
        terminationGracePeriodSeconds: null
        tolerations: null
        volumes: null
    }
    status: null
}                   

```

io.kubernetes.client.ApiException: Bad Request
        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
        at io.kubernetes.client.apis.CoreV1Api.createNamespacedPodWithHttpInfo(CoreV1Api.java:8317)
        at io.kubernetes.client.apis.CoreV1Api.createNamespacedPod(CoreV1Api.java:8299)

I didn't know why the reason it failed

**Comment by brendandburns** [comment]
`ApiException` has a function to get the response body, that will contain more details from the Kubernetes API server.

Closing since the question is answered.

**Comment by liboyue23** [comment]
> `ApiException` has a function to get the response body, that will contain more details from the Kubernetes API server.
> 
> Closing since the question is answered.

But I trace into the SDK, and found only useful message is response.message, and response.body is null, why?
![image](https://user-images.githubusercontent.com/11264082/64577700-c20ed400-d3af-11e9-99fb-0f7fb52cf08e.png)

**Comment by yue9944882** [comment]
/reopen

>         client.setDebugging(true);

can you show us the json payload of your request from the debugging output?

**Comment by liboyue23** [comment]
> /reopen
> 
> > ```
> >     client.setDebugging(true);
> > ```
> 
> can you show us the json payload of your request from the debugging output?

I set debugging(true) but there's no debug message output in the log file

**Comment by yue9944882** [comment]
`Unprocessable Entity` always suggests that your requesting payload is malformed/invalid, please check if the payload correspondingly

**Comment by brendandburns** [comment]
You should really use `ApiException.getResponseBody()` to get the response body and print it. There will be more details in that message.

https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/ApiException.java#L88
