### ISSUE TITLE
Error patching deployment using patchNamespacedDeployment after upgrading to client-jar 6.0.1

### ISSUE THREAD

**Issue by rsreeni** [kubernetes-client/java#761]
Hi,

 

I am unable to patch deployments with api patchNamespacedDeployment, after I updated to kubernetes-client.jar 6.0.1.

 

Previously I was using 3.0.0 and I updated to the latest one compatible with the k8s version we are running. Call using the old patchNamespacedDeployment worked fine.

 

But the new one, gets an error `cannot unmarshal object into Go value of type jsonpatch.Patch`  .  i turned API Debugging on and got this.

 

 

PATCH https://<ipaddress>/apis/apps/v1beta1/namespaces/integ/deployments/example-svc?pretty=false&fieldManager="sreeni-updater" HTTP/1.1

Content-Type: application/json-patch+json; charset=utf-8

Content-Length: 66

authorization:  <auth-token>

Accept: application/json

User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java

 

{"op":"add","path":"/metadata/labels/crashloop.count","value":"1"}

--> END PATCH (66-byte body)

<-- HTTP/1.1 400 Bad Request (5ms)

Content-Type: application/json

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"json: cannot unmarshal object into Go value of type jsonpatch.Patch","reason":"BadRequest","code":400}

 

<-- END HTTP (182-byte body)

2019-10-29 08:18:02.151 ERROR 1 --- [   scheduling-1] c.s.w.service.SreeniOperatorImpl         : Exception when calling AppsV1beta1Api#patchNamespacedDeployment

io.kubernetes.client.ApiException: Bad Request

        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)

        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)

        at io.kubernetes.client.apis.AppsV1beta1Api.patchNamespacedDeploymentWithHttpInfo(AppsV1beta1Api.java:3166)

        at io.kubernetes.client.apis.AppsV1beta1Api.patchNamespacedDeployment(AppsV1beta1Api.java:3146)

        at com.sreenihome.web.service.SreeniOperatorImpl.addLabelsToDeploymentByPatch(SreeniOperatorImpl.java:188)

        at com.sreenihome.web.controller.SreeniProcessor.countDeploymentRestart(SreeniProcessor.java:480)

        at com.sreenihome.web.controller.SreeniProcessor.lambda$processEachKubeMonitorProcess$11(SreeniProcessor.java:344)

        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)

        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)

        at com.sreenihome.web.controller.SreeniProcessor.processEachKubeMonitorProcess(SreeniProcessor.java:305)

        at com.sreenihome.web.controller.SreeniProcessor.lambda$processPods$5(SreeniProcessor.java:206)

        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)

        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)

        at com.sreenihome.web.controller.SreeniProcessor.processPods(SreeniProcessor.java:205)

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)

        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

`String jsonPatchStr = "{\"op\":\"add\",\"path\":\"/metadata/labels/" + labelName + "\",\"value\":\""

                + labelValue + "\"}";

        V1Patch body = new V1Patch(jsonPatchStr);

        try {

            AppsV1beta1Deployment result = apiInstance.patchNamespacedDeployment(deploymentName, namespace, body, FALSE_STRING,null,"sreeni-updater",null);`

Can anyone help fix this ? What am I doing wrong ?

I appreciate any help.

Thanks,
-Sreeni

**Comment by yue9944882** [comment]
> {"op":"add","path":"/metadata/labels/crashloop.count","value":"1"}

the correct payload for json-patch should array on the top according to https://tools.ietf.org/html/rfc6902. i.e. patch w/ `[{"op":"add","path":"/metadata/labels/crashloop.count","value":"1"}]` should work

**Comment by rsreeni** [comment]
Thanks, just padding the string with [ & ] worked. I was previously trying to create a V1Patch with an array  of JsonElements as a string and that wasnt working. Now I just padded the [ & ] and it worked like a charm.  Thanks a lot!

**Comment by githubyangxd** [comment]
I don't know how to use [&] .
String jsonPatchStr = "{"op":"add","path":"/metadata/labels/" + labelName + "","value":""+ labelValue + "\"}";

in where?

**Comment by gresockj** [comment]
> I don't know how to use [&] .
> String jsonPatchStr = "{"op":"add","path":"/metadata/labels/" + labelName + "","value":""+ labelValue + ""}";
> 
> in where?

I believe @rsreeni meant wrapping the `jsonPatchStr` in brackets.  "[ & ]" means [ and ].

So instead of:
```
String jsonPatchStr = "{"op":"add","path":"/metadata/labels/" + labelName + "","value":""+ labelValue + ""}";
```
use:
```
String jsonPatchStr = "[{"op":"add","path":"/metadata/labels/" + labelName + "","value":""+ labelValue + ""}]";
```
