### ISSUE TITLE
KeyError: 'paths'

### ISSUE THREAD

**Issue by sskmail14** [kubernetes-client/java#768]
Hai,

Am getting the below exception when am trying to generate the java code for my custom CRD

```
$ docker run -i --rm yue9944882/java-model-gen < /tmp/swagger | tar -xzf - -C /tmp/codegen-java/
CLIENT_VERSION: 5.0-SNAPSHOT
PACKAGE_NAME: io.kubernetes.client
CRD_GROUP_NAME not specified, won't prune the output directory after generation..

succesfully read openapi specs..
filtering with crd group name:
rendering settings file to /tmp/settings (inside container)
/source/swagger-codegen /
/
--- Downloading and pre-processing OpenAPI spec
Traceback (most recent call last):
  File "//preprocess_spec.py", line 357, in <module>
    sys.exit(main())
  File "//preprocess_spec.py", line 351, in main
    out_spec = process_swagger(in_spec, args.client_language)
  File "//preprocess_spec.py", line 119, in process_swagger
    spec = add_custom_objects_spec(spec)
  File "//preprocess_spec.py", line 109, in add_custom_objects_spec
    if path not in spec['paths'].keys():
KeyError: 'paths'

```

**Comment by yue9944882** [comment]
can you verify if `/tmp/swagger` is a legitimate swagger document?

**Comment by sskmail14** [comment]
@yue9944882 - Thanks for the response. It was my mess. Instead of generating the swagger response json I was trying to generate on my own CRD json which causes this issue.

I took the swagger json now with `kubectl get --raw="/swagger.json" > swagger`
earlier I did it with one of CRD url context

Now am able to generate the source code :)
