### ISSUE TITLE
Error on close socket|io.kubernetes.client.util.WebSocketStreamHandler

### ISSUE THREAD

**Issue by ceeaspb** [kubernetes-client/java#801]
Running against kubernetes 1.12.0 , I have upgraded from 5.0.0 to 6.0.1 and the following errors have started for `exec` and `copy` (which uses exec).

The api calls work. But the logs are going to fill up and be harder to read.
Thanks

```
2019-11-14 10:34:39.858|ERROR|OkHttp https://192.168.0.44:6443/api/v1/namespaces/stuff/pods/more-stuff/exec?stdin=false&stdout=true&stderr=true&tty=false&container=other&command=sh&command=-c&command=cat+%2Fvar%2Flog%2Fa.log+%7C+base64 WebSocket Close Reply||Error on close socket|io.kubernetes.client.util.WebSocketStreamHandler
java.io.IOException: closed
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:119) ~[okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111) ~[okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket.close(RealWebSocket.java:168) ~[okhttp-ws-2.7.5.jar:?]
	at io.kubernetes.client.util.WebSocketStreamHandler.close(WebSocketStreamHandler.java:98) [client-java-6.0.1.jar:?]
	at io.kubernetes.client.Exec$ExecProcess$1.close(Exec.java:282) [client-java-6.0.1.jar:?]
	at io.kubernetes.client.util.WebSockets$Listener.onClose(WebSockets.java:145) [client-java-6.0.1.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:197) [okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket.access$200(RealWebSocket.java:38) [okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:84) [okhttp-ws-2.7.5.jar:?]
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) [okhttp-2.7.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by brendandburns** [comment]
Ack. will take a look.

**Comment by rokii** [comment]
It seems this has not been resolved.

**Comment by rokii** [comment]
It is not reproduced in latest 8.0.0 release.  @brendandburns it could be closed.

**Comment by brendandburns** [comment]
Closing this.
