### ISSUE TITLE
Informer doesn't shutdown gracefully

### ISSUE THREAD

**Issue by shakeelrao** [kubernetes-client/java#815]
I'm building an Informer to list-watch pods across the entire cluster and noticed that when I stop the Informer, `main` simply hangs without returning. After checking a thread dump of the program, I noticed that the Reflector thread isn't terminated properly. Here's sample code to reproduce the issue:

```Java
import io.kubernetes.client.ApiClient;
import io.kubernetes.client.Configuration;
import io.kubernetes.client.apis.CoreV1Api;
import io.kubernetes.client.informer.*;
import io.kubernetes.client.models.V1Pod;
import io.kubernetes.client.models.V1PodList;
import io.kubernetes.client.util.CallGeneratorParams;
import io.kubernetes.client.util.Config;

import java.util.List;
import java.util.concurrent.TimeUnit;

public class InformerExample2 {
  public static void main(String[] args) throws Exception {
    ApiClient client = Config.defaultClient();
    client.getHttpClient().setReadTimeout(0, TimeUnit.SECONDS);
    Configuration.setDefaultApiClient(client);

    SharedInformerFactory factory = new SharedInformerFactory();

    CoreV1Api coreV1Api = new CoreV1Api();

    // Create a Pod Informer.
    SharedIndexInformer<V1Pod> informer = factory.sharedIndexInformerFor(
        (CallGeneratorParams params) -> {
          return coreV1Api.listPodForAllNamespacesCall(
              null,
              null,
              null,
              null,
              null,
              params.resourceVersion,
              params.timeoutSeconds,
              params.watch,
              null,
              null
          );
        },
        V1Pod.class,
        V1PodList.class
    );

    factory.startAllRegisteredInformers();

    // Wait a few seconds for the Pod Informer to start syncing.
    Thread.sleep(5000L);

    // List the number of pods the Informer has processed so far.
    List<V1Pod> podList = informer.getIndexer().list();
    System.out.println("Informer has processed " + podList.size() + " pods within the cluster");

    // Should exit normally here, but the JVM actually hangs since there is a non-daemon thread running.
    factory.stopAllRegisteredInformers();
  }
}
```

Here's the output from the thread dump as well:
```
"controller-reflector-io.kubernetes.client.models.V1Pod-0" #15 prio=5 os_prio=31 tid=0x00007fae3fa63800 nid=0xa703 runnable [0x000070000c81b000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	- locked <0x000000076b7896d8> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	- locked <0x000000076bda9b98> (a sun.security.ssl.AppInputStream)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:454)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:435)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at io.kubernetes.client.util.Watch.hasNext(Watch.java:181)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.watchHandler(ReflectorRunnable.java:128)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:81)
```

The underlying socket should be closed by `watch.close` in `ReflectorRunnable#run`, but for some reason it isn't.

Any thoughts?

**Comment by yue9944882** [comment]
> at io.kubernetes.client.util.Watch.hasNext(Watch.java:181)
	at io.kubernetes.client.informer.cache.ReflectorRunnable.watchHandler(ReflectorRunnable.java:128)

the reflector is designed to be shutting down gracefully, it should take a short period of time to release the reflector after you invoked `stopAllRegisteredInformers` (we signals an InterruptedException on stopping, then the reflector shall make sure the watch connection is closed before quitting in case of leakage).
