### ISSUE TITLE
Exec into pod results with 500 InternalServerError everytime

### ISSUE THREAD

**Issue by adreviko** [kubernetes-client/java#831]
I'm trying to exec inside the pod with shell command and so far I always get back 500 InternalServerException from Kubernetes client.

This is the code snippet I'm trying to run: 

```
try {
    Exec exec = new Exec(kubernetesService.getApiClient()); // Gets ApiClient from CoreV1Api which is injected into @ApplicationScoped bean (kubernetesService) via JAX-RS producer
    Process process = exec.exec(
        namespace,
        appId,
        new String[]{"ls"},
        true, // stdin
        false //tty
    );

    Thread in = new Thread(() -> {
        try {
            ByteStreams.copy(System.in, process.getOutputStream());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    });

    in.start();

    Thread out = new Thread(() -> {
        try {
            ByteStreams.copy(process.getInputStream(), System.out);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    });

    out.start();
    process.waitFor();
    // wait for any last output; no need to wait for input thread
    out.join();
    process.destroy();
} catch (ApiException | IOException | InterruptedException e) {
    e.printStackTrace();
}

...

This is what the producer looks like:

@ApplicationScoped
public class KubernetesClientProducer {

    @Produces
    @Dependent
    public CoreV1Api produceKubernetesClient() throws IOException {
        // Standard is - 1. kube config file or 2. cluster config
        ApiClient client = ClientBuilder.standard(false).build();
        return new CoreV1Api(client);
    }

}
```

This is the exception I keep getting:

```
java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

We have kubernetes server v1.13 and I've tried to upgrade to 5.0.0 Java client but with no success. I have also tried other commands like listNamespacedPod(...) via CoreV1Api with no problems.

Thanks in advance for you help.

**Comment by brendandburns** [comment]
The 500 is coming from the Kubernetes API Server, you'll need to pull the apiserver logs to see why it's throwing a 500 (it really shouldn't ever throw a 500)

Once you figure out why the apiserver is throwing 500, we should see if there's anything on the client side we should fix.

**Comment by mayurvpatil** [comment]
Facing same issue, could you help me to get those k8s API Server logs ?

**Comment by yue9944882** [comment]
500 response code normally suggests a bug in the kube-apiserver. there should be some clue in the kube-apiserver's log (better w/ verbosity set to >4).

**Comment by brendandburns** [comment]
Closing this issue due to no further responses. Please use the `/reopen` command if you need more assistance.

**Comment by charcharan** [comment]
Sorry to comment on closed issue.

Hi @adreviko, Are you able to resolve this issue, I am also facing the same ?
