### ISSUE TITLE
Can't create K8sDeployment object because of null creationTimestamp or deletionTimestamp fields in yaml file

### ISSUE THREAD

**Issue by ansh7jan** [kubernetes-client/java#845]
I copied the yaml file from an existing deployed resource in cluster. 
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
    creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80`

The file had null creationTimestamp. 
When we try to read the manifest file as an object using below, then this is throwing an exception
Yaml.loadAs(manifestFileYaml, V1Deployment.class)

The SDK is treating null as string value and giving the exception
`Caused by: java.lang.IllegalArgumentException: Invalid format: "null"
 at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
 at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)
 at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:65)
 at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:151)
 at org.joda.time.DateTime.<init>(DateTime.java:281)
 at io.kubernetes.client.util.Yaml$CustomConstructor.constructDateTime(Yaml.java:352)
 at io.kubernetes.client.util.Yaml$CustomConstructor.constructObject(Yaml.java:333)
 at `

Can we handle this.

**Comment by yue9944882** [comment]
null value is supported since yaml 1.2 spec https://yaml.org/spec/1.2/spec.html#id2805071
while the serialization library (snakeyaml) is yet only supporting 1.1 i suppose, according to its wiki page https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-yaml-syntax

**Comment by sarveshkaushal** [comment]
I don't think this can be handled because K8 client uses snakeyaml jar for this. You can remove this node and try.

**Comment by brendandburns** [comment]
Looks like we should switch to snakeyaml-engine:

https://mvnrepository.com/artifact/org.snakeyaml/snakeyaml-engine/1.0

**Comment by karthikkondapally** [comment]
@brendandburns @yue9944882 
I think this issue is closed with [PR-911](https://github.com/kubernetes-client/java/pull/911).
or are there still plans to move to snakeyaml-engine ?

**Comment by brendandburns** [comment]
I think this is fixed, closing.
