### ISSUE TITLE
"Content type \"text/html; charset=utf-8\" is not supported for type: class io.kubernetes.client.models.V1PodList

### ISSUE THREAD

**Issue by aris-totle** [kubernetes-client/java#849]
i am not able to use any of the functions in CoreV1Api / AppsV1Api with token based authentication. 
I am getting a content-type "xxxxx" not supported error.  It is fine when i read the configuration file locally from my computer.

Here is the function:- (replaced token and url with xxxxxxx)
 public List<String> ListAllPods() throws IOException, ApiException, JSONException {
       

        ApiClient client = Config.fromToken(xxxxxxx,xxxxxxx,false);
        Configuration.setDefaultApiClient(client);
        List<String> PodList = new ArrayList<>();
        CoreV1Api api = new CoreV1Api();
        V1PodList list = api.listNamespacedPod(null,null,null,null,null,null,null,null,null,null);

        return (List<String>) list;

    }

Here is the stacktrace:-

io.kubernetes.client.ApiException: Content type "text/html; charset=utf-8" is not supported for type: class io.kubernetes.client.models.V1PodList
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:680) ~[client-java-5.0.0.jar:na]
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:875) ~[client-java-5.0.0.jar:na]
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:802) ~[client-java-5.0.0.jar:na]
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:18720) ~[client-java-api-5.0.0.jar:na]
	at io.kubernetes.client.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:18698) ~[client-java-api-5.0.0.jar:na]
	at com.musigma.labs.service.implementation.ClusterServiceImplementation.ListAllPods(ClusterServiceImplementation.java:44) ~[classes/:na]
	at com.musigma.labs.controller.Controller.ListAllPods(Controller.java:33) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]

**Comment by brendandburns** [comment]
I don't think you're actually talking to a Kubernetes server. Check your config, I suspect you're connected to some other type of HTTP server. The Kubernetes API Server should never return content-type HTML

**Comment by riemann77** [comment]
i am using spring-boot framework for building a microservice , it is working fine when i am reading the configuration file directly from my computer , but the problem arises only when i use token based authentication

**Comment by riemann77** [comment]
the "handleresponse" function in the ApiClient is calling a deserialize function which is not able to convert the text/html to json , it is an issue with gson parser

**Comment by brendandburns** [comment]
The client shouldn't be talking to the kubernetes-dashboard URL, it should be talking to the Kubernetes API server URL.

The problem is that the server (in this case the Kubernetes dashboard) is returning a content type `"text/html"` that the client doesn't know how to handle.

If you create a config file where the server is the Kubernetes API server it should work correctly.

**Comment by brendandburns** [comment]
Closing this issue due to no response. If you need to reopen please use the `/reopen` command.

**Comment by kelthuzadx** [comment]
Solved by deferring initializaiton of CoreV1Api, i.e.:

```
    static {
        ApiClient client;
        try {
            client = Config.defaultClient();
            Configuration.setDefaultApiClient(client);
            api = new CoreV1Api();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

**Comment by kelthuzadx** [comment]
The initialization order of CoreV1Api and ApiClient causes many problems in our product. @brendandburns can we add explicit initialization orders for them to reduce potential misuses?
