### ISSUE TITLE
Support for OpenID Connect

### ISSUE THREAD

**Issue by mlbiam** [kubernetes-client/java#855]
I want to use the java api for a kubectl plugin but it looks like openid connect clients aren't supported:

```
[main] ERROR io.kubernetes.client.util.KubeConfig - Unknown auth provider: oidc
----- Scale Deployment Start -----
[main] WARN com.tremolosecurity.App - Exception had occured 
io.kubernetes.client.openapi.ApiException: Unauthorized
        at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:979)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
        at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespaceWithHttpInfo(CoreV1Api.java:16069)
        at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespace(CoreV1Api.java:16041)
        at com.tremolosecurity.App.getAllNameSpaces(App.java:91)
        at com.tremolosecurity.App.main(App.java:53)
```

I'd like to write an oidc implementation.  Which branch should I write it against?  master doesn't compile.

**Comment by brendandburns** [comment]
Master should compile. What errors are you seeing?

**Comment by mlbiam** [comment]
environment:
```
➜  java git:(master) java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
➜  java git:(master) mvn -version
executing mvnw instead of mvn
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /Users/mlb/.m2/wrapper/dists/apache-maven-3.5.0-bin/6ps54u5pnnbbpr6ds9rppcc7iv/apache-maven-3.5.0
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.1", arch: "x86_64", family: "mac"
```

build error:
```
0%: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImpl
Generating: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImplFluent
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Kubernetes Client API .............................. SUCCESS [  0.207 s]
[INFO] client-java-api .................................... FAILURE [02:02 min]
[INFO] client-java-proto .................................. SKIPPED
[INFO] client-java ........................................ SKIPPED
[INFO] client-java-extended ............................... SKIPPED
[INFO] client-java-examples ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:03 min
[INFO] Finished at: 2020-01-30T20:05:37-05:00
[INFO] Final Memory: 573M/3237M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project client-java-api: Fatal error compiling: io.sundr.SundrException: No getter found for property: instance on class: io.kubernetes.client.openapi.models.V1ClusterRoleBindingListFluentImpl -> [Help 1]
```

**Comment by mlbiam** [comment]
I also tried Java 11 with:

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 11.0.5, vendor: Oracle Corporation, runtime: /usr/local/Cellar/openjdk@11/11.0.5+10/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.1", arch: "x86_64", family: "mac"
```

but still no luck
```
[INFO] --- maven-bundle-plugin:3.5.0:bundle (default-bundle) @ client-java-api ---
[ERROR] Bundle io.kubernetes:client-java-api:bundle:8.0.1-SNAPSHOT : The default package '.' is not permitted by the Import-Package syntax.
 This can be caused by compile errors in Eclipse because Eclipse creates
valid class files regardless of compile errors.
The following package(s) import from the default package [io.kubernetes.client.openapi.models]
[ERROR] Error(s) found in bundle configuration
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kubernetes Client API 8.0.1-SNAPSHOT:
[INFO]
[INFO] Kubernetes Client API .............................. SUCCESS [  0.127 s]
[INFO] client-java-api .................................... FAILURE [01:15 min]
[INFO] client-java-proto .................................. SKIPPED
[INFO] client-java ........................................ SKIPPED
[INFO] client-java-extended ............................... SKIPPED
[INFO] client-java-examples ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:16 min
[INFO] Finished at: 2020-01-31T05:33:56-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:3.5.0:bundle (default-bundle) on project client-java-api: Error(s) found in bundle configuration -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :client-java-api
```

**Comment by mlbiam** [comment]
so this is interesting.  i fired up a centos 8 container and installed java 1.8 and maven and it compiled no problem:

```
Apache Maven 3.5.4 (Red Hat 3.5.4-5)
Maven home: /usr/share/maven
Java version: 1.8.0_232, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-2.el8_1.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.19.76-linuxkit", arch: "amd64", family: "unix"
```

**Comment by brendandburns** [comment]
Can you try running `mvn clean` and then re-compiling on your Mac?

Also see this issue about specific JVM Versions not working right:
https://github.com/kubernetes-client/java/issues/795

**Comment by mlbiam** [comment]
I ran clean on each try.  Saw #795, after trial and error the only VM that worked on mac was amazon's java 1.8.  That said i've got a basic version of oidc working.  need to add refresh and test cases so pr soon.

**Comment by brendandburns** [comment]
Closing this since #871 merged.
