### ISSUE TITLE
Copy.copyFileFromPod() does not close stream

### ISSUE THREAD

**Issue by ChangSurrey** [kubernetes-client/java#861]
API version: 7.0.0
I'm using the following code to copy a file from a specified pod's `sourcePath` to `destinationPath`.

```
Copy copy = new Copy();
try (InputStream is = copy.copyFileFromPod(namespace, podName, containerName, sourcePath);
FileOutputStream fos = new FileOutputStream(destinationPath)) {
            is.transferTo(fos);
            fos.flush();
}
catch (...)
```

While the file gets successfully copied over to `destinationPath` quickly (within 1-2s), and I've verified that the copied file's content is intact, the stream is never closed, which causes `is.transferTo(fos)` to never return. 

I've tried using `ByteStreams.copy(is, fos)` and it's the same outcome. 

As a result, after around 20-30s, I get an `IOException` that says `Pipe broken`: 
```
java.io.IOException: Pipe broken

	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:321)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at org.apache.commons.codec.binary.BaseNCodecInputStream.read(BaseNCodecInputStream.java:158)
	at java.base/java.io.InputStream.transferTo(InputStream.java:704)
(rest of stack trace)
```

In `Copy.java` the source code of the method I'm calling is: 
```
  public InputStream copyFileFromPod(String namespace, String pod, String container, String srcPath)
      throws ApiException, IOException {
    Process proc =
        this.exec(
            namespace,
            pod,
            new String[] {"sh", "-c", "cat " + srcPath + " | base64"},
            container,
            false,
            false);
    return new Base64InputStream(proc.getInputStream());
  }
```

This might be a bug?

**Comment by ChangSurrey** [comment]
I have reproduced the issue using the example at https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/CopyExample.java

**Comment by ChangSurrey** [comment]
I can also reproduce it using the `Exec` example at https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java, which is thrown at line 93: `ByteStreams.copy(proc.getInputStream(), System.out);`

```
java.io.IOException: Pipe broken
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:321)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:109)
```

**Comment by brendandburns** [comment]
Yeah, we should probably wait on the process to exit and then close the stream. Happy to take a PR for this.

**Comment by cxli2** [comment]
any updated on this issue? I find this issue in API version 7.0.0 and 8.0.0-alpha when hanle the process input form Exec.exec process.

**Comment by vyarosh** [comment]
I have the same issue and waiting for the official fix. Though I did working workaround based on JSCH expample: http://www.jcraft.com/jsch/examples/ScpFrom.java.html
`    public void copyToLocal(String podName, String remoteFile, String localFile) {
        LOGGER.info("Downloading \"{}\" file from {} to \"{}\"", remoteFile, podName, localFile);
        FileOutputStream fos = null;
        String prefix = null;
        if (new File(localFile).isDirectory()) {
            prefix = localFile + File.separator;
        }
        try {
            Process proc =
                    new Copy(getClient()).exec(
                            NAMESPACE,
                            podName,
                            new String[] {"sh", "-c", "cat " + remoteFile + " | base64"},
                            null,
                            false,
                            false);

            // get I/O streams for remote scp
            OutputStream out = proc.getOutputStream();
            InputStream in = proc.getInputStream();
            byte[] buf = new byte[1024];
            // send '\0'
            buf[0] = 0;
            out.write(buf, 0, 1);
            out.flush();
            while (true) {
                int c = checkAck(in);
                if (c != 'C') {
                    break;
                }
                // read '0644 '
                in.read(buf, 0, 5);
                long filesize = 0L;
                while (true) {
                    if (in.read(buf, 0, 1) < 0) {
                        // error
                        break;
                    }
                    if (buf[0] == ' ') {
                        break;
                    }
                    filesize = filesize * 10L + (long) (buf[0] - '0');
                }
                String file = null;
                for (int i = 0; ; i++) {
                    in.read(buf, i, 1);
                    if (buf[i] == (byte) 0x0a) {
                        file = new String(buf, 0, i);
                        break;
                    }
                }
                LOGGER.debug("filesize={}, file={}", filesize, file);
                // send '\0'
                buf[0] = 0;
                out.write(buf, 0, 1);
                out.flush();
                // read a content of localFile
                fos = new FileOutputStream(prefix == null ? localFile : prefix + file);
                int foo;
                while (true) {
                    foo = buf.length < filesize ? buf.length : (int) filesize;
                    foo = in.read(buf, 0, foo);
                    if (foo < 0) {
                        // error
                        break;
                    }
                    fos.write(buf, 0, foo);
                    filesize -= foo;
                    if (filesize == 0L) {
                        break;
                    }
                }
                fos.close();
                fos = null;

                if (checkAck(in) != 0) {
                    return;
                }
                // send '\0'
                buf[0] = 0;
                out.write(buf, 0, 1);
                out.flush();
            }
        } catch (Exception e) {
            throw new CustomException(e);
        } finally {
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException e) {
                    LOGGER.error("Fail to close OutputStream",e);
                }
            }
        }
        LOGGER.info("Copied successfully");
    }

    private static int checkAck(InputStream in) {
        try {
            int b = in.read();
            // b may be 0 for success,
            //          1 for error,
            //          2 for fatal error,
            //          -1
            if (b == 0 || b == -1) {
                return b;
            }
            // error or fatal error
            if (b == 1 || b == 2) {
                StringBuffer sb = new StringBuffer();
                int c;
                do {
                    c = in.read();
                    sb.append((char) c);
                } while (c != '\n');
                LOGGER.info(sb.toString());
            }
            return b;
        } catch (IOException e) {
            throw new CustomException(e);
        }
    }`
Hope this will be useful for somebody.

**Comment by malli31** [comment]
Is this fixed??
Any workaround here?

**Comment by malli31** [comment]
Trying this fix,
I built 8.0.1 and usking these jars for exec, 
seeing Below exception only after first call,

java.net.SocketException: Connection closed by remote host
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1547)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
	at okhttp3.internal.ws.WebSocketWriter.writeControlFrame(WebSocketWriter.java:146)
	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:106)
	at okhttp3.internal.ws.RealWebSocket.writeOneFrame(RealWebSocket.java:507)
	at okhttp3.internal.ws.RealWebSocket.lambda$new$0(RealWebSocket.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Any inputs here?

**Comment by gholliday100** [comment]
Hi is there any update on this?  Also seeing this exception when using the following example with 8.0.2 and 9.0.0:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java

java.net.SocketException: Socket is closed
at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1545)
at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1566)
at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
at okio.Okio$1.write(Okio.java:79)
at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
at okhttp3.internal.ws.WebSocketWriter.writeControlFrame(WebSocketWriter.java:146)
at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:106)
at okhttp3.internal.ws.RealWebSocket.writeOneFrame(RealWebSocket.java:507)
at okhttp3.internal.ws.RealWebSocket$1.run(RealWebSocket.java:159)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by malli31** [comment]
See if the client has exec permission

**Comment by gholliday100** [comment]
Seeing the above exception intermittently though, if it were a permissions issue would we not be seeing it all the time?

**Comment by brendandburns** [comment]
This is expected if the server closes the connection.

**Comment by panashka** [comment]
Hi,
If this is expected why statusCode is updated to -1975219. If actual command complete with status 0, eventually its code will be overwritten with -1975219. 
`    @Override
            public void failure(Throwable ex) {
              super.failure(ex);
              // TODO, it's possible we should suppress this error message, but
              // currently there's
              // no good place to surface the message, and without it, this will be
              // really hard to
              // debug.
              ex.printStackTrace();
              synchronized (ExecProcess.this) {
                // Try for a pretty unique error code, so if someone searches
                // they'll find this
                // code.
                statusCode = -1975219;
                isAlive = false;
                ExecProcess.this.latch.countDown();
              }
            }`
