### ISSUE TITLE
listNamespacedPod Exception

### ISSUE THREAD

**Issue by 1542254356** [kubernetes-client/java#925]
`api.listNamespacedPod("default",true,null,null,null,null,null,null,10,true);`

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $

	at com.google.gson.Gson.assertFullConsumption(Gson.java:908)
	at com.google.gson.Gson.fromJson(Gson.java:898)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.kubernetes.client.JSON.deserialize(JSON.java:108)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:672)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:875)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:802)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:16949)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:16926)
	at com.hjwblog.robo_cmp.api.PodApi.getPodByNamespace(PodApi.java:9)
	at com.hjwblog.robo_cmp.api.PodApiTest.getPodByNamespace(PodApiTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1405)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:543)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:904)
	... 73 more
```

```
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-07-03T15:31:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by 1542254356** [comment]
![image](https://user-images.githubusercontent.com/25589700/79828121-aa321080-83d2-11ea-821d-c6a39152486f.png)

body :
```
{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"nginx-app-2007220645-473vj","generateName":"nginx-app-2007220645-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/nginx-app-2007220645-473vj","uid":"77b48ecf-7c69-11ea-a70e-000c29be8c66","resourceVersion":"178065","creationTimestamp":"2020-04-12T02:58:20Z","labels":{"pod-template-hash":"2007220645","run":"nginx-app"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"nginx-app-2007220645\",\"uid\":\"8a3ef9d6-78e9-11ea-a70e-000c29be8c66\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"110362\"}}\n"},"ownerReferences":[{"apiVersion":"extensions/v1beta1","kind":"ReplicaSet","name":"nginx-app-2007220645","uid":"8a3ef9d6-78e9-11ea-a70e-000c29be8c66","controller":true}]},"spec":{"containers":[{"name":"nginx-app","image":"nginx:alpine","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeName":"127.0.0.1","securityContext":{}},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-12T02:58:21Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-20T04:47:51Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-12T02:58:21Z"}],"hostIP":"127.0.0.1","podIP":"172.17.0.2","startTime":"2020-04-12T02:58:21Z","containerStatuses":[{"name":"nginx-app","state":{"running":{"startedAt":"2020-04-20T04:47:50Z"}},"lastState":{"terminated":{"exitCode":255,"reason":"Error","startedAt":"2020-04-12T14:46:29Z","finishedAt":"2020-04-20T04:47:38Z","containerID":"docker://024681b846dbee153a112717cf0cd817ed2cfdf09de6e025bd5906c2faa84a53"}},"ready":true,"restartCount":2,"image":"nginx:alpine","imageID":"docker-pullable://docker.io/nginx@sha256:abe5ce652eb78d9c793df34453fddde12bb4d93d9fbf2c363d0992726e4d2cad","containerID":"docker://10491624c0cd3b705744837d538de33f6d33774d4137ae415b1d524722f6954a"}]}}}
{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"nginx-app-2007220645-w069t","generateName":"nginx-app-2007220645-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/nginx-app-2007220645-w069t","uid":"771a6c7b-7c69-11ea-a70e-000c29be8c66","resourceVersion":"178069","creationTimestamp":"2020-04-12T02:58:19Z","labels":{"pod-template-hash":"2007220645","run":"nginx-app"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"nginx-app-2007220645\",\"uid\":\"8a3ef9d6-78e9-11ea-a70e-000c29be8c66\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"110321\"}}\n"},"ownerReferences":[{"apiVersion":"extensions/v1beta1","kind":"ReplicaSet","name":"nginx-app-2007220645","uid":"8a3ef9d6-78e9-11ea-a70e-000c29be8c66","controller":true}]},"spec":{"containers":[{"name":"nginx-app","image":"nginx:alpine","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeName":"127.0.0.1","securityContext":{}},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-12T02:58:19Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-20T04:47:51Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-12T02:58:19Z"}],"hostIP":"127.0.0.1","podIP":"172.17.0.4","startTime":"2020-04-12T02:58:19Z","containerStatuses":[{"name":"nginx-app","state":{"running":{"startedAt":"2020-04-20T04:47:50Z"}},"lastState":{"terminated":{"exitCode":255,"reason":"Error","startedAt":"2020-04-12T14:46:29Z","finishedAt":"2020-04-20T04:47:38Z","containerID":"docker://29b604a54e246f573e0a3c201b198668596aefab9a77ed5b668cb79340e8d646"}},"ready":true,"restartCount":2,"image":"nginx:alpine","imageID":"docker-pullable://docker.io/nginx@sha256:abe5ce652eb78d9c793df34453fddde12bb4d93d9fbf2c363d0992726e4d2cad","containerID":"docker://7292e910db60751d5f5e9d6bec1782113909da599f7f873dd89124d96d57b248"}]}}}
{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"nginx-app-2007220645-w9fkz","generateName":"nginx-app-2007220645-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/nginx-app-2007220645-w9fkz","uid":"77127cab-7c69-11ea-a70e-000c29be8c66","resourceVersion":"178062","creationTimestamp":"2020-04-12T02:58:19Z","labels":{"pod-template-hash":"2007220645","run":"nginx-app"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"nginx-app-2007220645\",\"uid\":\"8a3ef9d6-78e9-11ea-a70e-000c29be8c66\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"110302\"}}\n"},"ownerReferences":[{"apiVersion":"extensions/v1beta1","kind":"ReplicaSet","name":"nginx-app-2007220645","uid":"8a3ef9d6-78e9-11ea-a70e-000c29be8c66","controller":true}]},"spec":{"containers":[{"name":"nginx-app","image":"nginx:alpine","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeName":"127.0.0.1","securityContext":{}},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-12T02:58:19Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-20T04:47:51Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-12T02:58:19Z"}],"hostIP":"127.0.0.1","podIP":"172.17.0.5","startTime":"2020-04-12T02:58:19Z","containerStatuses":[{"name":"nginx-app","state":{"running":{"startedAt":"2020-04-20T04:47:50Z"}},"lastState":{"terminated":{"exitCode":255,"reason":"Error","startedAt":"2020-04-12T14:46:29Z","finishedAt":"2020-04-20T04:47:38Z","containerID":"docker://f22501c3753a6a5276ca621dcfe5bf7a5a19a5628e9c3441c344e40f64220c0d"}},"ready":true,"restartCount":2,"image":"nginx:alpine","imageID":"docker-pullable://docker.io/nginx@sha256:abe5ce652eb78d9c793df34453fddde12bb4d93d9fbf2c363d0992726e4d2cad","containerID":"docker://71c371055883e9728e1650af0d81691cd239265292714506a1c3bfa1b4a04f37"}]}}}
{"type":"ADDED","object":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"nginx","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/nginx","uid":"b199f973-7991-11ea-a70e-000c29be8c66","resourceVersion":"178073","creationTimestamp":"2020-04-08T12:08:44Z","labels":{"app":"nginx"}},"spec":{"containers":[{"name":"nginx","image":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeName":"127.0.0.1","securityContext":{}},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-08T12:08:44Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-20T05:02:14Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-04-08T12:08:44Z"}],"hostIP":"127.0.0.1","podIP":"172.17.0.3","startTime":"2020-04-08T12:08:44Z","containerStatuses":[{"name":"nginx","state":{"running":{"startedAt":"2020-04-20T05:02:14Z"}},"lastState":{"terminated":{"exitCode":255,"reason":"Error","startedAt":"2020-04-12T14:48:17Z","finishedAt":"2020-04-20T04:47:38Z","containerID":"docker://69e95b2700032869388cd4f0cdae92400173b56b6b5eee3cbb0150250cbb4a72"}},"ready":true,"restartCount":2,"image":"nginx","imageID":"docker-pullable://docker.io/nginx@sha256:d81f010955749350ef31a119fb94b180fde8b2f157da351ff5667ae037968b28","containerID":"docker://c618f18b0a1cfd55c0f673bca186843431f03265e2c0f466b6279b2f446a5b53"}]}}}

```

returnType: io.kubernetes.client.models.V1PodList

**Comment by 1542254356** [comment]
And the following function is normal
```
api.listPodForAllNamespaces(null, null, null, null, null, null, null, null, null);
api.readNamespacedPodStatus("nginx","default",null);
api.readNamespacedServiceStatus("nginx-app","default",null);
 ```
```
nginx
nginx-app-2007220645-473vj
nginx-app-2007220645-w069t
nginx-app-2007220645-w9fkz

nginx

nginx-app
```

**Comment by brendandburns** [comment]
You set `watch` to true, but you're not using a watch method you're using the read method.

The server is returning Watch formatted data which doesn't parse into a namespace list.

Either set the watch parameter to false or use the watch client if you want to perform a watch.

**Comment by 1542254356** [comment]
thanks
