### ISSUE TITLE
Patch Deployment Error

### ISSUE THREAD

**Issue by leimort** [kubernetes-client/java#926]
I'm trying to patch a pod with a dummy metadata, so it will trigger a rolling restart. I am using k8s version 1.14 and patching is the only workaround to invoke rolling restart I have seen so far.

Patching works when I use kubectl patch, but when I use patch using java API, I get an error and I think it's because I haven't included the metadata when I deployed the pod. Is there an operation that adds instead of replaces a metadata of a pod when patching? I don't want to add the dummy metadata in my yaml file. Also, I'm open to suggestions on how else to achieve a rolling restart.

**Code**
` 
       String jsonPatchStr = "[{\"op\":\"replace\",\"path\":\"/spec/template/metadata/annotations/date\",\"value\":\"" + strDate + "\"}]";
        try {
            ExtensionsV1beta1Api api = new ExtensionsV1beta1Api(ClientBuilder.standard().build());
            api.patchNamespacedDeployment(podName, podNamespace,
                    new V1Patch(jsonPatchStr), null, null, null, null);
        } catch (Exception e) {
            e.printStackTrace();
        }
` 
**Error**
`io.kubernetes.client.ApiException: Unprocessable Entity
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.ExtensionsV1beta1Api.patchNamespacedDeploymentWithHttpInfo(ExtensionsV1beta1Api.java:5657)
	at io.kubernetes.client.apis.ExtensionsV1beta1Api.patchNamespacedDeployment(ExtensionsV1beta1Api.java:5637)
	at com.concentricai.kronos.executor.handlers.k8s.RestartK8sPodHandler.execute(RestartK8sPodHandler.java:54)
	at com.cognitree.kronos.executor.TaskExecutionService.lambda$submit$1(TaskExecutionService.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by brendandburns** [comment]
Your patch isn't parsing correctly for some reason. If you print the `ApiException.getResponseBody()` you'll probably get more details.

**Comment by brendandburns** [comment]
Closing this issue since no more help is requested. Please use the `/reopen` command if you need further assistance.
