### ISSUE TITLE
io.kubernetes.client.openapi.ApiException: java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by Lavie526** [kubernetes-client/java#978]
I have a cluster created in oracle OKE, now i try to connect that cluster in local shell with Kubernetes java clients API. 

String kubeConfigPath = "~/.kube/config";

KubeConfig config = KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath));

ApiClient client = ClientBuilder
        .kubeconfig(config)
        .build();
client.setConnectTimeout(60*1000);
client.setReadTimeout(60*1000);
client.setDebugging(true);
Configuration.setDefaultApiClient(client);

CoreV1Api api = new CoreV1Api();

V1PodList list = api.listNamespacedPod("default", true, null,
        null, null, null,
        null, null, null,
        null
);

for (V1Pod item : list.getItems()) {
    System.out.println(item.getMetadata().getName());
}

However, while run, there are socket time out exception, i have set the time out to 60seconds.

INFO: <-- HTTP FAILED: java.net.SocketTimeoutException: connect timed out
io.kubernetes.client.openapi.ApiException: java.net.SocketTimeoutException: connect timed out
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:898)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespacesWithHttpInfo(CoreV1Api.java:19189)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listPodForAllNamespaces(CoreV1Api.java:19161)
	at com.oracle.bi.obis.TestAPIsMain.CreateDeployment(TestAPIsMain.java:143)
	at com.oracle.bi.obis.TestAPIsMain.main(TestAPIsMain.java:286)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:894)
	... 4 more
it works fine using kubectl, while they point to the same config file.
Any suggestions?

**Comment by brendandburns** [comment]
Something may be going wrong in your client building. I would just use the default:

```java
    ApiClient client = Config.defaultClient();
    Configuration.setDefaultApiClient(client);
```
For example:
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/Example.java#L34

You shouldn't need to manually construct the config/client yourself.

**Comment by Lavie526** [comment]
> Something may be going wrong in your client building. I would just use the default:
> 
> ```java
>     ApiClient client = Config.defaultClient();
>     Configuration.setDefaultApiClient(client);
> ```
> 
> For example:
> https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/Example.java#L34
> 
> You shouldn't need to manually construct the config/client yourself.

I also tried the default, but same exception.

**Comment by Lavie526** [comment]
It turns out that i didn't set the proxy while running my java application, not the kubernetes issue. Thanks for your time.
